### ISSUE TITLE
LiveSplit won't load my splits, .css

### ISSUE THREAD

**Issue by olly2001** [LiveSplit/LiveSplit#1011]
![untitled](https://user-images.githubusercontent.com/36572663/36344197-887dc942-140e-11e8-8ad1-7bf2a8be9e80.png)

**Comment by hallcristobal** [comment]
Could you upload the splits file?

**Comment by olly2001** [comment]
g

**Comment by olly2001** [comment]
I can't it says it doesn't support that file type.

**Comment by CryZe** [comment]
Zip it and then upload it

**Comment by olly2001** [comment]
[splits.zip](https://github.com/LiveSplit/LiveSplit/files/1734276/splits.zip)

**Comment by wooferzfg** [comment]
That file is a layout file. You might've accidentally overwritten your splits file while saving your layout.

**Comment by olly2001** [comment]
oh, shit. any way of reversing it?

**Comment by TheEssenceOfDarkness** [comment]
Unless you have a backup or uploaded them to splits.io, you will have to remake them. They are gone for good.

**Comment by just-ero** [comment]
The issue appears to have been resolved.
