### ISSUE TITLE
Help me to fix this please (time travel)

### ISSUE THREAD

**Issue by JMD49591** [LiveSplit/LiveSplit#1017]
Hello,
I have no real idea what I did to get this but I know its annoying once I reached that part.
Maybe it's a feature of Livesplit or smt but I don't know what I have to do to undo this.
Please help me to fix this.
Thanks

![livesplit bug](https://user-images.githubusercontent.com/36740020/36552149-764c78d8-17f9-11e8-809a-1317a645f401.JPG)

[WW.zip](https://github.com/LiveSplit/LiveSplit/files/1748808/WW.zip)

**Comment by TheEssenceOfDarkness** [comment]
You have a few options here.

1. You can use a backup of your splits file if you have one.

2. You can delete and recreate those splits losing the segment history for them.

3. You can just remove the times from the splis.

**Comment by JMD49591** [comment]
Ok I tried to do your second option because it was the best imo. And as I selected "Remove Sum of Best" Live Split automaticly detected that there is something wrong and remove some for me invisible time and now its correct.
So thank you anyways^^

**Comment by wooferzfg** [comment]
Edit Splits -> Other... -> Clean Sum of Best is the best way to fix this issue, for future reference.
