### ISSUE TITLE
Resource folder missing in Github release

### ISSUE THREAD

**Issue by SuiMachine** [LiveSplit/LiveSplit#1031]
As in the title the package that you can download from [http://livesplit.github.io/downloads/](http://livesplit.github.io/downloads/) is missing a **Resource** folder (with icons).
This results in **LiveSplit** registering file **extensions** in registry that have an icon file that points to non-existing file, which in turn results in windows falling back to using a (awful looking) default icon file.

**Comment by wooferzfg** [comment]
Should be fixed now.
