### ISSUE TITLE
Detailed Timer

### ISSUE THREAD

**Issue by Jervalin** [LiveSplit/LiveSplit#1035]
I cannot figure out how to get my second comparison to appear in the livesplit program under the detailed timer section.  I have gone through edit layout and clicked "detailed timer".  From there at the top of the new window there is an option off to the left that says "hide second comparison" or "hide comparison 2".  I do not have that box selected.  The goal I am trying to achieve is to get my "pb segment time" and my "best segment time" to appear once i start the timer.  No matter what settings I change the "best segment time" will not appear.  I have even gone to click on the second comparison drop down to make sure that the first and second comparisons are not set to the same setting.  When I try to do this I do not even have the option to change "comparison 2" to "best segments".  The only options I see are "current comparison", "personal best", and "latest run".  Is there any way to fix this?

**Comment by wooferzfg** [comment]
If you go to Settings -> Choose Active Comparisons, do you have Best Segments enabled?
