### ISSUE TITLE
LiveSplit doesn't open

### ISSUE THREAD

**Issue by kuroixxx** [LiveSplit/LiveSplit#1038]
Hello, some years ago I used LiveSplit 1.4.5 and it worked fine, but I had not used it for some time. Today I opened it and it asked to update. I accepted the update, but after the progress bar completed, the window disappeared and didn't show me anything else.
After waiting some time, I killed the proccess on taskmanager and tried to reopen it, but nothing happened: the proccess gets loaded again on taskmanager, but no window is shown.

So I downloaded LiveSplit again, this time the last version 1.7.5, unzipped it to a new folder, rebooted windows, tried opening it, but again nothing happens: the proccess is loaded on taskmanager, but no window is shown.

Based on suggestions from web, I've already tried:
- I've unplugged my Xbox controller (and also my PS2 controller) before opening it
- I have no antivirus software installed the could be blocking it (except for Windows Defender, but I can't find how it would be the issue)
- My Windows Event log shows me an error related to LiveSplit which says "Couldn't locate file 'C:\LiveSplit_1.7.5\settings.cfg'."
- I have Windows 10 Pro and .NET Framework 4.7.1 installed.
- EDIT:  also, tried running as administrator

I just can't use LiveSplit, why doesn't it open? What do I have to do?

Thanks in advance.

**Comment by TheEssenceOfDarkness** [comment]
Try redownloading it. You appear to be missing the settings file.

**Comment by just-ero** [comment]
Closing as stale.
