### ISSUE TITLE
Don't track Game Time if there's no Auto Splitter

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#104]
It shouldn't be Real Time by default

**Comment by CryZe** [comment]
Looks like this should definitely be in 1.6

**Comment by wooferzfg1** [comment]
If Game Time isn't being tracked, we might not want anything related to Game Time at all being shown (including removing it from the Splits Editor and SoB Clean Up) to make things easier for the user.

**Comment by wooferzfg1** [comment]
I think we want <ProvidesGameTime /> in the AutoSplitters.xml for backwards compatability and everything else should call state.ProvideGameTime(this);

Run Editor: Shows Game Time if the Splits have them
Internal Game Time: Has Game Time if there currently is a component that has it and store it in the splits afterwards.
Compare Against: Shows Game Time if there's currently a component providing it or if the splits have game time

Removing Game Time from the splits can be under the "Other..." button.
