### ISSUE TITLE
LiveSplit crashes when opening .lss file

### ISSUE THREAD

**Issue by FoolsLab** [LiveSplit/LiveSplit#1054]
When I open .lss split file at the path including non-ascii character by LiveSplit Developmet Build, it immediately crashes.
Opening layout file don't causes this bug.

**Comment by FoolsLab** [comment]
splits file
https://drive.google.com/open?id=1tJKyQxuJvXH6C4KbXs6XHvhVs3KLRgqQ
Path is "C:\テスト\test.lss".

**Comment by wooferzfg** [comment]
I wasn't able to reproduce this bug. Could you send your event logs from the time of this crash? https://pastebin.com/M3n52ABV

**Comment by FoolsLab** [comment]
event logs
https://drive.google.com/open?id=12O8isDs9tFhmiIJryR5oT3E9DYXtnw_U

**Comment by wooferzfg** [comment]
Which version of Windows are you using?

**Comment by CryZe** [comment]
Does it happen with an ascii path too, or does it need to have japanese characters?

**Comment by FoolsLab** [comment]
Japanese characters are necessary.
I use windows 10 Pro, version 1709(build 16299.371), but I reproduced similar bug also on another PC, windows 8.1 Pro, version 6.3(build 9600).
It occurs on LiveSplit Developmet Build(non-updated, 1.7.4-300) or LiveSplit built from source on my PC(13.3.7), and doesn't occur on updated LiveSplit Developmet Build or stable version(1.7.5).

**Comment by CryZe** [comment]
What do you mean with `doesn‘t occur on updated LiveSplit Developmet Build`. Does this mean the bug used to exist but is resolved on the latest master?

**Comment by CryZe** [comment]
Can you open cmd and then navigate into the livesplit folder and put in the following 2 commands?

![https://i.imgur.com/P3am7zD.png](https://i.imgur.com/P3am7zD.png)

```cmd
set RUST_BACKTRACE=1
LiveSplit.exe 2> text.txt
```

LiveSplit should then open and you want to make it crash then. Once it crashed, a text.txt file should be in the directory. Can you send me that file?

**Comment by FoolsLab** [comment]
text.txt
https://drive.google.com/open?id=1kcZ3RKCTClrV-a3fVH0EaR_tg9l7uiTO

**Comment by CryZe** [comment]
[livesplit_core.zip](https://github.com/LiveSplit/LiveSplit/files/1916785/livesplit_core.zip)

Can you replace the livesplit_core.dll in the x64 folder by this one and do the last step again to generate a text file that you can send me? It seems like the path is not valid UTF-8 for some reason. Thanks for the help btw :)

**Comment by FoolsLab** [comment]
https://drive.google.com/open?id=1mqPzW0MT1Xtmq0-NnI9jT-7RDkn88baA

**Comment by FoolsLab** [comment]
I built livesplit_core.dll on my PC, then the symbol names were normally shown.
https://drive.google.com/open?id=18kY-OWI7wOXeSWflGHwxE0Z6RZP1kZnO
