### ISSUE TITLE
Current Pace component only using current comparison

### ISSUE THREAD

**Issue by HydraSR** [LiveSplit/LiveSplit#1057]
After updating to Livesplit 1.7.6 the Current Comparison component no longer compares based on what I have selected in the Layout Settings, and instead is based off my current active comparison.

**Comment by wooferzfg** [comment]
Which version did you update from? I don't think that 1.7.6 had any changes that affected the Current Pace component. Also, could you send me your layout & split file or give a way to reproduce this issue?

**Comment by Hydro202** [comment]
I believe I updated from 1.7.5, but could've been 1.7.4; It seems to have fixed itself after I changed the active comparisons, or maybe it was just simply a reboot of my computer, but changing them back does not recreate this issue, for reference I had all but Best Split Times unchecked. I'm more than willing to try and help figure this out though.

**Comment by wooferzfg** [comment]
What was the incorrect behavior like?

**Comment by Hydro202** [comment]
Sorry, not quite sure what you mean by that, could you elaborate?

**Comment by wooferzfg** [comment]
What did it do when you switched comparisons in the Layout Settings? Did the name always just say "Current Pace" rather than switching to "Best Possible Time" or "Predicted Time" like it should, or did the time just not update?

**Comment by Hydro202** [comment]
I don't remember exactly, but I don't believe it changed at all.

**Comment by just-ero** [comment]
The issue appears to have been resolved.

There is no clear cause for the issue. There are also no steps to reproduce it.
