### ISSUE TITLE
Livesplit using high CPU when the timer is running only

### ISSUE THREAD

**Issue by clouds617** [LiveSplit/LiveSplit#1059]
Livesplit when idling uses no CPU but when the timer is active it rockets up to 20%-25%. I get errors but I have no idea what specified device its talking about as I only have my GV USB2, logitech c920 webcam and blue yeti microphone all plugged in with a usb hub. 

I am using a mircosoft surface pro 4.

https://imgur.com/a/vLyynUc

**Comment by clouds617** [comment]
Also im using 1.7.6 windows 10

**Comment by wooferzfg** [comment]
The CPU usage might be high just because it draws so much. Some easy ways to reduce that are to make sure you aren't using a background image, to turn gradients off, and to reduce the number of decimals on the timer (so that it redraws less often).

**Comment by clouds617** [comment]
After restarted my computer the cpu use when down a ton but still was going up to 10% and turning off horizontal gradient with delta time for detailed timer seemed to keep it under 4% all the time, thanks for the help!
