### ISSUE TITLE
Load Remover bug

### ISSUE THREAD

**Issue by jpeezymyneezy** [LiveSplit/LiveSplit#1065]
The first day I used LiveSplit and added a load remover for Crash Bandicoot NST it was working just fine. Then later that day it wasn't in my layout settings and I kept getting notifications that i need to update for the load remover. Every time i hit yes it would update, reboot and the same thing would happen. No load remover, and another update notification. I deleted LiveSplit off my PC and re-downloaded it and nothing has changed

**Comment by jpeezymyneezy** [comment]
https://www.speedrun.com/crashnst/resources

and thats definitely possible, however it was working before so thats the main thing thats confusing me

**Comment by wooferzfg** [comment]
You might want to try to contact the person who made this directly.
