### ISSUE TITLE
Video component freezes the UI

### ISSUE THREAD

**Issue by OoDeeR** [LiveSplit/LiveSplit#1071]
Hi, I have encountered the following issue:
For layouts containing a video component, the UI does not update anymore. That includes the timer itself, split names, splits, the title and the video component. It does not include the delta and split icons in the detailed timer for some reason.
Example: I open the program and see the splits I have used before closing the program. If I try to change to other splits, nothing happens, visually. If I close and open the program, I now see the splits I had selected and was not able to see before restarting the program.
The program seems to be running just fine in "the background". split comparisons will show up, although not making sense since they can be from a different game and visually compare to a different one.
I am using v1.7.6. A fresh installation exhibits the exact same behaviour. The issue persisted with any video I have tested.
The only bigger system change prior to this issue emerging was me installing Vegas Pro Edit 14.
Event log: http://s000.tinyupload.com/index.php?file_id=44354944263334691735

**Comment by wooferzfg** [comment]
which version of VLC do you have?

**Comment by OoDeeR** [comment]
3.0.2-win64 which should be the latest stable release

**Comment by wooferzfg** [comment]
The video component currently requires using VLC 2.2.1. We will probably change this in the future, but for now this is the case.

**Comment by wooferzfg** [comment]
https://github.com/LiveSplit/LiveSplit/issues/1074
