### ISSUE TITLE
LiveSplit will not run on my PC

### ISSUE THREAD

**Issue by Jksonic15** [LiveSplit/LiveSplit#1072]
I had LiveSplit version 1.7.4 and was using it fine, until recently it stopped working on my pc. I've read some online help for this issue and i doesn't seem to work. I got version 1.7.6 and so far I can't get it to work. I hope someone gets to read this soon.

**Comment by hallcristobal** [comment]
Does it not boot, not work correctly, etc..? What exactly is the issue at hand?

**Comment by Jksonic15** [comment]
It won't really boot up. If im lucky, sometimes I can get it booted up through the files where it says application. Other than that, it never boots up.

**Comment by jakanz** [comment]
One question; did you take LiveSplit.exe out of the folder?

**Comment by Zypher1102** [comment]
The same thing is happening to me and how to you take Livesplit.exe out.
