### ISSUE TITLE
Total Playtime Oddity?

### ISSUE THREAD

**Issue by Sapphron** [LiveSplit/LiveSplit#1077]
I recently implemented the Total Playtime tab into my splits. However, whenever I start, the number starts counting down. It started at like 47 minutes and went down. After I waited for the timer to go all the way down, it went up to 58 minutes. Am I doing something wrong?
(sidenote: I ran the category for >8 hours before I added it)
Top image is before, bottom image is 7-8 seconds after.
![first](https://user-images.githubusercontent.com/24858043/39678713-0aea226a-5157-11e8-876a-664bee592b89.png)
![second](https://user-images.githubusercontent.com/24858043/39678714-0b0a6cdc-5157-11e8-9ba1-e3a055a2ca4f.png)

**Comment by wooferzfg** [comment]
Could you send me your splits?

**Comment by CryZe** [comment]
I'm pretty sure it's the 01/01/0001 bug.

**Comment by wooferzfg** [comment]
For reference: https://twitter.com/wooferzfg/status/992516485292658695

**Comment by Sapphron** [comment]
Where do I find the attempt history?

**Comment by Sapphron** [comment]
[SMR Axeil Edition - Crocomire%.zip](https://github.com/LiveSplit/LiveSplit/files/1993029/SMR.Axeil.Edition.-.Crocomire.zip)

**Comment by Sapphron** [comment]
It's not the "01/01/0001" bug.

**Comment by CryZe** [comment]
It's definitely a bug with a corrupted date time in your attempt history: ![https://i.imgur.com/ngfgdT8.gif](https://i.imgur.com/ngfgdT8.gif)

**Comment by hallcristobal** [comment]
it is the `01/01/0001` bug, attempt 42.

**Comment by Sapphron** [comment]
woah what

**Comment by Sapphron** [comment]
wait
i guess i didn't check enough

**Comment by Sapphron** [comment]
it's fixed! thank you guys

**Comment by CryZe** [comment]
Reopening since this seems to be a general bug that we should handle.

**Comment by Sapphron** [comment]
okay, sorry

**Comment by wooferzfg** [comment]
We still need to remove these broken times from the Attempt History when loading splits (similarly to how we removed negative best segment times).

@Sapphron Did you ever save an attempt midrun and choose to save it as a Personal Best?

**Comment by Sapphron** [comment]
I did save attempts midrun. I haven't completed an any% run because I haven't routed it so I just skipped the rest of the times and deleted the ones that were skipped over.

**Comment by nathandalton** [comment]
can someone see what the problem are if i send my splits?

**Comment by nathandalton** [comment]
what attempt was the bug?

**Comment by nathandalton** [comment]
my splits have the same problem. they keep counting down from 1 hour. i don't know what to do or what attempt it is. i don't know how to get into my attempt history so i could find the bugged attempt. 

[asm 2.zip](https://github.com/LiveSplit/LiveSplit/files/3074869/asm.2.zip)
