### ISSUE TITLE
Autosplitter Super Metroid does not split on non-default splits.

### ISSUE THREAD

**Issue by Nighty93** [LiveSplit/LiveSplit#1082]
As the title implies, the autosplit does not work properly for Super Metroid. It does start the timer however and also reset it once the soft reset is hit (higan), but it does not split on anything but the default predefined splits. None of the custom checkboxes work. It seems that livesplit is not saving it to the .asl file

I hope that this can be fixed soon. Best regards

**Comment by UNHchabo** [comment]
I wrote the autosplitter for SM; Nighty told me he figured out that he was clicking the checkboxes for the individual grouped settings, but the parent was still unchecked.

From the Auto Splitters documentation: "The user can still freely toggle settings that have their parent unchecked, however they will be grayed out to indicate they are disabled."

Could I request that the checkboxes be disabled entirely? That way it's clear to the user that those settings are turned off. That behavior is fairly standard for checkboxes and radio buttons in GUIs.

**Comment by just-ero** [comment]
The issue appears to have been resolved.
