### ISSUE TITLE
Splits.io Explorer is broken?!

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#109]
Not sure what's wrong, but it needs to be fixed :cry:

**Comment by wooferzfg1** [comment]
https://github.com/LiveSplit/LiveSplit/commit/54a892163c991f5fcf7a54ea0c48808d0853ff3b

**Comment by wooferzfg1** [comment]
actually Glacials fixed it on his end so the fix is no longer needed
