### ISSUE TITLE
Best partial times

### ISSUE THREAD

**Issue by lagoPS** [LiveSplit/LiveSplit#1107]
Just a suggestion for a possible cool feature.

I was thinking that it'd be cool to have, along with each level's best time, the "best time until this point" information at each split.
That'd make it possible to see how you're doing comparing to all your previous single segment runs.
(I'm assuming it's not already possible ATM)

**Comment by just-ero** [comment]
The issue appears to have been resolved.

The comparison "Best Split Times" exists now.
