### ISSUE TITLE
Always on Top doesn't work

### ISSUE THREAD

**Issue by FireCulex** [LiveSplit/LiveSplit#1132]
In the layout editor Always on Top is checkmarked however the splits disappear whenever I alt-tab to a different window.

1.7.6

**Comment by res0nance** [comment]
I can't replicate this, this does happen only if you leave the layout editor open and previously unchecked `Always on Top`

**Comment by DRY411S** [comment]
I am seeing this with factorio. If I run it fullscreen mode, then LiveSplit does not stay on top. Run factorio windowed mode, Livesplit stays on top.

I believe that factorio 'full screen' mode is actually windowed borderless, but I cannot be sure.

**Comment by wooferzfg** [comment]
Always on Top won't work when there's a full screen window open.

**Comment by YoXpertguyZ** [comment]
I have the same problem same issue but with Minecraft I use borderless Minecraft and livesplit goes under it for some reason and stay on top is checked

**Comment by just-ero** [comment]
Closing as unrelated.

No application can be displayed on top of a full screen game. This is not an issue with LiveSplit.
