### ISSUE TITLE
splits dont open

### ISSUE THREAD

**Issue by linkmaster647** [LiveSplit/LiveSplit#1133]
i premade splits for all games i want to run, also made 2 runs already but..... now i cant open ANY splits...... it says that the splits file isnt recognized as splits....

**Comment by hallcristobal** [comment]
Would you mind uploading the .lss file?

**Comment by linkmaster647** [comment]
everything is in there https://www.dropbox.com/sh/b2hfgiopah70sx3/AADq5C6jCdBaW9bXI3bOuGmFa?dl=0

**Comment by hallcristobal** [comment]
And you've tried opening the splits with the latest release?

**Comment by just-ero** [comment]
The issue appears to have been resolved.
