### ISSUE TITLE
LiveSplit frequently fails to open, or takes a very long time.

### ISSUE THREAD

**Issue by Yumi08** [LiveSplit/LiveSplit#1138]
LiveSplit very often ends up so that it doesn't open a window, but still opens a process in the task manager. The only fix that I've found so far is restarting my computer, or waiting around 3 minutes. I run Windows 10 x64.

**Comment by Sapphron** [comment]
I have the same problem.

**Comment by jakanz** [comment]
Try this issue: https://github.com/LiveSplit/LiveSplit/issues/1192.

**Comment by wooferzfg** [comment]
This is likely resolved by https://github.com/LiveSplit/LiveSplit/commit/97a1d8ed25e46b65c95b48d7f5960e6905564da1
