### ISSUE TITLE
Splits frequently fail to save

### ISSUE THREAD

**Issue by jhobz** [LiveSplit/LiveSplit#1143]
For the last few weeks, LiveSplit has had a weird quirk where it fails to save my splits. If I use "Save Splits as..." and name it a different file, it works fine. And other times, it'll save over the current file just fine. But often I'm met with an "Splits could not be saved!" error.
![image](https://user-images.githubusercontent.com/1765799/43625919-88526d6a-96bd-11e8-8118-48cd5b6d65c3.png)

I've checked my disk space and folder permissions and all are fine, so I'm not sure what could be causing this.

**Comment by CryZe** [comment]
Can you send your event logs?

Go to your Control Panel -> Search for Event Viewer -> Open it -> Windows Logs -> Application -> Select the last few LiveSplit errors (those that were at the time when the error happened) -> Save Selected Events -> Save them as the default format -> Send it to me (Upload it somewhere).

**Comment by jhobz** [comment]
Here you go: https://drive.google.com/file/d/18qZhw_-W6mU0w1m6CjZcR5TBcjw4IIVT/view?usp=sharing

I included all errors from that evening, but the failure to save ones should be pretty obvious. It seems some other application is accessing the file at the same time, but I have no idea what it could be... The closest thing would be my Google Drive Backup & Sync program, but that should only be trying to access it *after* a save, not before. Plus, sometimes it works fine.

**Comment by just-ero** [comment]
Does this issue persist in the most recent stable version of LiveSplit?

The issue may have been caused due to a handle to the splits file not being closed after reading it in.

**Comment by jhobz** [comment]
I don't believe I've had this issue in years. I didn't even remember opening it when I got your reply.
