### ISSUE TITLE
Autosplitter throws error on Pointer Path negative offset.

### ISSUE THREAD

**Issue by Ynscription** [LiveSplit/LiveSplit#1151]
In an autosplitter script, in the state block, writing a Pointer Path with a negative offset throws the error:

`Syntax error, expected: number`

Original code:
```c#
state("POP"){
//The prince's currHealth
	int currHealth : 0x006DB8F4, -0xB88;
}
```

Also tried with:
`- 0xB88`
`(- 0xB88)`
`(-0xB88)`

**Comment by TransparentBlue** [comment]
Still an issue
```
state("FBF"")
{
	float TotalResourcesCount : "FBF.exe", 0x0023D3E4, 0x20, -0x2D0;
}
```
Causes 
```
ASL parse error(s):
at Line 3, Col 66: Number cannot be followed by a letter.
```

Replacing `-0x2D0` by `- 0x2D0` causes
```
ASL parse error(s):
at Line 3, Col 66: Syntax error, expected: number
```
instead.

**Comment by Kojoley** [comment]
The parser does not accept negative hexencoded values, as a workaround use decimals (instead of `-0xB88` use `-2952`, and instead of `-0x2D0` use `-720`).

**Comment by just-ero** [comment]
The issue appears to have been resolved.
