### ISSUE TITLE
Livesplit missing Splits

### ISSUE THREAD

**Issue by joshuapbull** [LiveSplit/LiveSplit#1162]
Hello. Livesplit was working for a while on getting over it. Then once the game updated the autosplitter wasn't working at all. I fixed it but now the autosplitter will miss random splits. What is going on?

**Comment by res0nance** [comment]
It sounds like its a problem with the autosplitter you can try to reach the autosplitter author here https://github.com/Tairoon92/LiveSplit.ASLScripts

**Comment by just-ero** [comment]
Closing as invalid.

Please report issues with autosplitters in their respective repositories or communities.
