### ISSUE TITLE
Global Hotkeys disable on their own.

### ISSUE THREAD

**Issue by stllr** [LiveSplit/LiveSplit#1177]
Windows 7, beefy PC, while using multiple different keys and even my xbox 360 controller as split keys. The "Global Hotkeys" checkbox keeps unchecking itself, sometimes multiple times in the span of a few minutes. I've tried disabling the keys for other programs, and disabling double tap prevention. Don't know what causes this.

**Comment by wooferzfg** [comment]
Do you have a hotkey set for "Toggle Global Hotkeys"?

**Comment by stllr** [comment]
If I did have such a hotkey, I have no idea how to find/change it. I poked
around in the settings a bit and also googled but couldn't find anything
about hotkeys or where to set them.

**Comment by stllr** [comment]
It was there the whole time, yet somehow I still couldn't find it. Sorry about this and thank you for your prompt responses. It's been fixed now.
