### ISSUE TITLE
LiveSplit Does Not Open

### ISSUE THREAD

**Issue by HandCrush** [LiveSplit/LiveSplit#1192]
Recently I used LiveSplit normally for speedruns but when I tried to use the program today it did not open. It gets as in process in the task manager but when trying to open nothing happens. already tried to download again, if you can help me thank you.

**Comment by floatas** [comment]
Try to run application once more and if it fails, you could look at logs for errors:
1. Press Windows key + R
2. Type: eventvwr
3. Press enter
4. Event viewer will open, navigate to "Windows Logs" > "Applications"
5. Find all errors where "Source" column says "LiveSplit" and post them here.

**Comment by VTnotfoundDX0912** [comment]
Live split is starting extremely slow and idk how to solve this... 


GENERAL PAGE:

HREAULT: (0X8007001E), MODULE (SHARPDX.DIRECTINPUT,APICODE: DIERR_INPUTLOST), MESSAGE: SYSTEM CANNOT READ FROM THE SPECIFIED DEVICE.

AT SHARPDX.RESULT.CHECKERROR()
ATSHARPDX.DIRECTINPUT.DEVICE.GETDEVICEDATA(INT32 ARG0, INTEL& ARG2, INTEL32 ARG 3) AT SHARPDX.DIRECTINPUT.COSTUMDEVICE`3.GETBUFFEREDDATA()
AT LIVESPLIT.MODEL.INPUT.GAMEPADHOOK.POL()
