### ISSUE TITLE
Sum of Best is partly using Real Time for the Game Time SoB Calculation 

### ISSUE THREAD

**Issue by reijerzzz** [LiveSplit/LiveSplit#123]

**Comment by wooferzfg1** [comment]
i can't reproduce this. could you elaborate on this issue?

**Comment by reijerzzz** [comment]
I made a quick video showing the bug: http://youtu.be/ee8kYoR1xeA

(sorry for the late response)

**Comment by CryZe** [comment]
To me this looks like you simply didn't improve your sum of best.

**Comment by CryZe** [comment]
Ok, nvm, it's completely broken for Game Time and no one ever noticed. We'll fix it.
