### ISSUE TITLE
Sharing to splits.io at end of run doesn't include current run in history

### ISSUE THREAD

**Issue by beninswe** [LiveSplit/LiveSplit#1269]
So after a PB, I share to splits.io, and then can post the link on discord and it includes a screenshot of the splits.
e.g. https://splits.io/3mrz
includes the screenshot: https://i.imgur.com/Bb85qB9.png which shows the splits, however, in the segments in splits.io it doesn't include the splits from that time... e.g. if you expand Mushroom Hill 1, it shows the last one from Attempt 253.  (**note**: I right clicked on LS and did Save Splits before Sharing to splits.io).

If I end the run, LS asks if I want to update my splits, so I say yes.  And then after that if I share to splits.io it then includes the run in the history:
https://splits.io/3muo (check MH1 again, and it has attempt 282 in the graph)
However, the screenshot attached to it isn't as useful as it's from before a new run: https://i.imgur.com/swmraa4.png

**Comment by wooferzfg** [comment]
This seems to be resolved now.
