### ISSUE TITLE
LiveSplit doesn't remember last used Timing Method

### ISSUE THREAD

**Issue by stllr** [LiveSplit/LiveSplit#1284]
I set livesplit to compare against Game Time on my splits, and save after using em everytime. But for some reason, it resets back to using Real Time when I reopen the program the next day. I've gotten around this by putting my Timing Method Columns to "Game Time" instead of "Current Timing Method" to get around this, but I can't do that for my Sum of Best and Best Possible Time. Since I don't like using work-arounds and I can't even fully use them, is there a way I can get livesplit to remember my last used Timing Method? is it a bug with my splits file? I've linked it below. 
[sa2 broken splits t.zip](https://github.com/LiveSplit/LiveSplit/files/2872394/sa2.broken.splits.t.zip)

**Comment by wooferzfg** [comment]
Could you send your settings.cfg file?

**Comment by stllr** [comment]
[here it is](https://github.com/LiveSplit/LiveSplit/files/2874015/settings.cfg.t.zip)

**Comment by wooferzfg** [comment]
Your most recent splits file has "Game Time" associated with it, so it should be opening with Game Time. The only issue I could think of is if you're opening splits files by double clicking on them? The timing method wouldn't be remembered in that case.

**Comment by stllr** [comment]
Ah, didn't know that affected it. Thanks! This is solved.
