### ISSUE TITLE
total playtime keeps going down from 1 hour

### ISSUE THREAD

**Issue by nathandalton** [LiveSplit/LiveSplit#1329]
i added the total playtime for 1 of the categories i speedrun. after a while it made it so that it counts down and it continues from the last run. i didn't change anything but going into the settings and turning off total hours doesn't help and when i turn it back on it doesn't help? i don't have this for any of my other  categories i have. i don't know what else to do?

**Comment by wooferzfg** [comment]
Duplicate of https://github.com/LiveSplit/LiveSplit/issues/1077
