### ISSUE TITLE
-0.00 instead of +0.00

### ISSUE THREAD

**Issue by negative-seven** [LiveSplit/LiveSplit#1360]
A simple suggestion: whenever the time delta is exactly 0 (which in the case of some games with autosplitters can happen very often), mark it as being ahead (-0.00) instead of behind (+0.00), because we all need some optimism in our lives.

**Comment by LukeSaward1** [comment]
You don't realize that LiveSplit can count in X.XXX (e.g. 0.000), so -0.00 could be -0.001 and +0.00 could be +0.005, for example.

**Comment by Thermospore** [comment]
> [Quote: @LukeSaward1] - You don't realize that LiveSplit can count in X.XXX (e.g. 0.000), so -0.00 could be -0.001 and +0.00 could be +0.005, for example.

-7 realizes this. I don't think you fully read the issue; this part specifically: 

> whenever the time delta is exactly 0 (which in the case of some games with autosplitters can happen very often)
