### ISSUE TITLE
enhancement: Web page component

### ISSUE THREAD

**Issue by schwjm** [LiveSplit/LiveSplit#1387]
Similar to other components showing arbitrary data (e.g. Text), and comparable to those showing dynamic data (e.g. Video), it would be useful to be able to load a web page.

Other details/ideas:
* Use CefSharp or any similarly capable library
* Feed JavaScript events to the web page on LiveSplit events (start/reset/pause/split)
* Allow additional hotkeys to be bound and set via LiveSplit which also generate events

The main inspiration/use-case is to integrate an item tracker built in HTML/JS (keyboard control mapping is limited and global hotkeys aren't really a thing). Therefore I wouldn't worry so much about making the web page directly interactable as long as keyboard controls pushed events through.

The potential of this kind of component is large as it enables a new way to develop components, especially if LiveSplit exposes an object to feed data back the other way (I have no particular use for this channel at this time though).

I attempted this briefly using CefSharp.WinForms but the prototype would not actually render anything in spite of CefSharp apparently otherwise working according to its log, and my inexperience with WinForms leaves me with few ideas on how to proceed--the Video component apparently does some weird things to be made to work in the generic component system but in the end it doesn't seem like I'm doing much differently than the CefSharp tutorial. CefSharp.OffScreen may be an option but I suspect it may be less performant (which would be acceptable for pages that don't need to render very often).

**Comment by just-ero** [comment]
@wooferzfg Would such a component ever be part of LiveSplit's default components? I believe the idea is to render a web page right on the LiveSplit application?

**Comment by wooferzfg** [comment]
Probably would be a downloadable component if anything
