### ISSUE TITLE
Saved splits differ from numbers while running

### ISSUE THREAD

**Issue by zoliking** [LiveSplit/LiveSplit#1396]
Hello,

I'm not sure if this is a bug, an issue with my specific setup (I have a shitty old SSD that stalls sometimes, messing with everything running on the machine) or I'm misunderstanding a feature, but here's the issue:

After completing a run, when I save my splits, the numbers that load in aren't the ones that were displayed during the gameplay. I ascertained with video recording that the split times after the save are incorrect and the live ones are the right ones.

Example (real data):
Let's call my first split S1, my middle one S2 and my final time S3. (I have 22 splits overall, but this will suffice to demonstrate the problem)

Previous save (also impacted by the issue):
S1: 4:51
S2: 1:00:55
S3: 2:02:21

Splits for current run during gameplay:
S1: 3:53
S2: 57:33
S3: 1:55:10

Splits saved now:
S1: 4:34
S2: 59:55
S3: 2:00:11

It's not the kind of promlem that would make me rip off the wallpaper from my walls in rage, but it's weird and kinda annoying, any help in figuring it out would be appreciated. For now I'll just be manually adjusting the numbers, but I'd rather not resort to that on the long run, not to mention that I don't capture video every time I play, so it's not always an option.

Thank you in advance for the assistance,
zoliking

**Comment by CryZe** [comment]
Can you send the recording of this happening? Also can you share the splits file too?

**Comment by zoliking** [comment]
Unfortunately the bit where this all happened was not captured. But I'll send a screenshot of what LiveSplit looked like at the end of the video and the splits file.

https://www.filedropper.com/oriandtheblindforestdefinitiveedition

![lswindow](https://user-images.githubusercontent.com/24624895/59114561-b1316b00-8947-11e9-85e8-a9373a778e70.png)

![vlcsnap-2019-06-07-17h08m27s45](https://user-images.githubusercontent.com/24624895/59114149-d7a2d680-8946-11e9-80b8-d0bea48a751a.png)

**Comment by CryZe** [comment]
It seems like you are comparing against "Average Segments" instead of "Personal Best".

**Comment by zoliking** [comment]
I see, thank you!
