### ISSUE TITLE
Predicted Time doesn't predict time properly?

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#140]
It looks like Predicted Time doesn't work during a run where a time for a split is missing? I'm not fully sure why that happened though, so this has to be tested properly. It was Predicted Time (Average) and I deleted the times of one split before. It could also be an issue with Average Segments.

**Comment by wooferzfg** [comment]
This is specific to the Average Segments comparison - it relies on the segment history for every segment being present. When deleting times for a segment, the history for that segment is cleared, which breaks the average calculation for that segment until a run gets to that segment again.
