### ISSUE TITLE
Combine segment times together when deleting a segment

### ISSUE THREAD

**Issue by chillex0** [LiveSplit/LiveSplit#1418]
When I export splits to MS Excel after deleting a segment, the sum of each segment for each attempt do not add up to the final total time.

In the current non-developer LiveSplit build:
Example: For a given attempt, segment 1 took 3 s; segment 2 took 5 s. Sum of segments matches up with the total time.
I remove segment 1, so now there's segment 2 left. Segment 2 remains 5 s, which implies that the run took 5 seconds to complete. Segment 2 should be 8 s for that attempt to account for the deleted segment 1.

**Comment by wooferzfg** [comment]
LiveSplit already does this, except it uses your best time from the segment history from the start of the run until the second segment for the new best segment time (which might be lower than the sum of the best segments).

**Comment by chillex0** [comment]
I tested this, and you're right. I must've mis-remembered my first time doing this.
