### ISSUE TITLE
PB Times Change during run

### ISSUE THREAD

**Issue by csilva235** [LiveSplit/LiveSplit#1424]
I'm having an issue with the way LiveSplit tracks against PB. 

Scenario. 
![image](https://user-images.githubusercontent.com/9128386/61192993-ea16db00-a67d-11e9-95fd-00bb52f82a3f.png)

When running against those times, if I get anything less than the times of the right, those times update to reflect the change. 

![unknown](https://user-images.githubusercontent.com/9128386/61193021-3eba5600-a67e-11e9-8166-3f746471a2bc.png)

I'm trying to make it so that when I get a time lower than my PB, the time stays and shows the delta and then when the run is complete, it updates to the new PB times. 

I've seen streamers do it, but I don't think I've ever noticed if their PB time changes when they gold or save time on a split. 

Is this possible?

**Comment by wooferzfg** [comment]
The times on the right get replaced with the time you get during the current run, regardless of whether it's faster or slower than the PB time.

**Comment by csilva235** [comment]
Is this the intended functionality? I just may have not noticed it when streamers are doing runs, but it seems like the PB time always stays the same and the only thing that changes is the delta of the current run.

**Comment by csilva235** [comment]
Closing stale task.
