### ISSUE TITLE
Update the Video Component to the new VLC version

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#145]

**Comment by wooferzfg1** [comment]
Is this already done? I don't remember our progress on this

**Comment by wooferzfg1** [comment]
Seems like referencing the dll's makes it work with any version of VLC? Maybe it's just me though.

**Comment by wooferzfg1** [comment]
Looks like we need to:
[ ] Update the DLLs to support VLC 2.2.1 rather than 2.1.5
[ ] Catch the error if the VLC version doesn't match (what we already did here https://github.com/LiveSplit/LiveSplit.Video/commit/34918728d0036ddb406636db77b2e35de6d86ea9 should work)
