### ISSUE TITLE
Add Call of Duty 4 : Modern Warfare auto splitter

### ISSUE THREAD

**Issue by KunoDemetries** [LiveSplit/LiveSplit#1453]
https://raw.githubusercontent.com/KunoDemetries/cod4/master/mw.asl

I wasn't sure how to add it so I made it into a repositories file. 

it has start, split, reset, and remove loads.

**Comment by wooferzfg** [comment]
https://github.com/LiveSplit/LiveSplit/blob/master/Documentation/Auto-Splitters.md#adding-an-auto-splitter
