### ISSUE TITLE
Livesplit giving wrong time for Sum of Best

### ISSUE THREAD

**Issue by death7unites7us** [LiveSplit/LiveSplit#1475]
Hello! I just wanted to report a bug I have experienced so that hopefully we can find a way to keep it from happening in the future.

Basically, livesplit has a time of 3:57, but it is adding 1:02 in my sum of best column. If I edit the 3:57 to anything other than 1:02, the final sum of best stays the same. If I go under 1:02, it will change to whatever I typed in. I see no problems in the actual splits file, so I'm pretty lost.

![help](https://user-images.githubusercontent.com/54593168/63789473-70e9e500-c8c5-11e9-81f5-a7bb681439c6.jpg)
[Kirby 64 The Crystal Shards - 100% OLD.txt](https://github.com/LiveSplit/LiveSplit/files/3547183/Kirby.64.The.Crystal.Shards.-.100.OLD.txt)

**Comment by UrbanCMC** [comment]
I've had a look at the difference between the two "sum of best" calculations and came up with what should answer your question:

The "simple sum of best calculation" does just what it says, display the sum of the lowest time ever recorded for all segments. Sounds fine so far.

The "complex" calculation tries to give a more accurate best case time by including attempts where some segments are missing a split time (i.e. the next segment actually displays the time for **both** of them).

In this particular case the following happens for the complex calculation:

While determining the best time for segment "-4-2", LiveSplit finds a missing time in attempt 203, so it checks for a time in "-4-3", which is also empty, before it moves on to "-4-4", which has a time of 7:22.

The assumption is now that this is the total time for those 3 segments in that attempt. This means the best time until "-4-4" is actually the time until "-4-1" (34:32), plus **the fastest time you ever recorded for those 3 segments** (7:22), resulting in 41:54.

Obviously, this changes the displayed information from "The fastest I ever finished -4-4 is 1:02" to "the fastest I could've ever completed **everything including -4-4** is 41:52".

**Comment by death7unites7us** [comment]
That makes sense, glad you could figure it out! 👍
