### ISSUE TITLE
Code duplicates

### ISSUE THREAD

**Issue by namax** [LiveSplit/LiveSplit#1484]
Hi, 

I was not sure if you accept pull request for such trivial "bug" as its not actually a bug, so I decided to add as an issue. Hope you do not mind. 

I read your code and found in the https://github.com/LiveSplit/LiveSplit/blob/master/LiveSplit/LiveSplit.Core/Model/Input/KeyboardHook.cs file , that a couple lines of code can be replaced by already existing function. 

`var result = GetAsyncKeyState(keyWithoutModifiers);`
`var isPressed = ((result >> 15) & 1) == 1;`

can be replaced by the function call

`
var isPressed = IsKeyDown(keyWithoutModifiers);
`

**Comment by wooferzfg** [comment]
Could you make a PR for this?

**Comment by namax** [comment]
sure

**Comment by namax** [comment]
the pull request https://github.com/LiveSplit/LiveSplit/pull/1485
