### ISSUE TITLE
LiveSplit Erased History Automatically

### ISSUE THREAD

**Issue by LukeSaward1** [LiveSplit/LiveSplit#1491]
I woke up this morning to play some Refunct, loaded up LiveSplit and clicked on my Any% splits. 

> The selected file was not recognized as a splits file.

 It was working yesterday, and I have no idea what is going on.
Also it erased my splits & layout history without me erasing it.
So if this can't be fixed, my 4000+ attempts and 15hrs+ is wasted.

I hope this can be fixed.

**Comment by wooferzfg** [comment]
Your splits are probably corrupred. This is most likely due to https://github.com/LiveSplit/LiveSplit/issues/1143

I would recommend backing up your splits often and uploading PBs to [Splits.io](https://splits.io/).
