### ISSUE TITLE
Backport reattachment of unattached segment history elements

### ISSUE THREAD

**Issue by Sapphron** [LiveSplit/LiveSplit#1504]
Hello, this has really been bugging me over the past few months. I haven't been using LiveSplit much so it hasn't affected me greatly, but I decided it was time to ask about what the heck keeps happening.
Each time I finish a run and have the ending split, I press 1 which is my split key to save it. It shows all of the fields with Deltas saying +0.0 like this: https://drive.google.com/file/d/1hc8xQRCnNRWqd7ZwoD3BssoPAQ-ivr0i/view?usp=sharing
And if I try to save it without trying to press 1 about ten times so it finally saves for some reason, it just shows this error: https://pastebin.com/zHFyzQqw
This is really obnoxious. I tried redownloading LiveSplit to see if I had an old version or something, but that wasn't it.

**Comment by CryZe** [comment]
Can you send me those splits? They seem corrupted in some way that is completely unexpected to LiveSplit.

**Comment by Sapphron** [comment]
Yeah, I totally forgot to send them in the first place, sorry. The reason it's named "test.lss" is because I didn't want to screw up my main split file terribly, but it does the exact same thing. And this type of thing has happened on other livesplit configurations too for some reason... https://www.dropbox.com/s/ln8t7ny6cj7uudi/test.lss?dl=1

**Comment by CryZe** [comment]
How do I replicate it crashing exactly? Just saving doesn't seem to be enough.

**Comment by Sapphron** [comment]
For me, finishing the "run" and then trying to save while it has the +0.0's on screen does that error for me. In the "Save Splits" section.

**Comment by Sapphron** [comment]
[double post, sorry]
It fixed itself, somehow?? It doesn't do it anymore

**Comment by Sapphron** [comment]
https://www.dropbox.com/s/lbtgaxavm9wcvsd/Super%20Metroid%20-%20Low%25%20Ice%20-%20Copy.lss?dl=1 THIS one does it. Sorry for the confusion

**Comment by CryZe** [comment]
Oh wow, yeah I'm seeing it with this file now too.

**Comment by Sapphron** [comment]
For some reason, hitting 1 over and over fixed the "test.lss" file...

**Comment by CryZe** [comment]
Did you manually modify the XML in some way? The data in there seems inconsistent.

**Comment by Sapphron** [comment]
The only thing I know that I did was modify this line:
<Platform usesEmulator="False">
99.9% sure I didn't modify anything else.

**Comment by wooferzfg** [comment]
Here's a fixed version of your splits file: https://www.dropbox.com/s/6hibrjfh22hrzan/SM_Low_Ice_Fixed.lss?dl=0

**Comment by Sapphron** [comment]
https://www.dropbox.com/s/mvojaqic03txps1/Super%20Metroid%20Ancient%20Chozo%20-%20Any%25BROKEN.lss?dl=1
https://www.dropbox.com/s/v5zmorygb4kc8kq/Super%20Metroid%20Hermit%20Kingdom%20-%20Any%25BROKEN.lss?dl=1
These two are also broken. Out of my 52 split files, only 3 are corrupt, I'm guessing one was corrupt and I used that one unknowingly and the other ones broke.
Also, how did you fix it? Thank you so much!

**Comment by CryZe** [comment]
Here's the changes that need to be backported for this to the original LiveSplit.

**Comment by TheTedder** [comment]
I'm gonna tackle this one.
