### ISSUE TITLE
Twitter auth is broken

### ISSUE THREAD

**Issue by wooferzfg** [LiveSplit/LiveSplit#1535]
https://twitter.com/legrandrunner/status/1189658193527525376?s=19

**Comment by joro550** [comment]
I did a bit of research on this and have a couple of questions, it seems when you try and "share" your time via twitter and are debugging livesplit it throws an exception that an underlying connection has been closed. Looking at the code 

```

            auth = new WebAuthorizer
            {
                // Get the ConsumerKey and ConsumerSecret for your app and load them here.
                Credentials = new InMemoryCredentials
                {
                    ConsumerKey = Twitter.ConsumerKey,
                    ConsumerSecret = Twitter.ConsumerSecret
                },
                Callback = new Uri("http://livesplit.org/twitter/"),
                // Note: GetPin isn't used here because we've broken the authorization
                // process into two parts: begin and complete
                PerformRedirect = pageLink =>
                    OAuthWebBrowser.Navigate(new Uri(pageLink, UriKind.Absolute))
            };

            auth.BeginAuthorization(new Uri("http://livesplit.org/twitter/")); // throws here
```

It sort of looks like it's throwing the exception when trying to go to live split twitter page, navigating to that URL does give me a 404, but I'm not 100% whether this ever existed.

Looking into the package a little it looks like live split is using version 4.0, the project still exists on GitHub: https://github.com/JoeMayo/LinqToTwitter but its last commit was in 2018 and is on version 5.0 (according to nuget) but does not support .Net 4.5 (the version of LiveSplit.Core) but does support 4.6.1. That aside for one second, looking through the demo's for version 4 of this library it looks like the `WebAuthorizer` was filed under "old" which makes it sound like this is a very outdated version of the OAuth in this library. The "new" includes an example with a `PinAuthorizer` with a slightly different set of methods.

**Comment by wooferzfg** [comment]
I think this is fixed now that we're on .NET 4.6.1.
