### ISSUE TITLE
'Windows cannot access the specified device path or file'

### ISSUE THREAD

**Issue by Derpspace** [LiveSplit/LiveSplit#1568]
Every time this message comes up when i try to boot up livesplit when i updated to 1.7.7 plz help fix 
![image](https://user-images.githubusercontent.com/59072461/71221164-27b50b00-2291-11ea-9567-35a162217fa9.png)

Edit: I did try run as administrator and it comes up with the same thing

**Comment by wooferzfg** [comment]
Can you make sure that you have .NET 4.6.1 installed? (https://www.microsoft.com/en-us/download/details.aspx?id=49981)

**Comment by Derpspace** [comment]
Yeah I do I tried to install it and this message came up
![image](https://user-images.githubusercontent.com/59072461/71293807-2c82c900-233c-11ea-903e-a8994785aa1d.png)

**Comment by Derpspace** [comment]
![image](https://user-images.githubusercontent.com/59072461/71297735-4c20ee00-234a-11ea-8678-094c6799ffbb.png)
this might be why I reinstalled 1.7.6 and updated and this happend now its the same situation as before so Im gonna stay on 1.7.6 until this is fixed

**Comment by Derpspace** [comment]
just incase there are any fixes tell me down here

**Comment by ERColaizzi** [comment]
I am experiencing the same issue. My current situation is that I am able to run the application for any specific build once and only once before I get the same permission error. To clarify after closing I get the permission when trying to reopen the application. I am able to download a prior release and get a single use out of that build before getting the permission error. I am prompted to upgrade, but get the same access denied error as above.

**Comment by mulch-est** [comment]
I was able to fix this error by executing `dir -Path C:\Users\username\Downloads\LiveSplit_1.8.15 -Recurse | Unblock-File` in powershell, and disabling my antivirus.
