### ISSUE TITLE
LS stopped working after updating to version 1.7.7.

### ISSUE THREAD

**Issue by SentinelProxima** [LiveSplit/LiveSplit#1583]
When I try to open LiveSplit, I get an error message telling me I need to install something called ".NET Framework". I have gone to the website and tried to install it but it refuses to install, giving me a gibberish error message that tells me nothing about what the problem actually is. Anything I can do?

**Comment by wooferzfg** [comment]
You need at least .NET 4.6.1 in order to run LiveSplit. You can find the newest version here: https://www.microsoft.com/en-us/download/details.aspx?id=55170
