### ISSUE TITLE
Scrolling doesn't work

### ISSUE THREAD

**Issue by Durferity** [LiveSplit/LiveSplit#1588]
Hi guys :)

Hope you guys can helpe me out on this one. 

I'm running on PC with Livesplit (started using it a week ago) and it seems like i can't scroll trough my splits at all. I can bind my mouse wheel to commands though (for example on "Reset") - so it actually detects it. 

I guess I'm missing out on something to enable it but I can't seem to find the issue.

Thanks in advance for your help!

**Comment by NoTeefy** [comment]
Are you using splits or subsplits?

**Comment by Durferity** [comment]
Oh.. wow. that was actually the issue. Problem solved.
Thought I have to use Splits not subsplits. Thank you so much for your fast reply!

**Comment by NoTeefy** [comment]
Uhm.. it should work with both but the subsplits behave a little bit different. Are you on the latest LiveSplit version? It works with both for me (normal splits and subsplits) on Windows 10

**Comment by Durferity** [comment]
I just edited the layout (switched splits - subsplits). Now i reversed it again.. and it works even with splits now!? what is this sorcery lol. However, the problem is solved thank you so much for helping me out.

**Comment by NoTeefy** [comment]
I call it magic 😉
