### ISSUE TITLE
Where is the window redraw rate setting?

### ISSUE THREAD

**Issue by UserNaem** [LiveSplit/LiveSplit#1616]
I looked at the commit history and apparently there should be a setting that lets you override the default UI redraw rate of 40 Hz. And supposedly it's hidden. You did a very good job of hiding it, I can't for the life of me find the setting to change it, even compiling was easier.

**Comment by wooferzfg** [comment]
Don't know what you're talking about with the commit history. There's a PR for it (https://github.com/LiveSplit/LiveSplit/pull/1195) that never got merged.
