### ISSUE TITLE
Livesplit not saving my new personal best

### ISSUE THREAD

**Issue by keld0rn** [LiveSplit/LiveSplit#1646]
I'm doing some path of exile speedrunning and for some reason livesplit refuses to save my personal best. The way I have my livesplit setup is that it automatically splits upon me entering specific areas and at the end for the final split I do it manually as it's a boss kill and livesplit can't do it automatically. So at the end of the run, I do the final split, it's better than my personal best (shown as blue) and then I attempt to save it - I've done it mutiple ways, neither worked:
- I tried to reset, then close livesplit but not before clicking on the 'yes I do want to save'
- I tried to just close livesplit and then click on the 'yes I do want to save'
- I tried to right click livesplit - save splits, then exit livesplit

The odd thing is that I created a different set of splits, just to test this, tried each of those 3 ways of saving personal best - they all worked. But none of those work for my regular splits.

Here's how my regular splits are setup 
![image](https://user-images.githubusercontent.com/15522298/74388197-b5752880-4df2-11ea-9b00-e3626c980518.png)

I have compare against -> personal best / real time

**Comment by wooferzfg** [comment]
Could you send your splits file?

**Comment by keld0rn** [comment]
> Could you send your splits file?

[Path of Exile - Act 5 Kitava Kill - Copy.zip](https://github.com/LiveSplit/LiveSplit/files/4195980/Path.of.Exile.-.Act.5.Kitava.Kill.-.Copy.zip)

Let me know if that works.

**Comment by wooferzfg** [comment]
My guess is that this is an issue with the Auto Splitter that you're using. I'd suggest reporting this issue there: https://github.com/brandondong/POE-LiveSplit-Component
