### ISSUE TITLE
crash due to unspecified error

### ISSUE THREAD

**Issue by AverageTrey** [LiveSplit/LiveSplit#1657]
I was getting this error message when trying to open livesplit, so I reinstalled it and it's still happening:

![LiveSplit_2020-02-23_18-04-51](https://user-images.githubusercontent.com/61395555/75122855-9afb4480-5667-11ea-9b7f-4bf2f88e480d.png)

Event logs: https://mega.nz/#!0w8WmQrL!WPJO7zmx8ojSv_n3cXQyzyVZco_3bEpy5DILnbh0Pu4

EDIT: nvm restarted my computer and it works now, strange lolz

**Comment by wooferzfg** [comment]
Based on the event logs, seems like it errored out on this line: https://github.com/LiveSplit/LiveSplit/blob/master/LiveSplit/LiveSplit.Core/Model/Input/GamepadHook.cs#L52

Seems like LiveSplit just blows up if DirectInput isn't working on your computer.

**Comment by wooferzfg** [comment]
This should be fixed with https://github.com/LiveSplit/LiveSplit/commit/97a1d8ed25e46b65c95b48d7f5960e6905564da1
