### ISSUE TITLE
Files Lost

### ISSUE THREAD

**Issue by HyparSR** [LiveSplit/LiveSplit#1667]
When I forget to close LiveSplit after doing runs and come back to it hours later, the program doesn't respond and the program crashes. This crash causes ALL my split files, layouts, SoB times, ANYTHING gained or created during that active session to be completely lost. If there's anything to be done to remedy this PLEASE let me know!!

**Comment by just-ero** [comment]
Closing as stale.

A hang can rarely be recovered from. There isn't really anything you or LiveSplit can do.

**Comment by HyparSR** [comment]
Thank you very much for replying FOUR YEARS after the fact. Your timely
response is very much appreciated.
