### ISSUE TITLE
Implement Urn Support

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#167]
Apparently Urn is in somewhat active development. splits i/o added support for it, so we should probably too. Here's an example of how Urn splits look like: https://github.com/3snowp7im/urn/blob/master/splits/sotn.json

**Comment by CryZe** [comment]
Apparently there's also some run history we can include: The Best Split Times.

**Comment by CryZe** [comment]
Actually, every single segment should be included as its own run, since the best split times could be apart from each other less than the best segments, so we have to assume they are from different runs.

**Comment by CryZe** [comment]
Mostly implemented, I just need to make sure skipped splits are implemented correctly. I'm not sure whether it's stored as 0, null or empty string.

**Comment by CryZe** [comment]
Apparently BatedUrGonnaDie tested it and verified that empty times are indeed stored as "0", so this needs to be implemented.

**Comment by BatedUrGonnaDie** [comment]
More specifically the skipped split in Urn will be "0.000000".
