### ISSUE TITLE
Best Possible Time up to a certain split

### ISSUE THREAD

**Issue by wooferzfg** [LiveSplit/LiveSplit#1682]
Rather than always showing the Best Possible Time at the end of the run, you could have a component that shows the Best Possible Time up to a split earlier in the run. For example, for SM64, this could be something like "best possible upstairs time".

**Comment by nathanesau** [comment]
I have created a component for this which can be found at https://github.com/nathanesau/LiveSplit.PartialRunPrediction.

Here is a screenshot with an example:

![](https://camo.githubusercontent.com/2e981a385d362b8312578276175ceb2b667359ec/68747470733a2f2f692e696d6775722e636f6d2f69764f7a4731382e706e67)

**Comment by just-ero** [comment]
Did the discussion in #1719 resolve this?
