### ISSUE TITLE
How the heck are you supposed to create an autosplitter based on standard output?

### ISSUE THREAD

**Issue by sticks-stuff** [LiveSplit/LiveSplit#1684]
The autosplitting documentation says you can do it but I can't find anything written in Auto Splitting Language that uses standard output to split. Any help? (Sorry if this is the wrong place to put this)

**Comment by wooferzfg** [comment]
I'd suggest asking for help in the [Speedrun Tool Development Discord](https://discord.gg/N6wv8pW)
