### ISSUE TITLE
Livesplit not recognizing .lss split files

### ISSUE THREAD

**Issue by HelptoWin** [LiveSplit/LiveSplit#1700]
I have splits for SMO and They've been saved as a .lss file but when I open Livesplit and hit 
Open Splits -> SMO, it gives an error message stating "selected file not recognized as a splits file." Any help?

**Comment by CryZe** [comment]
Can you attach the splits file?

**Comment by HelptoWin** [comment]
Never mind, the guys on the SMO running Discord helped me out
