### ISSUE TITLE
Subsplit layout settings not saving upon reopening program

### ISSUE THREAD

**Issue by CopperCat** [LiveSplit/LiveSplit#1704]
Specifically the section header comparison section always defaults to current comparison. I change this to say "Personal Best" every time I open the program and then save the layout. Despite this, when I reopen LiveSplit after saving, it will always state comparison is "Current Comparison". - Picante

**Comment by wooferzfg** [comment]
Duplicate of https://github.com/LiveSplit/LiveSplit/issues/1636. This is fixed in the dev build.
