### ISSUE TITLE
Unable to load downloaded components

### ISSUE THREAD

**Issue by SpeckyYT** [LiveSplit/LiveSplit#1712]
The downloaded components don't load even tho I installed those twice into the `<LiveSplit>` folder and `<LiveSplit>/Components` folder.
(with "installed", I mean that I extracted the .dll file from the zip file I downloaded and copied it to the previous listed folders)

![image](https://user-images.githubusercontent.com/40666126/77831945-a2b07c00-7132-11ea-9687-867dfab6a845.png)
^there should be more elements in the `Other` category than what it shows.

I'm pretty confused why that still doesn't work...

**Comment by wooferzfg** [comment]
Which component are you trying to load? It might be in a different category that isn't "Other"

**Comment by SpeckyYT** [comment]
I downloaded every single component existing on the Components website and installed all of them.
I checked all categories, but there isn't any of the downloaded components.

**Comment by wooferzfg** [comment]
Make sure that you restart LiveSplit after putting the component dll's in `LiveSplit/Components`. If that doesn't work, could you [send your event logs](https://pastebin.com/M3n52ABV)?

**Comment by SpeckyYT** [comment]
https://drive.google.com/open?id=18HJHzI9o52aVgI6Cmq04P6qmMJpCmDAZ
Here are the event logs.
