### ISSUE TITLE
Manual Game Time Window always appears on the Top Left

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#174]
Keep the last window location instead. Jumpyluff has this issue, so tell him once it's fixed: https://twitter.com/Jumpyluff/status/595296820261036032

**Comment by wooferzfg1** [comment]
https://github.com/LiveSplit/LiveSplit.ManualGameTime/commit/ae17c37f070d32a1d90b9c105a0f3003a707a236

**Comment by CryZe** [comment]
I don't think you need to manually track it. I think there's a setting for it in the window. But mmh, I guess this works as well xD
