### ISSUE TITLE
Crash when importing splits.io comparison

### ISSUE THREAD

**Issue by Marenthyu** [LiveSplit/LiveSplit#1741]
When attempting to Import a splits.io comparison using "Import from URL", the Error Message "The splits file couldn't be downloaded" appears and after dismissing it, an uncaught exception is thrown with the following Debug information: https://lowee.de/2020-04-09_03-33-42.txt
The following gets logged in DebugView: https://lowee.de/2020-04-09_03-36-45.txt
After quitting from the Error popup, LiveSplit Errors out again, stating what seems to be a concurrentModificationException, logging the following in DebugView and stating the same (german) error message in an Error Popup before closing forcibly: https://lowee.de/2020-04-09_03-38-45.txt

This seems to be consistent across different splits and only started happening with 1.8.0/1 and i can confirm it happening in 1.8.2 as well.

Reproduction steps:
1. Open a splits file
2. Edit Splits -> Import Comparison -> From URL
3. Enter a splits.io link (Example: https://splits.io/5evu )
4. Click OK

Expected Behaviour:
Successful import of referenced splits link.

Observed behaviour:
Multiple Error messages as described above.

Screenshots:
https://lowee.de/LiveSplit_2020-04-09_03-41-30.png
https://lowee.de/LiveSplit_2020-04-09_03-42-14.png
https://lowee.de/LiveSplit_2020-04-09_03-42-28.png
https://lowee.de/LiveSplit_2020-04-09_03-42-43.png
https://lowee.de/LiveSplit_2020-04-09_03-42-54.png
https://lowee.de/LiveSplit_2020-04-09_03-43-06.png

If any information is missing or the issue is not reproducable, please do tell.

**Comment by Marenthyu** [comment]
To ensure it's not on my end, i confirmed that it does work as expected using version 1.7.7

**Comment by Marenthyu** [comment]
Confirmed fixed, thanks for the quick update!

**Comment by wooferzfg** [comment]
Thank you for the bug report!
