### ISSUE TITLE
Autosplitter issues

### ISSUE THREAD

**Issue by xzRockin** [LiveSplit/LiveSplit#1743]
I've been speedrunning Refunct for several years, a short PC game that is highly dependent on the autosplitter to be able to tell if a run is good or not. I've never had a problem with the autosplitter, until a little while ago, I went to do runs and the splits wouldn't start. I went to check and in the autosplitter settings, the start, reset, and split boxes were all unchecked, but they were also greyed out to prevent me from re-enabling them. I tried several solutions and none worked.

**Comment by wooferzfg** [comment]
Did you run into this problem on 1.7.7, or only after updating to 1.8?

**Comment by xzRockin** [comment]
Only after updating to 1.8

**Comment by cursedtoast** [comment]
All ASL files with settings no longer show their settings. They don't fire off either.

**Comment by wooferzfg** [comment]
@xzRockin @cursedtoast Could you try redownloading 1.8.2 and seeing if that fixes the issue? Seems like this could be related to https://github.com/LiveSplit/LiveSplit/issues/1742

**Comment by xzRockin** [comment]
Yeah I'll do that right now

**Comment by xzRockin** [comment]
That fixed it, interesting

**Comment by cursedtoast** [comment]
Redownloading 1.8.2 seems to have worked for me as well

**Comment by wooferzfg** [comment]
Cool, thanks for the quick bug report! I made sure that things will work properly for anyone who tries to use the auto updater in the future.
