### ISSUE TITLE
livesplit-core fails to load for some users

### ISSUE THREAD

**Issue by arch2005** [LiveSplit/LiveSplit#1748]
Every time I launch LiveSplit 1.8.6 I receive the following error:

LiveSplit has crashed due to the following reason:
The type initializer for
'LiveSplit.Model.RunFactories.StandardFormatsRunFactory' 
threw an exception.

Any ideas? Thanks.

**Comment by wooferzfg** [comment]
Could you send your event logs? https://pastebin.com/M3n52ABV

**Comment by wooferzfg** [comment]
Here's another instance of the same error: https://twitter.com/Memery_Man/status/1248675555798638592?s=19

**Comment by JackReaping** [comment]
https://pastebin.com/NhWsJTMn @wooferzfg

**Comment by wooferzfg** [comment]
- Are you on a 32 bit computer?
- Could you try installing https://www.microsoft.com/en-us/download/details.aspx?id=52685 and see if that fixes the issue?

**Comment by JackReaping** [comment]
Thank you thank helped

**Comment by wooferzfg** [comment]
@JackReaping Is it working now?

**Comment by speedrunguy** [comment]
I have the same problem.

**Comment by wooferzfg** [comment]
@arch2005 @speedrunguy Please try installing https://www.microsoft.com/en-us/download/details.aspx?id=52685 and let me know if that resolves the issue.

**Comment by wooferzfg** [comment]
@arch2005 @JackReaping @speedrunguy Please try opening LiveSplit 1.8.7 and see if it works for you.

**Comment by wooferzfg** [comment]
Seems like this is fixed by switching to GNU. https://github.com/LiveSplit/LiveSplit/commit/9437086c9a484749cebfa1b2cc7f7fb142b2eaa7

**Comment by koyo427** [comment]
wooferzfg, this sadly dosent work for me is there anything else i should do?

**Comment by wooferzfg** [comment]
@koyo427 Did you already try re-downloading LiveSplit and installing the [C++ redistributable update](https://www.microsoft.com/en-us/download/details.aspx?id=52685)?
