### ISSUE TITLE
Livesplit crashes

### ISSUE THREAD

**Issue by speedrunguy** [LiveSplit/LiveSplit#1750]
![Screenshot (3)](https://user-images.githubusercontent.com/63490465/79037126-18a6ef80-7bd7-11ea-976a-2ece5ad2bc13.png)
Livesplit always shows this error when I start it. It started popping up when I updated it.

**Comment by wooferzfg** [comment]
Could you try installing https://www.microsoft.com/en-us/download/details.aspx?id=52685 and see if that fixes the issue?

**Comment by wooferzfg** [comment]
(This is the same issue as #1748)

**Comment by wooferzfg** [comment]
Closing this as a duplicate.
