### ISSUE TITLE
McAfee and Norton Declare LiveSplit as Ransomware

### ISSUE THREAD

**Issue by PixloxOnGH** [LiveSplit/LiveSplit#1761]
McAfee (Total Protection) on my 1st PC says LiveSplit is Ransomware, and LiveSplit hangs. After taking it out of quarantine, and restarting my PC several times, LiveSplit lags ENORMOUSLY. Is recreatable by deleting LiveSplit and Reinstalling. Will activate after saving your Split 2-3 times. 

On my second PC, Norton (360 Deluxe) says LiveSplit is a Trojan. However LiveSplit lags until you restart and take it out of quarantine.

**Comment by wooferzfg** [comment]
It's not a trojan, so you should whitelist it or disable the virus scanner while you're using it.
