### ISSUE TITLE
No section timer

### ISSUE THREAD

**Issue by Derpspace** [LiveSplit/LiveSplit#1762]
![image](https://user-images.githubusercontent.com/59072461/79516602-7beab480-8011-11ea-9de7-16647a48e941.png)
what is happening here

**Comment by Derpspace** [comment]
https://ibb.co/NVq349V

**Comment by wooferzfg** [comment]
can you send your splits and layout?

**Comment by Derpspace** [comment]
https://drive.google.com/file/d/1fY-JC2RIJPEu6VLzzQfgHtguY1eRsaJp/view?usp=sharing
(layout)
https://drive.google.com/file/d/1y69-g_stsh2B2AibB3NOL815FJJgEhCV/view?usp=sharing
(splits)

**Comment by Derpspace** [comment]
oh nevermind
it was on game time for some reason
