### ISSUE TITLE
Implement LiveSplit Remote

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#177]
LiveSplit Remote hosts a HTTP Server that serves a modified version of https://github.com/iotku/websplit which will show the current state of LiveSplit through the website. Splitting and other interactions will allow the user to use this website to interact with LiveSplit. This allows users to control LiveSplit through their phones or other devices that have a web browser. The interaction with LiveSplit will either be through a WebSocket or AJAX.

**Comment by Ekelbatzen** [comment]
For the record of this issue, I did a remote app for android without using the browser:
https://github.com/Ekelbatzen/LiveSplit.Remote.Android
Other platforms are still lacking, though.
