### ISSUE TITLE
Allow registering on SpeedRunsLive over the LiveSplit GUI

### ISSUE THREAD

**Issue by BitPatty** [LiveSplit/LiveSplit#1770]
Would make it easier for people without IRC experience to get started with SRL.

**Comment by CryZe** [comment]
I think this is very unlikely to happen, as we are actually rather looking at deprecating / removing it.

**Comment by wooferzfg** [comment]
We'll allow registering on SRL in the GUI whenever SRL provides an OAuth solution to do so 🙂
