### ISSUE TITLE
Allow 32/64 bits override for DeepPointer

### ISSUE THREAD

**Issue by dragonbane0** [LiveSplit/LiveSplit#1787]
Some Unity games, in this instance Firewatch, have a 64 bit executable but map their mono dll into a 32 bit address space apparently. So I currently can not use DeepPointer for my ASL autosplitter as the code attempts to read an 8 byte pointer while the pointers are only 4 bytes big. 

To solve it I have to do manual memory reads at the moment. An override to specify 32 bits in combination with an absolute base would be really appreciated.

**Comment by Voxelse** [comment]
It would have been useful for some of my splitters as well and it probably will again so I've added it: https://github.com/LiveSplit/LiveSplit/pull/1864
