### ISSUE TITLE
LiveSplit Crash

### ISSUE THREAD

**Issue by zebalcoff** [LiveSplit/LiveSplit#1801]
Whenever I try to open LiveSplit, I get the error message "LiveSplit has crashed due to the following reason: Success"

**Comment by wooferzfg** [comment]
Are you on Windows? Did you extract the contents of the ZIP file to a folder?

**Comment by zebalcoff** [comment]
> Are you on Windows? Did you extract the contents of the ZIP file to a folder?

I’m on Mac using Wine, I placed the contents in the Wine folder

**Comment by wooferzfg** [comment]
LiveSplit doesn't work with Wine at the moment.

**Comment by zebalcoff** [comment]
> LiveSplit doesn't work with Wine at the moment. https://one.livesplit.org is the best alternative if you want to use LiveSplit on Mac.

Oof, okay thank you
