### ISSUE TITLE
Fix the Sum of Best and Cleanup Algorithm

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#181]
If you skip over multiple segments, the algorithm assumes the combined segment started before every single skipped segment, which is not the case and can in rare situations lead to a wrong Sum of Best. It should verify whether the skipped split is actually the first skipped split before tracking this branch. This also results in the Clean Up messages to appear for every single one of these skipped segments.

**Comment by CryZe** [comment]
Seems to still ask multiple times for these splits: https://splits.io/5so

**Comment by wooferzfg1** [comment]
This wasn't a bug with the cleaning/SoB algorithm but rather with the Segment History being filled with duplicate entries. This is now another one of the things that will be cleaned up whenever Splits are fixed.

https://github.com/LiveSplit/LiveSplit/commit/70903710f2c0e70066e9af5c1d643af74deef2ca
