### ISSUE TITLE
When I open live split it just closes immediately 

### ISSUE THREAD

**Issue by RebornIlluminati** [LiveSplit/LiveSplit#1810]
When I try to open livesplit it just closes immediately without letting me do anything, I uninstalled and reinstalled it but it still has the same problem. Is there a way to fix this?

**Comment by wooferzfg** [comment]
Is it getting blocked by a virus scanner?

**Comment by RebornIlluminati** [comment]
That was it, I thought I had used it before with my current antivirus but I guess not.
