### ISSUE TITLE
Confused as to what's going on? Negative hours played and an obscene number of attempts/long time?

### ISSUE THREAD

**Issue by mcd573** [LiveSplit/LiveSplit#1815]
I have 21 attempts in the game Uplink- and my worst time has been 32:52. However, the graphs seem to be a bit... off. Someone able to help me figure this out?
![image](https://user-images.githubusercontent.com/32823185/81391245-c4fec780-90ea-11ea-8820-907567a75dca.png)

![image](https://user-images.githubusercontent.com/32823185/81391255-c9c37b80-90ea-11ea-82e7-04987f506814.png)

**Comment by CryZe** [comment]
Can you attach / send your splits?

**Comment by mcd573** [comment]
[uplinksheet.xlsx](https://github.com/LiveSplit/LiveSplit/files/4602457/uplinksheet.xlsx)

**Comment by wooferzfg** [comment]
Could you send your splits file instead?

**Comment by just-ero** [comment]
Closing due to insufficient information.
