### ISSUE TITLE
Implement a way to disable Hotkey Modifiers

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#182]
When sprinting in a game with Shift, you can't split due to LiveSplit having Hotkey Modifiers which treat modified keys as different keys. There should be a way to disable this. Tell Phillotrax about it, once it's implemented: http://www.twitter.com/Phillotrax/status/597491615788335104

**Comment by wooferzfg1** [comment]
Actually this isn't a LiveSplit issue. If you have A set as a hotkey, Shift + A will still work for that hotkey. The specific problem that he had was that the NumPad doesn't work while Shift is held, which has nothing to do with LiveSplit.
