### ISSUE TITLE
Livesplits Autosplitter Not Starting Properly and I Can't See the Timer Until I Manually Start and Than Go to Pause the Timer

### ISSUE THREAD

**Issue by shranosisgod** [LiveSplit/LiveSplit#1821]
whenever I try to speedrun hollow knight the auto-splitter does not start when the run starts and if i manually start it the timer does not update until paused meaning I can't see my time on the run

**Comment by rvolden** [comment]
I'm not sure if this is the same as you, but I was also having trouble with my hollow knight splits not timing. There was an update that removed all of my splits from my split settings. Go through and re-add them. Hopefully this helps

**Comment by just-ero** [comment]
Closing as invalid.

Please report issues with autosplitters in their respective repositories or communities.
