### ISSUE TITLE
Add split name abbreviations to Subsplits

### ISSUE THREAD

**Issue by wooferzfg** [LiveSplit/LiveSplit#1846]
The Splits component already has this.

**Comment by shroomwastaken** [comment]
hey, is this issue up for grabs? i want to try and do this

**Comment by shroomwastaken** [comment]
(sorry for the big message)
ok i got abbreviation working for the normal subsplits, but not for the section splits (i mean the ones at the end of a section, for example `{section name} split name`)

i also added a checkbox to the subsplit settings to turn this on (bottom left)
![image](https://github.com/LiveSplit/LiveSplit/assets/59111626/37f59eb0-c858-48f8-b793-1b19a5a218b5)

what i have right now turns this
![image](https://github.com/LiveSplit/LiveSplit/assets/59111626/29392d55-71cb-483d-8934-ca58fadaf531)

into this
![image](https://github.com/LiveSplit/LiveSplit/assets/59111626/cdcd95d7-492a-483d-9674-04ad03987e1f)

where the split names are this:
![image](https://github.com/LiveSplit/LiveSplit/assets/59111626/3bed8625-86fe-4bbf-8a92-4d16a9d47d2f)

im struggling to figure out a way to make the section split abbreviate properly, any help would be appreciated

**Comment by shroomwastaken** [comment]
do i have to fork the subsplits component repo and make a pr there for it to be added into livesplit? how does this work

**Comment by wooferzfg** [comment]
> do i have to fork the subsplits component repo and make a pr there for it to be added into livesplit?

Yes
