### ISSUE TITLE
Submit to speedrun.com from LiveSplit

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#185]
This could theoretically already be possible. You'd simulate a login, store the cookie and then do an HTTP POST Request with this cookie. I haven't checked how they do it exactly, but if the browser can do it, it shouldn't be too hard.

**Comment by CryZe** [comment]
It's a POST Request of the following type:
application/x-www-form-urlencoded; charset=UTF-8
to the following URL:
http://www.speedrun.com/ajax_editrun.php?id=57901&game=3074&action=submit
with game being the game id, id being irrelevant (?).

The Form Data is:
category:Story_Mode
player1:player1value
playerselect:0
hour:1
minute:2
second:3
milliseconds:456
variable867:2715
console:54
year:2015
month:5
day:12
video:http://youtube.com/video
splitsio:
comment:commentvalue
csrftoken:yF8hqT75EUICE1HBKGVAbAK5jiprxeda4EVITYBVmtJQcJKG-NPwGfa3lbyLxU6-

The Cookie required for submitting is: PHPSESSID

The CRSF Token, the variables and the game id need to be parsed from the HTML.

**Comment by Lighnat0r** [comment]
id is used for updating existing runs so yes, it is irrelevant in this case.

playerselect is only allowed to be 0 for mods (as they can submit runs for others), otherwise it needs to be which player the current user is (1, for single player runs). player1 is irrelevant in that case.

**Comment by CryZe** [comment]
@Lighnat0r Should I wait on a proper API or should I implement it like that? Can we expect an API any time soon?

**Comment by sgt-kabukiman** [comment]
I can start working on the API this weekend. Can it wait until then?

**Comment by CryZe** [comment]
Yeah, it's not urgent at all. Thanks for implementing the API :)

**Comment by sgt-kabukiman** [comment]
It will, for simplicity sake, probably be based on an alphanumeric API key, which can be used to authenticate on behalf of a user. Users will (maybe not at first, but at some point) be able to generate a new API key, rendering the old one useless. So be prepared for sudden HTTP 403 responses :)
