### ISSUE TITLE
Livesplit Crashing when game crashing

### ISSUE THREAD

**Issue by ghost** [LiveSplit/LiveSplit#1857]
Hey there, for some reason when i'm speedrunning my game is crashing. 
No worries i just restart it. But sometimes Livesplit is crashing as well. I mean not always ; sometimes Livesplit continues working fine. But sometmes it freezes completely and i have to restart it, and ofc my times are gone.

Here the event list of a test i made, i launched the game, and then force quit it, relaunched it and Livesplit was craching.

[Crash Livesplit.zip](https://github.com/LiveSplit/LiveSplit/files/4671545/Crash.Livesplit.zip)

I'm looking for a solution to solve the game crashing issue, but if you have some advices to fix LiveSplit it could be enough.

Thank you !

**Comment by wooferzfg** [comment]
Looks like the issue here is with `Ds3Component`, whatever that is.

**Comment by BoostHazard** [comment]
I don't use any Autosplitter, i'm using the auto start though...

**Comment by just-ero** [comment]
Closing as stale.

The issue was possibly caused by `Ds3Component`. Souls games now use SoulSplitter. Issues with custom components should be reported in their respective repositories or communities.
