### ISSUE TITLE
Implement importing Comparisons and Runs from the speedrun.com Leaderboards

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#187]
It should probably include the following:
 * Downloading the World Record Run (maybe just the best run on the leaderboards)
 * Downloading the Rival Run (the run that is closest to your PB but better)
 * Downloading all Runs of the Leaderboard as Comparisons

**Comment by CryZe** [comment]
I implemented downloading the World Record run. The comparison is currently called "World Record". I'm not too sure about that, maybe it should include the runner's name or just be the runner's name.
I also implemented downloading the Rival Run. It's a bit weird to check who's actually your rival since we don't know who you even are, this should be fixed once there's an actual API. Also the comparison is currently called "Rival", which doesn't include the Rival's name either, not too sure about that either.
You can also download the whole Leaderboard, where yet again, it is weird to check where you are. At the moment it tries to download all runs and discards the one where the final time matches, which is not too bad I guess. This should still be cleaned up once there's an API.

All of these are currently only available when downloading comparisons. When opening a run, I guess opening the World Record Run and the Rival Run would make sense. Downloading the whole leaderboard wouldn't work, since they are meant to be comparisons, you can't open multiple runs at once. Open the World Record Run and the Rival Run would be a bit weird too though. Would it use the currently opened run as the basis to find them or would it just ask you which game and category you want to open the World Record Run for? Also for the Rival Run, would it ask who you are?

**Comment by CryZe** [comment]
Not sure if we still want this, now that we have a Dialog for Browsing Speedrun.com. Probably not.

**Comment by wooferzfg1** [comment]
There should still be a way to download the whole leaderboard though (maybe clicking Download while on a category node?)

**Comment by CryZe** [comment]
Closing this for now, since we probably just keep it the way we have it at the moment.
