### ISSUE TITLE
README.md issue

### ISSUE THREAD

**Issue by ioerrorle** [LiveSplit/LiveSplit#1879]
Clean install of VS Community 2015 Update 3, cloned repo, opened solution, build failed, many syntax errors.
Need clear step by step instruction.

**Comment by wooferzfg** [comment]
You might need C# 7?

**Comment by ioerrorle** [comment]
Yes, on VS Community 2019 all is good, should fix compile info.

> LiveSplit is written in C# 6 with Visual Studio and uses .NET Framework 4.6.1. To compile LiveSplit, you need one of these versions of Visual Studio:
> 
>    Visual Studio 2015 Community Edition
>    Visual Studio 2015
> 
> Simply open the project with Visual Studio and it should be able to compile and run without any further configuration.
