### ISSUE TITLE
Rename Predicted Time to Current Pace

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#189]
This fits the component a bit better because it's not predicting the final time if it's not used with the Average Segments.

**Comment by CryZe** [comment]
This would break all layouts, so idk how we could do this properly, unless we don't rename the DLL.

**Comment by wooferzfg1** [comment]
These seem like good options at the moment:

Predicted Time -> Current Pace
Predicted Time (Average) -> Predicted Time
Predicted Time (Best) -> Best Possible Time
