### ISSUE TITLE
Timer freezes when using an autosplitter

### ISSUE THREAD

**Issue by MyPetCactus** [LiveSplit/LiveSplit#1899]
I play Hollow Knight, and when using the autosplitter for it while the game is open the timer will not move. Livesplit knows the timer is running as you can see in the video, but I cannot actually see the times. When I deactivate the autosplitter the timer runs fine.

**Comment by just-ero** [comment]
Closing as invalid.

Please report issues with autosplitters in their respective repositories or communities.
