### ISSUE TITLE
Autosplitters SetSettings(null) call in the splits editor

### ISSUE THREAD

**Issue by Dalet** [LiveSplit/LiveSplit#190]
How to reproduce:
- Have splits set to a game that has an autosplitter with settings, make sure the autosplitter is deactivated before doing the next steps.
- Close the splits editor if it was open
- Open the splits editor
- Click Activate, don't open the settings
- Click Cancel

**Comment by CryZe** [comment]
I think I actually fixed that on some branch a few days ago. I'll check though.
