### ISSUE TITLE
Sum of Best Glitch

### ISSUE THREAD

**Issue by ShadowSMG2** [LiveSplit/LiveSplit#1907]
Hi, I've noticed when using LiveSplit that on one of my late segments for two different Categories my BPT will begin to go up and my Best Segments comparison will tell me I'm losing time way earlier than it should be (e.g, my gold is a 2:41.xx but it says im losing time from 1:53.xx) is there a known fix for this? Here is a clip of it taking place- https://youtu.be/9iSAMwtJgCQ?t=9542

**Comment by wooferzfg** [comment]
Try doing Edit Splits -> Other -> Clean Sum of Best

**Comment by ShadowSMG2** [comment]
wont that delete my golds?

**Comment by CryZe** [comment]
No, clean is for fixing problems, "clear" would mean removing them

**Comment by ShadowSMG2** [comment]
ah ok ill give it a go, ty

**Comment by ShadowSMG2** [comment]
yeah it worked, thanks a lot guys
