### ISSUE TITLE
Always match the final split when racing and importing comparisons

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#191]
The final split should always be the same "Game State" for the same category, so we can just assume it's the same without checking the name. This should be an easy fix when importing a comparison, not so much when racing. When racing there's no way to check whether it even was then final split or not, except maybe checking for .done, but that might be a bit delayed. So the final split should maybe be tagged as the final split during a race.

**Comment by wooferzfg1** [comment]
Both importing comparisons and racing should also trim and convert to lower case or whatever else to make matching better.

**Comment by wooferzfg1** [comment]
needs to be tested https://github.com/LiveSplit/LiveSplit/pull/213

**Comment by wooferzfg1** [comment]
https://github.com/LiveSplit/LiveSplit/commit/01965e191577ea6a272faa63877149f0e48cad6b
