### ISSUE TITLE
Implement parsing the record ids of speedrun.com

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#193]
This will allow opening the record's web page and later on, once there's a proper API, being able to edit them.

**Comment by CryZe** [comment]
Commit 2b4bff2306a2aa2ce598d82f7ccbd17909bdd01a implements this. This is somewhat flawed though, since there's no way of figuring out the game's id at the moment. It's using the TWW leaderboard currently, which seems to be working to some degree, but this definitely needs to be fixed once there's a way of querying the game's id.

**Comment by Lighnat0r** [comment]
This relates to something I am planning to change/fix soon: linking to http://www.speedrun.com/run/{0} will then work so there won't be a need to get the game url.

**Comment by CryZe** [comment]
@Lighnat0r That sounds cool. There should be some way of figuring out the game id of the runs / games eventually though.

**Comment by Lighnat0r** [comment]
Yeah definitely, there will be in the new API.

**Comment by Lighnat0r** [comment]
Linking to http://www.speedrun.com/run/{0} now works.
