### ISSUE TITLE
LiveSplit does not open when computer is offline

### ISSUE THREAD

**Issue by psenough** [LiveSplit/LiveSplit#1949]
It is listed on taskmanager but does not appear on screen.

Event viewer error:
![Capture2](https://user-images.githubusercontent.com/808571/88009001-6356d280-cb09-11ea-81e6-6dc9f6d7af4d.PNG)

v1.8.11 Windows 10

**Comment by wooferzfg** [comment]
Is your computer entirely disconnected from the internet (as opposed to being connect to a network with no internet, which results in downloads hanging)? LiveSplit should open almost instantly if it's entirely disconnected.

**Comment by psenough** [comment]
was indeed connected to the local network but the local network didn't have internet (uplink on the modem router was down).
still, ideally it shouldn't hang like that, should timeout the connection attempts and carry on with it's business offline (maybe reattempt connections after a few mins)
