### ISSUE TITLE
LiveSplit Number of Splits shown

### ISSUE THREAD

**Issue by juicyy** [LiveSplit/LiveSplit#1958]
Hi,

Im currently having an issue with the splits shown at a time. All my splits are shown the whole time and I dont know how to change it.
Thx in advance

**Comment by wooferzfg** [comment]
You can configure the number of splits shown in the Splits component settings.

**Comment by juicyy** [comment]
> You can configure the number of splits shown in the Splits component settings.
The only thing I can see is Total and Upcoming splits, not Splits shown

**Comment by wooferzfg** [comment]
Total Splits affects how many splits are shown.

**Comment by just-ero** [comment]
The issue appears to be resolved.
