### ISSUE TITLE
Splits i/o v3 Upload seems to be broken

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#196]
And browsing doesn't seem to be working either.

**Comment by wooferzfg1** [comment]
We likely want to get rid of splits.io browsing anyway because speedrun.com browsing is much better.

**Comment by CryZe** [comment]
The API should still be useable though, so we should fix both bugs.

**Comment by CryZe** [comment]
The Upload is broken due to splits i/o not supporting the new LSS file format.

**Comment by CryZe** [comment]
This being fixed now depends on https://github.com/glacials/splits-io/issues/171

**Comment by CryZe** [comment]
glacials implemented 1.6 support for splits.io
