### ISSUE TITLE
autosplitter doesnt work right with images

### ISSUE THREAD

**Issue by makeopts** [LiveSplit/LiveSplit#1962]
is this a avast issue or just my pc being genuinely retarded
and also deltas causing it, not sure why

**Comment by wooferzfg** [comment]
What does "with images" mean?

**Comment by DangerSR** [comment]
For some reason, when my livesplit background has images it completely messes up something in livesplit so the autosplitter completely dies https://streamable.com/pxshl0

**Comment by DangerSR** [comment]
also for another reason, when i didnt have my controller connected, it was completely fine. i did a sadx test run and the delta didnt fuck up

**Comment by DangerSR** [comment]
[](url)

**Comment by DangerSR** [comment]
i did that on accident

**Comment by just-ero** [comment]
Does this issue persist in the most recent stable version of LiveSplit?

Unless the autosplitter accesses the background image, it is not possible for the background image to impact the autosplitter.

Closing due to insufficient information. The linked streamable is not available.
