### ISSUE TITLE
LiveSplit suddenly stopped recognizng side mouse buttons

### ISSUE THREAD

**Issue by Denny2705** [LiveSplit/LiveSplit#1980]
So i was trying out LiveSplit and everything was working fine, but after a while, it stopped recognizing my mouse side buttons, which i had set to Start/Split and Reset. Please Help.

**Comment by Denny2705** [comment]
Enabling "Allow Numpad as Hotkeys" solved this.

**Comment by wooferzfg** [comment]
@Denny2705 Was that not enabled by default for you?
