### ISSUE TITLE
Components not sorted once loaded

### ISSUE THREAD

**Issue by AllocatorMK** [LiveSplit/LiveSplit#2000]
The components are not sorted when loaded. I created a new component called Next Time Save (NextTimeSave.dll). Now, because all components X are named LiveSplit.X.dll, it is displayed in the incorrect order (see image). Now, I'm not sure how to fix this properly, because I don't like how a public dictionary is used in the ComponentManager class, but presumably LoadAllFactories() should be altered.

![Incorrect order](https://user-images.githubusercontent.com/69111085/89458956-2ffe7f80-d768-11ea-8c95-65227d421416.png)

**Comment by wooferzfg** [comment]
You can call it `LiveSplit.NextTimeSave.dll`. Components are sorted based on their DLL name.
