### ISSUE TITLE
LiveSplit changes my final split time and my pb when I update a best segment?

### ISSUE THREAD

**Issue by Solicit10p** [LiveSplit/LiveSplit#2016]
Let's say I have a pb and split times set, and I beat a couple of the best segments in my pb run, but I did not complete the new run. When I exit or reset LiveSplit, it tells me I beat some of my best times and it asks if I want to update them, so I say yes. Do I want to update those segments? When I do say yes, it changes my final split time and my pb time to a faster pb than I actually have. Do I have to complete a run in order to update any specific best segment? Should I not be updating or am I having an error?

**Comment by wooferzfg** [comment]
What do you see if you right click and go to "Compare Against"? Is it "Personal Best"?

**Comment by Solicit10p** [comment]
> What do you see if you right click and go to "Compare Against"? Is it "Personal Best"?

Best segments is selected, not personal best. Should I change that?

**Comment by wooferzfg** [comment]
Yes, it should be "Personal Best".

**Comment by Solicit10p** [comment]
> Yes, it should be "Personal Best".

That was it, thank you so much!
