### ISSUE TITLE
Font Override not working in at least the Comparing Against component.

### ISSUE THREAD

**Issue by VilePoison** [LiveSplit/LiveSplit#2021]
I tried to alter the font for the comparison title but no matter what I do it ignores the override and uses the settings defined in the 'Layout' tab. I tried to change the type of font and size with the override flag active, but that didn't work. I also tried to see if I restarted Livesplit if it would work but it didn't. I should note that the settings seem to be preserved (changes do not visibly undo themselves if I exit the window or close livesplit, i.e the settings I chose don't disappear). I don't know if this issue is occuring with other components.

**Comment by wooferzfg** [comment]
I removed the font customization for now because adding it is a bit tricky. We can add font customization to all the components in #248.
