### ISSUE TITLE
Always on top works only in windowed mode ?

### ISSUE THREAD

**Issue by Rebilium** [LiveSplit/LiveSplit#2035]
Disclaimer: this issue might be a replica of [#1132](https://github.com/LiveSplit/LiveSplit/issues/1132) and maybe there are more similar issues.

so, im not sure if this is a bug or its just how LiveSplit works. if its how it works, then i hope that the team have a potential addition or an enhancement. having the timer on top with full screen mode is just perfect.

**Comment by just-ero** [comment]
Closing as unrelated.

No application can be displayed on top of a full screen game. This is not an issue with LiveSplit.
