### ISSUE TITLE
Fullscreen doesn't work.

### ISSUE THREAD

**Issue by ThinkTwortles2008** [LiveSplit/LiveSplit#2036]
I have been speedrunning minecraft, but when I press F11 to make it fullscreen, it hides livescreen, so i cant see it.

**Comment by Avasam** [comment]
Have you tried the "Always on Top" option?
![image](https://user-images.githubusercontent.com/1350584/95939626-83193200-0daa-11eb-91bc-789dd6bcdbb1.png)

**Comment by ThinkTwortles2008** [comment]
I have that on, but I think that minecraft has a weird fullscreen function, so it won't show livesplit

**Comment by just-ero** [comment]
Closing as unrelated.

No application can be displayed on top of a full screen game. This is not an issue with LiveSplit.
