### ISSUE TITLE
It wont work on mac.

### ISSUE THREAD

**Issue by lapcatlak** [LiveSplit/LiveSplit#2037]
EXE cant run on mac, so I cant use livesplit on mac

**Comment by westim** [comment]
That's correct; this application is currently built with the .NET Framework which is Windows-only.

A browser-based version exists that might meet your needs. I've never used this app, so I have no idea how well it compares to the original LiveSplit.

https://one.livesplit.org/

**Comment by lukasjuhrich** [comment]
On a related but different note, wouldn't it be a good idea to port the core stuff to .net5 (i.e., everything but `LiveSplit.View`)?

I think this would allow linux users (like me, if I find time) to try and implement a (let's say minimal) [MAUI-based](https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/) View in a fork, although there is probably more work to be done than that.

**Comment by lukasjuhrich** [comment]
Having looked a bit through other parts of the livesplit ecosystem, it is unclear to me where the road is going with regards to platform compatability:

- There is LiveSplitOne, which uses livesplit-core, which is developed in rust and cross-platform. So there seems to be _some_ effort to push this issue.
- Autosplitters and the `LiveSplit.Server` seem to be “components” of this `LiveSplit` project; They depend on information from livescript and on `LiveSplit.Core` (which is something in .net and not the same as livesplit-core). To make autosplitters work with LiveSplitOne however, there would need to be a cross-platform implementation of `LiveSplit.Server` exposing a websocket port.

There are essentially the two options
- Create a cross-platform `core` library together with a cross-platform server, change this repo to use this new corelib, and provide a new „plugin api“ in this core project such that autosplitters etc can work in an inherently platform-compatible way
- Make this project platform compatible by strictly separating view-related stuff from the rest and moving to `.NET 5`, giving oneself room to switch to `.NET MPAUI` eventually.

See also https://github.com/ShootMe/LiveSplit.HollowKnight/issues/34.

The first option seems way more invested to me; but I'm missing a lot of context here, I've only seen bits of the code.

I think platform compatibility is a gradually more important topic; with steam supporting many games on Mac and Linux there will be a large userbase of people interested in speedrunniing missed by having tools such as LiveSplit not available out-of-the-box.
I know it's going to be a lot of work, but having a roadmap would be a valuable first step IMO.

**Comment by lapcatlak** [comment]
sorry for not replying but i dont understand this

**Comment by lukasjuhrich** [comment]
Don't worry, this is primarily meant as a note for the developers.
„Making things work on mac/linux“ is quite a complicated endeavor in this case.
I wanted to assist the developers with some coarse technical discussion.

**Comment by henyK** [comment]
The older application and repository `LiveSplit` is somewhat unmaintained at this point, aside of pull requests for the official autosplitter list being reviewed and merged.

`LiveSplitOne`, which, as you already mentioned, uses `livesplit-core` as its foundation, is supposed to be a cross-platform replacement in the long run which currently is being actively developed. Aside of a more structured, cleaner codebase and the portability aspect it will also offer more flexibility in terms of creating autosplitters.

To my knowledge the plan is to allow autosplitters being written in pretty much every language that compiles to Wasm. This also results in a higher safety as the respective modules are sandboxed. From the looks there won't be backwards compatibility for older ASL scripts.

Keep in mind that this is all still very much work in progress and thus subject to change. If you have any further questions, I'd believe the actual responsible devs might be able to help you.

**Comment by lapcatlak** [comment]
Okay. (I still want it on mac so i can do a Minecraft speedrun)

**Comment by CryZe** [comment]
There is a somewhat experimental OBS plugin that works on macOS: https://github.com/CryZe/obs-livesplit-one

**Comment by AnInternetTroll** [comment]
Minecraft java also has a cross platform timer available if you want in game time. https://github.com/NinjaSnail1080/mc-universal-in-game-timer/blob/master/README.md

**Comment by lukasjuhrich** [comment]
Thanks @henyK for giving me some context here!
I do have noticed that there are lots of bindings for `livesplit-core` for various languages, but was a bit unclear about what that would mean for future autosplitters. Perhaps I'll get in touch there.

**Comment by CryZe** [comment]
The auto splitters don't directly talk to livesplit-core, instead there's a separate auto splitter runtime library (that is completely independent of livesplit-core, so it's easily embeddable into other timers / projects). It then presents its own APIs (for querying processes and reading from them, and a virtualized "OS") to the auto splitters.

**Comment by Pangaea666** [comment]
Wanted to pipe in with support (or rather, a wish) for this cross-platform endeavour to succeed. I'm on Linux as well, and looked into solutions for speedrun timers, but didn't find anyone that worked satisfactorily. Only real-time is really possible. Livesplit One/Livesplit One Desktop looks most promising so far, but autosplitting doesn't work, and the latter is a pain to set up since there is no right-click functionality (for settings/splits etc).

Would be excellent if Livesplit worked on Linux too, and if that enables autosplitting to function for Hollow Knight.

**Comment by lukasjuhrich** [comment]
I believe the relevant issue should be  LiveSplit/livesplit-core#176

**Comment by just-ero** [comment]
Closing as unrelated.

LiveSplit is a Windows-only software.  
LiveSplit One is the cross-platform rewrite.
