### ISSUE TITLE
Negative segment times displayed when skipping segments

### ISSUE THREAD

**Issue by hedgehog125** [LiveSplit/LiveSplit#2041]
I've been using segment times for my runs which has been working well but I've found that if you skip segments, the first segment will display a negative segment time as well as the segment delta thinking I've got a really good new PB. It saves the correct time in the table but it's kind of annoying because I'm going to be practicing part way through the game a lot.

I'm guessing it's calculated from the total times instead of from the segment times. (or the grid calculates it in a different way?)

Side note: is there any way to skip to a segment while resetting the timer? Or do I just start the timer negative and then wait for it to get to 0?

I'm using 1.8.15 on Windows 10.

**Comment by just-ero** [comment]
Does this issue persist in the most recent stable version of LiveSplit?

**Comment by hedgehog125** [comment]
Just tried to replicate it and couldn't, so happy to mark this as resolved. Although I now realise my original instructions were unclear so I might have missed something.
