### ISSUE TITLE
"Insert Below" Option greyed out.

### ISSUE THREAD

**Issue by requirediscordjs** [LiveSplit/LiveSplit#2048]
![image_2020-11-08_164515](https://user-images.githubusercontent.com/70280684/98485078-c7e58c80-21e1-11eb-8e7a-5c8ccb6af0bd.png)

I don't know what to do.
(and yes I am speedrunning Minecraft Trial)

**Comment by CryZe** [comment]
This means the timer is still running. Reset it and then open the splits editor again.
