### ISSUE TITLE
[Feature Request] Add a way to turn down refresh rate of LiveSplit

### ISSUE THREAD

**Issue by Derpspace** [LiveSplit/LiveSplit#2058]
I know wsplit has this and i think it would be a good idea to add it on livesplit I don't know how hard it would be but here is a screenshot of the feature in wsplit.
![image](https://user-images.githubusercontent.com/59072461/100528401-01d2fe80-31a2-11eb-9e3f-ef9a58a9bbcc.png)
Its mostly so if i want to have 2 decimals on my timer it doesn't use most of the low end CPU. :)

**Comment by Avasam** [comment]
@Derpspace 
Fixed by #2095 and #1195 . Until if/when it becomes part of LiveSplit, you can find a download here: https://github.com/Avasam/LiveSplit/releases
