### ISSUE TITLE
When will there be an app with overlay for mac? I can test betas if you want :)

### ISSUE THREAD

**Issue by AstroOrbis** [LiveSplit/LiveSplit#2059]

**Comment by AnInternetTroll** [comment]
There's an early beta for a desktop version of [livesplit one](https://github.com/CryZe/livesplit-one-desktop/). You can install it right now and play with it if you want. On pop_os I had to install [a fork of it](https://github.com/CryZe/livesplit-one-desktop/pull/18/) to get it to work or it would crash when I resized it.

**Comment by AstroOrbis** [comment]
I do have livesplit one as an app using brave/unite i forgot which one

**Comment by AnInternetTroll** [comment]
Livesplit one the browser version isn't really a native app and doesn't provide global hotkeys. The one I linked above is a work in progress desktop cross platform project.

**Comment by just-ero** [comment]
Closing as unrelated.

LiveSplit is a Windows-only software.  
LiveSplit One is the cross-platform rewrite.
