### ISSUE TITLE
Racetime integration crashes

### ISSUE THREAD

**Issue by lenophis** [LiveSplit/LiveSplit#2060]
Whenever I try to use livesplit to do anything with racetime.gg, the exception gets thrown.

![image](https://user-images.githubusercontent.com/29736776/102703756-8ad8d500-4238-11eb-9bd5-94e1a5c8c696.png)

It has been like this since ragetime.gg integration was implemented.

![image](https://user-images.githubusercontent.com/29736776/102703765-aba12a80-4238-11eb-8076-503c42bf58bb.png)

Since a lot of things are moving over to racetime, it would be nice to finally nail down why this has been happening.

**Comment by wooferzfg** [comment]
Try redownloading LiveSplit. You're missing `DarkUI.dll`.

**Comment by lenophis** [comment]
Wouldn't that have been included with the updates over the last two or so years? This seems like a curious step.

**Comment by wooferzfg** [comment]
It's included in the updates. However, there was a brief period after 1.8.8 was released where that DLL was missing: https://twitter.com/LiveSplit/status/1257051818871476227?s=19

**Comment by just-ero** [comment]
Closing as stale.

This uses an outdated version of the Racetime integration.
