### ISSUE TITLE
Autosplitter not working

### ISSUE THREAD

**Issue by thaniel3** [LiveSplit/LiveSplit#2062]
my autosplitter just stopped working and when I click Settings I can't do nothing and nothing appears on the screen: [https://prnt.sc/vlvqk0](url)
Can someone help me?

**Comment by wooferzfg** [comment]
I'd suggest reaching out to the developer of the Autosplitter.

**Comment by thaniel3** [comment]
but this is happening with every game, not just one.

**Comment by just-ero** [comment]
Closing as stale for now.

This issue could be caused because the user did not extract the ZIP archive after downloading.
