### ISSUE TITLE
Force specific size of the window

### ISSUE THREAD

**Issue by lordlouckster** [LiveSplit/LiveSplit#2064]
My LiveSplit window gets stuck to the aspect ratio 239:198, and I can't narrow it, unless I zoom it extremely small.

**Comment by wooferzfg** [comment]
You can set a specific size in the Layout Editor. When in Vertical mode, there's a minimum width for the layout depending on the components in it.

**Comment by just-ero** [comment]
Closing as this is intended behavior.
