### ISSUE TITLE
Livesplit isn't displaying when I watch recorded videos.

### ISSUE THREAD

**Issue by Enasons** [LiveSplit/LiveSplit#2065]
I would have my livesplit open, then, after I'm done recording I go to watch it. The display is up while I'm recording, but when I go to watch it, it's not there. Am I doing something wrong? It's really frustrating considering I seen no one else have this issue. Please tell me what I'm doing wrong.

**Comment by SquareMan** [comment]
This is not at all an issue with LiveSplit and based on what you've said it's impossible to tell what you're doing wrong. If you're using something like OBS you probably have to add a window capture for LiveSplit, or replace your existing source with a Desktop Capture if you want to capture the whole desktop.

**Comment by Masterwolf2050** [comment]
yes it depends on what your recording with. If you are using OBS you will need to set up a window capture and then select [LiveSplit.exe]: LiveSplit as the window you want to capture. I tend to use BitBlt as my capture Method. Pleases let me know if this works for you

**Comment by Enasons** [comment]
> yes it depends on what your recording with. If you are using OBS you will need to set up a window capture and then select [LiveSplit.exe]: LiveSplit as the window you want to capture. I tend to use BitBlt as my capture Method. Pleases let me know if this works for you

Yeah i downloaded OBS I was just using the built in recorder that didnt capture the other windows. Problem is resolved now.
