### ISSUE TITLE
Livesplit Keeps Crashing When I Open the Game I am Speedrunning

### ISSUE THREAD

**Issue by BandobrasTook** [LiveSplit/LiveSplit#2073]
Every time I open the game I am speedrunning (Dark Souls: Remastered), livesplit stops working, and than closes. I have no idea as to why this is happening, but it only has happened when the game is open. Does anyone have any ideas whatsoever? Thank you.

**Comment by just-ero** [comment]
Closing as stale.

I believe this was caused by the autosplitter for the game at the time.
