### ISSUE TITLE
Timer red even though I´m ahead of PB

### ISSUE THREAD

**Issue by KamiRyu37** [LiveSplit/LiveSplit#2074]
Hi all,

I made a small example of my problem:

as seen in the screenshot my timer is red even though I´m still ahead of my PB.

I have the standard Color configuration (except for background)

When I was over a Minute ahead the Color was dark green. Once I was beneath 57.8 it changed to light green as expected because I lost time but am still ahead. But at around -30 it suddenly changes to red.

Can someone explain this to me?

![Livesplit](https://user-images.githubusercontent.com/71383898/104807989-59c1d500-57e3-11eb-8252-16f9e59e7c60.png)

**Comment by SquareMan** [comment]
Right click on livesplit and look at "Compare Against". It's likely that you have selected Best Segments there, but in your layout set your splits to compare against PB instead of "Active Comparison"

**Comment by KamiRyu37** [comment]
Damn that was easy. Thank you very much =)
