### ISSUE TITLE
Automatic updating of Components seems to be broken

### ISSUE THREAD

**Issue by kugelrund** [LiveSplit/LiveSplit#2084]
It seems like the `UpdateManager.exe` that is [downloaded from the LiveSplit website](https://github.com/LiveSplit/LiveSplit/blob/c913ce59c95a4db91942b9f58b66f88d71ae96e8/LiveSplit/UpdateManager/Updater.cs#L172) is broken at the moment. Custom components seem to not be updated properly anymore. The prompt "do you want to update" shows, and when confirming it looks like it is performing the update. But then after LiveSplit restarts, no file was actually replaced and the "do you want to update" prompt shows again. Even manually running the `UpdateManager.exe` with the correct arguments from the command line does not work with the downloaded version.

However if I compile the `UpdateManager.exe` by myself by changing the build type of the `UpdateManager` project from Class Library to Windows Application, the resulting binary will do the update properly. So the specific executable on the LiveSplit website seems to be at fault? Not sure how I could debug that.

**Comment by SuiMachine** [comment]
Just gonna rack it up, that it's not an isolated issue and I also have it. 🦀

**Comment by kugelrund** [comment]
Appears to be fixed now, thanks @wooferzfg
