### ISSUE TITLE
Fullscreen LiveSplit issues

### ISSUE THREAD

**Issue by PortBerry** [LiveSplit/LiveSplit#2086]
For some reason, I can't have a fullscreened game and use LiveSplit at the same time; I am very new to SplitLive, so I don't know exactly what to do.
I have always on top activated, so I don't know whats wrong.
Help is definetly appreciated.
Thank you

**Comment by just-ero** [comment]
Closing as unrelated.

No application can be displayed on top of a full screen game. This is not an issue with LiveSplit.
