### ISSUE TITLE
I cant add splits 

### ISSUE THREAD

**Issue by ethan123456789055** [LiveSplit/LiveSplit#2088]
![image](https://user-images.githubusercontent.com/78610533/107060983-9d39ae80-67a5-11eb-88f1-423400293340.png)
I cant add splits and also clicking the split button does nothing the only thing i can do is add comparisons and make 1 split which is the already set split.

**Comment by henyK** [comment]
Is your timer running? You can't modify the amount of splits while a run is in progress.

**Comment by ethan123456789055** [comment]
No it’s not, I just entered the split menu before I started the timer

**Comment by ethan123456789055** [comment]
Nvm I guess it was sorry

**Comment by ThatsNasu** [comment]
if its indeed solved, i would mark this as done and hereby request to close this issue c:

**Comment by LukeSaward1** [comment]
> if its indeed solved, i would mark this as done and hereby request to close this issue c:

Stop necroposting old issues and especially ones which have been resolved.

**Comment by ThatsNasu** [comment]
Exactly. stumbled upon some open issues which are somewhoat obviously resolved but still marked open, so i thought i hop in and either try to resolve the issue, or just ask for closing the issue. sorry if my interest in cleaning up dead issue lists is not welcome here. wont do it again

**Comment by DarkRTA** [comment]
> Exactly. stumbled upon some open issues which are somewhoat obviously resolved but still marked open, so i thought i hop in and either try to resolve the issue, or just ask for closing the issue. sorry if my interest in cleaning up dead issue lists is not welcome here. wont do it again

It is more than welcome here. The other guy was just being rude for no reason.

**Comment by ThatsNasu** [comment]
oh, i interpreted the "Please dont do this again" as meant for me, so i guess we ran into a missunderstanding here c: anyways, to just finish this up and let this issue rest in peace, imma dip out and see if i can find some other issues to either resolve or request a close if appropiate.
