### ISSUE TITLE
Port to Mono for Linux support

### ISSUE THREAD

**Issue by lewisje** [LiveSplit/LiveSplit#209]
I don't know whether anyone else has asked for it (checking both open and closed issue titles indicates "no"), but it would be nice for LiveSplit to also be available on Linux.

**Comment by CryZe** [comment]
Yeah, a lot of people asked for this and we'll implement it at some point.

**Comment by Drenn1** [comment]
Also hoping for this to get done, it'll make livesplit the definitive speedrunning timer. I made a token effort to get it to run under monodevelop, though it's clear that Livesplit depends heavily on windows stuff for now. I'm rather amazed I got it to compile at all, though it doesn't get very far. Seems like the gdi stuff would need to be rewritten. Not sure if I want to get into that, unfamiliar as I am with the sources.

**Comment by Gotos** [comment]
While LiveSplit works fine with Wine, global hotkeys don't, which is a major problem when trying to run a games whos window needs the focus. Therefore, I'd really love to see a linux version of LiveSplit!

**Comment by Drenn1** [comment]
Since I didn't pursue the path of a native port myself I looked up a workaround for global hotkeys. It uses xdotool and xbindkeys to get the job done.

https://gist.github.com/Drenn1/b9bb3b5c888b7a3a1045

**Comment by CodingKoopa** [comment]
Is there any kind of ETA on this? Llanfair's domain has now expired, and is no longer being worked on it seems, so we're in desparate need of a Linux speedrunning timer. Appologies if these kinds of comments are discouraged, but I don't see any kind of discussion forum, issue, or project for the cross-platform rewrite.

**Comment by wooferzfg** [comment]
We are working on this instead: https://github.com/CryZe/LiveSplitOne
