### ISSUE TITLE
"CTRL+Z" Current Personal Best

### ISSUE THREAD

**Issue by eltharynd** [LiveSplit/LiveSplit#2103]
I'm sorry if this has been asked and closed before, i tried searching but there's too many results for PB..,.

So it would be nice to save two Personal Bests so that if you accidentally Save a longer run with gold segments you don't have to mess with the file but can just go back.

What do you guys think?

**Comment by just-ero** [comment]
It is hard to imagine one going through all the steps it takes to manually save a slower run *and* overwrite the old splits file and then realizing that it was a mistake. LiveSplit cannot be expected to fix such a deliberate action.
