### ISSUE TITLE
Livesplit crashing on joining racetime.gg session

### ISSUE THREAD

**Issue by enrospv** [LiveSplit/LiveSplit#2109]
- I downloaded latest version of LiveSplit early March
- Whenever I click to join a racetime.gg session, LiveSplit crashes (Not too many details, as shown in screenshot)
- Yes, it includes DarkUI.dll (RE: issue 2060)
- OS: Windows 7
- Shell: Litestep (Although, tried with Explorer as shell, crashed then as well)

Have custom UXtheme if that makes a difference
Latest as in 1.8.15

![crash image](https://cdn.discordapp.com/attachments/342012051339739136/826560759772872784/unknown.png)

**Comment by Evan-Skye** [comment]
Same issue here, also Windows 7. No custom UX skin, opening in VS with "Debug this Program" reveals a StackOverflowException. Pls fix if possible.

![image](https://user-images.githubusercontent.com/22407114/120117475-5a885180-c15b-11eb-93a9-b1a91621e324.png)
![image](https://user-images.githubusercontent.com/22407114/120117481-62e08c80-c15b-11eb-9d0e-81649c2591d1.png)
![image](https://user-images.githubusercontent.com/22407114/120117485-67a54080-c15b-11eb-9cf3-343e8aedafba.png)

**Comment by just-ero** [comment]
Does this issue persist in the most recent stable version of LiveSplit?

**Comment by wooferzfg** [comment]
This is using the old Racetime integration. We can close this.
