### ISSUE TITLE
Parse Splitty Splits

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#211]
https://github.com/ylorant/splitty

**Comment by Seldszar** [comment]
What is the best option for you:
- Recognize automatically and parse it when the user open from a file? (**Open Splits**, **From File...**)
- Add a new option in **Open Splits** menu

**Comment by wooferzfg1** [comment]
Cryze already implemented it in a separate branch on his fork so don't worry about it

**Comment by CryZe** [comment]
And it's already merged. Looks like auto closing and auto ready don't work when I work on my fork, so I might not want to do that anymore.
