### ISSUE TITLE
Current comparison showing previous segment delta?

### ISSUE THREAD

**Issue by paintskate8** [LiveSplit/LiveSplit#2121]
I noticed that what would normally show the delta for the current comparison (whether it be PB, golds, average, whatever), it would ONLY show the delta for the previous segment.
An image example:
If i split here, i should be around 30 seconds behind: https://cdn.discordapp.com/attachments/829799573475688448/838206514979668028/unknown.png
But after i split, i'm 37 seconds "ahead", which is the same amount of time I saved on that segment, as you can see on the bottom: 
https://cdn.discordapp.com/attachments/829799573475688448/838206541072695347/unknown.png

I reinstalled an old version and it was back to normal.

**Comment by just-ero** [comment]
Has this problem been resolved? It looks to me that a faulty layout configuration could be the cause of this. Unfortunately, the images are no longer available.

Closing as stale for now.
