### ISSUE TITLE
Livesplit "Open Splits" option unable to recognize some .lss files as splits

### ISSUE THREAD

**Issue by michaelihorwitz** [LiveSplit/LiveSplit#2122]
I went to go open a .lss file from about 3 months ago (3/8/21 if you want an exact date) through the "Open Splits" menu and LiveSplit told me "The selected file was not recognized as a splits file." However, upon going to the folder and double-clicking on the .lss file in question, the splits opened just fine. However, that did not fix the problem, and attempting to open it from the "Open Splits" menu still doesn't work, despite the fact that I already have the file open.

**Comment by CryZe** [comment]
Can you send / attach the file(s) in question?

**Comment by michaelihorwitz** [comment]
I seem to have figured it out, now that I look at the file names. Both of them were since renamed, but the names did not change in the splits menu so attempting to open them failed.
________________________________
