### ISSUE TITLE
LiveSplit needs a Linux version! (NOT ON WEB!)

### ISSUE THREAD

**Issue by cgaldieri** [LiveSplit/LiveSplit#2127]
I KNOW I KNOW!

LiveSplit on web is not too good! it is a little bit confusing!
Why the creators of LiveSplit already made a Flatpak version or even a snap version!
What i mean by that is about to expand the community of LiveSplit!

**Comment by ewe2** [comment]
To be a little more coherent, why isn't Livesplit Mono-compatible? Currently it's too dependent on kernel32 code and crashes with unknown assembly errors. Without this tool, speedrunning is difficult to verify on non-Windows platforms. Please consider cross-platform options.

**Comment by DarkRTA** [comment]
This is currently being worked on in the form of a native port of LiveSplit One. I have no idea when it'll be ready for public usage.

**Comment by CryZe** [comment]
There is an OBS plugin that works on Windows, Linux and macOS: https://github.com/CryZe/obs-livesplit-one

Make sure to get version 0.0.4 though, as the other version is currently broken: https://github.com/CryZe/obs-livesplit-one/releases/tag/v0.0.4

**Comment by iMonZ** [comment]
LiveSplit with MAUI would be great ones it comes out!
macOS (Intel + Silicon), WinUI3 (Windows 7 - Windows 11) and Linux (with Wayland and optionally with X)

**Comment by bboudreaux28** [comment]
In the meantime, running live split with wine (+ .net framework on the prefix) works well

**Comment by Vresod** [comment]
necroposting but has there been any development on this?

**Comment by davidak** [comment]
@cgaldieri what is the reason for closing this? Is there a native linux version now? That would still be useful.

**Comment by wooferzfg** [comment]
There's a Linux version in progress:
- https://github.com/LiveSplit/LiveSplitOne
- https://github.com/LiveSplit/obs-livesplit-one
- https://github.com/LiveSplit/livesplit-core

**Comment by CryZe** [comment]
The releases here are the closest to a full desktop version atm: https://github.com/CryZe/livesplit-one-druid/releases/tag/v0.1.0

**Comment by Vresod** [comment]
If all of them are in progress, then this shouldn't have been closed as Completed?

**Comment by wooferzfg** [comment]
Those projects are not directly related to this repo. LiveSplit One is a rewrite of LiveSplit, and we have no plans to port the original LiveSplit to Linux.

**Comment by DrakeWhu** [comment]
Any reasons on why you would not make a Linux version? Or is it just a huge middle finger to the whole open source community? I can't understand it

**Comment by stacyharper** [comment]
(fwiw I have done a similar program for linux https://git.sr.ht/~stacyharper/splitter)
