### ISSUE TITLE
"Add Comparison" Splits Being Overwritten

### ISSUE THREAD

**Issue by b-Liebenauer** [LiveSplit/LiveSplit#2129]
I am trying to manually add in the segments time for the World Record on KATANA Zero. The problem is that on certain segments, the time I input will be overwritten by a time I inputted on a previous segment. This only happens for certain segments, not on all of them (i.e. segment 3 time only overwrites segment 4 time, all other segments are fine).
  
![LiveSplit Problem After](https://user-images.githubusercontent.com/84261011/118386534-15561280-b5e6-11eb-8985-ed24d226f4e9.PNG) 
In this picture, I am in the middle of typing in the segment.

![LiveSplit Problem After](https://user-images.githubusercontent.com/84261011/118386552-39195880-b5e6-11eb-9a20-7db7fe08278a.PNG)
This is what happens after I hit enter or click off of the segment I am typing in.

Any help is appreciated.

**Comment by zpellman** [comment]
I'm seeing this issue as well in 1.8.21 and 1.8.20

**Comment by CryZe** [comment]
The comparisons are split times, not segment times.

**Comment by zpellman** [comment]
Sorry, I'm new to LiveSplit. But what does that mean? I clicked Add Comparison to add splits from someone else, and similar to what @b-Liebenauer described, after the third or fourth split, it wouldn't accept the time I entered - it would get set to the previous split's time.

**Comment by CryZe** [comment]
A "split time" is the time it took from the beginning of the run to get to this point. A "segment time" is the time it took for this individual segment. Split times have to be increasing otherwise they are not split times.

**Comment by zpellman** [comment]
Ahhh, I think I got it now. So if I have three segments that take 1 minute each, my splits for those segments need to be "1:00", "2:00", and "3:00", correct? Thanks!

**Comment by CryZe** [comment]
Exactly
