### ISSUE TITLE
Manual Game Time no longer an option.

### ISSUE THREAD

**Issue by Sonikkustar** [LiveSplit/LiveSplit#2132]
Using the latest version (1.8.16) as of writing. The option to manually input your times for splits under your split layout no longer shows up. Others I know have the same issue.

I downloaded from the LiveSplit website, so I'm not sure if there's a difference between there and on GitHub here.

![image](https://user-images.githubusercontent.com/22226938/119210544-ad3a7d00-ba7a-11eb-9256-f53552428b2d.png)

**Comment by TheBoxyBear** [comment]
Updated to 1.18 and the option is here for me.

**Comment by just-ero** [comment]
This issue appears to be resolved.
