### ISSUE TITLE
My issue with downloading

### ISSUE THREAD

**Issue by EJgithubyo** [LiveSplit/LiveSplit#2140]
For some reason, whenever I try to download LiveSplit, the LiveSplit.exe file doesn't exist.

**Comment by gmjosack** [comment]
How are you downloading it? From here: https://github.com/LiveSplit/LiveSplit/releases?

**Comment by EJgithubyo** [comment]
no I downloaded it from the LiveSplit website. maybe this one will work

**Comment by EJgithubyo** [comment]
oops accidentally closed the issue! the .exe file still isn't showing up.

**Comment by gmjosack** [comment]
I'd check if you have an anti virus that's removing it or something. The exe is definitely in the zip...
