### ISSUE TITLE
Constantly Increasing User Objects Until Crash

### ISSUE THREAD

**Issue by GPSolo** [LiveSplit/LiveSplit#2142]
I found out about this problem when I installed and begun making my livesplit settings when it randomly crashed with this error, so I looked it up, found nothing and figured out that it was because of User Objects exceeding and crashing the application. 
![Screenshot 2021-06-22 234127](https://user-images.githubusercontent.com/44757793/123042160-9d80c200-d3b3-11eb-9b3f-065e9ab8a838.png)
Here is a Screenshot just to prove the high levels of User Objects, if you know anything about this problem, please write back to me. LiveSplit Version is 1.8.16 (latest)

**Comment by GPSolo** [comment]
I figured out that it was some sort of installed application on my pc, so I uninstalled a lot of random apps then it fixed livesplit.

**Comment by dsloan4** [comment]
shouldn't have closed the issue. I don't have 'a lot of random apps' to uninstall and am getting the same problem
