### ISSUE TITLE
In-game time is extremely inaccurate

### ISSUE THREAD

**Issue by Retartist** [LiveSplit/LiveSplit#2144]
I've noticed while speedrunning My Friend Pedro that the in-game timer on livesplit is extremely inaccurate. I raised it with the maintainer of the autosplitter and they found and provided a workaround for a different issue (that the timer doesn't pause at right times), but that was not the issue. If you watch the attached video, you can see that over the course of level 1, livesplit differs by the in game timer by **4.27 seconds!** (Or 4.19-4.26 seconds accounting for errors at the beginning of the level) and i've checked the in-game timer and it's bang-on accurate. By the end of a roughly 12 min run, livesplit is fast by **over 1 minute**. 
I've checked and real-time is still accurate in livesplit and while it isn't in the video, my real time wasn't a PB for that run whilst IGT PB'd by a long time. 

https://www.youtube.com/watch?v=WCeuOYLhz7M

**Comment by just-ero** [comment]
This issue does not have anything to do with LiveSplit's functionality and can be closed.

If the problem still exists, open an issue on the repository of the autosplitter instead: https://github.com/just-ero/LiveSplit.MyFriendPedro.
