### ISSUE TITLE
Doesn’t load on any IPhone model 

### ISSUE THREAD

**Issue by philipbower122** [LiveSplit/LiveSplit#2164]
Doesn’t load on any IPhone model even those with the extra large screens

**Comment by philipbower122** [comment]
I’m on IPhone 6S it will only go up to IOS 12.5.4

**Comment by CryZe** [comment]
That's not true. iPhone 6S can install even iOS 15

**Comment by philipbower122** [comment]
How?? It says there is no update available.

**Comment by CryZe** [comment]
You may potentially be on an iPhone 6 of 6 Plus then:

![https://i.imgur.com/aFyU8Nt.png](https://i.imgur.com/aFyU8Nt.png)

**Comment by philipbower122** [comment]
Yeah a 6 Plus. So won’t it work. They should Ben compatibility as An iPad
at iOS 7.8 from years ago works on it as I asked my friend

**Comment by just-ero** [comment]
LiveSplit is not available on any operating system besides Windows. The issue is not relevant to the repository.
