### ISSUE TITLE
Instructions Video for "Minecraft: Java Edition - Component Settings" is unavailable 

### ISSUE THREAD

**Issue by Kinomora** [LiveSplit/LiveSplit#2168]
Steps to reproduce:
Set game to Minecraft: Java Edition
Click Activate
Click Settings
In the Components Settings window click "INSTRUCTIONS AND FAQ, PLEASE WATCH"
Video is private
![image](https://user-images.githubusercontent.com/9062578/132780011-83d881f8-69e0-437a-bb07-2eb6fa76559d.png)

**Comment by just-ero** [comment]
Closing as unrelated.

Please report issues with autosplitters in their respective repositories or communities.  
The Minecraft community recommends usage of the (SpeedRunIGT mod)[https://redlime.github.io/SpeedRunIGT] today.
