### ISSUE TITLE
Game Time error

### ISSUE THREAD

**Issue by HlamPhoneAung** [LiveSplit/LiveSplit#2169]
can someone help me why is this keep happening? game time changes automatically I've been reinstalling it like 3times plz someone help:"") I put the game correctly Minecraft: Java Edition I activate it. It still showing that time

https://user-images.githubusercontent.com/90708197/133282468-1837e50a-8b3c-4678-bf1f-55e464f4763e.mp4

**Comment by just-ero** [comment]
Closing as unrelated.

Please report issues with autosplitters in their respective repositories or communities.  
The Minecraft community recommends usage of the (SpeedRunIGT mod)[https://redlime.github.io/SpeedRunIGT] today.
