### ISSUE TITLE
Splitting replaces SoB column with current run split time

### ISSUE THREAD

**Issue by ghost** [LiveSplit/LiveSplit#2174]
I use 3 columns for my runs, +/-, Personal Best, and Sum of Best. When doing runs, whenever I do a split, it replaces the SoB time with the current split time. By the end of the run, the PB and SoB times match. I don't want them to do this. What am I doing wrong?

**Comment by just-ero** [comment]
Is it even possible to have a column for "sum of best"? Is the column actually set to the correct comparison?
