### ISSUE TITLE
Layout file from another user doesn't open

### ISSUE THREAD

**Issue by KeybladeBrett** [LiveSplit/LiveSplit#2180]
It appears to show up with an error message that states "The selected file was not recognized as a layout file. (LiveSplit.Server.dll could not be found)" This is a .lsl file that I try to import and it just doesn't work 😢

**Comment by Derpspace** [comment]
You need to download the livesplit server component (https://github.com/LiveSplit/LiveSplit.Server/releases) and put it into the components folder

**Comment by just-ero** [comment]
This issue appears to have been resolved.
