### ISSUE TITLE
Unable to load the native livesplit-core library

### ISSUE THREAD

**Issue by chines35** [LiveSplit/LiveSplit#2187]
I have used livesplit on my other computer, but when I installed it on my second computer, this pops up and it won't launch.
<img width="610" alt="Screenshot 2021-12-04 021117" src="https://user-images.githubusercontent.com/95522635/144702720-c3fe29d4-97f3-401d-adc0-80ec24a4f753.png">

**Comment by wooferzfg** [comment]
Could you try this build and let me know if it opens for you on the computer where you were having issues? https://github.com/LiveSplit/LiveSplit/suites/4554180818/artifacts/122305141

**Comment by chines35** [comment]
That build works. Thank you!_
