### ISSUE TITLE
Unable to use of LiveSplit due to technical difficulties

### ISSUE THREAD

**Issue by razorawr** [LiveSplit/LiveSplit#2188]
right click > edit splits > game name, input "Minecraft: Java Edition" > IGT is available > activate (cannot press settings) > dialogue box appears showing, "Couldn't find the Minecraft world save". > forever stuck to that dialogue box until its closed with task manager. I do not know the folder its assigned to because I accidentally double clicked to it, but I know its not a Minecraft world save folder which is bad. I tried to delete and download, did not work, and cannot even access settings to change directory, pls help I want to speedrun.

**Comment by Nice-Creativity** [comment]
Hey There! Don't worry I have the solution to that. First go to the "Edit splits" by right clicking on the timer, then go activate the timer in the splits editor. Then click on "settings" button and then a new window should appear called component settings. Then click the "reset saves location" button and there u go it should work now.

**Comment by just-ero** [comment]
Closing as unrelated.

Please report issues with autosplitters in their respective repositories or communities.  
The Minecraft community recommends usage of the (SpeedRunIGT mod)[https://redlime.github.io/SpeedRunIGT] today.
