### ISSUE TITLE
Build Versions

### ISSUE THREAD

**Issue by ROMaster2** [LiveSplit/LiveSplit#219]
Could we use something other than 13.3.7-debug to know what the build is? I'm all for dank memes, but it'd be good to know what build version it is, at least the beta thereof. Like right now anything built after the 1.5.5 release could be 1.5.5-debug or something similar.

**Comment by CryZe** [comment]
You need to have git in your Path environment variable. Then you will have a full on version. It's 1.5.5-235-debug at the moment for example.

**Comment by ROMaster2** [comment]
Okay I see now, didn't know that before.
