### ISSUE TITLE
[Feature request] Save paused timer and continue later

### ISSUE THREAD

**Issue by daanbom** [LiveSplit/LiveSplit#2197]
Hey, I am a streamer and I often do fun challenges for games like Dark souls. Here is use livesplit over multiple  streams and I would like to use splits and keep the timer when I start playing the next day. Can u guys make a function like this for me that would be greatly appreciated

**Comment by TheBoxyBear** [comment]
I wanted the same feature so looking into implementing it myself. Not sure if I can match the standards to be merge into master however.

**Comment by amcknight** [comment]
Did you have any luck with this @TheBoxyBear ?

**Comment by TheBoxyBear** [comment]
> Did you have any luck with this @TheBoxyBear ?

Unfortunately, no. I can't even get master to compile.

**Comment by Shotnex4** [comment]
Hey everyone, I also missed this feature.
I developed a LiveSplit Component which you can use to save your progress mid run to a file. With that you can close LiveSplit and even shutdown your PC. Just import the file when you are back and you can continue:
https://github.com/Shotnex4/LiveSplit.TimeAttackPause

**Comment by just-ero** [comment]
Closing as duplicate of #952.
