### ISSUE TITLE
Cannot Change Most Layout Settings (1.8.18)

### ISSUE THREAD

**Issue by mistrdew** [LiveSplit/LiveSplit#2201]
User "Sealio22" made a post about this back in October of 2020, which got no replies. There is an issue I've been experiencing with Livesplit since I've downloaded it that gives me "Unhandled exception" errors every time I open the program:

"Unhandled exception occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.
"Could not load file or assembly 'Microsoft.WindowsAPICodePack.Shell, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified."

I'm still able to run Livesplit despite this, but I've found a very similar error directly inhibits my ability to use the program. When I use the "Edit Layout" -> "Layout Settings" screen, if I try to do things like change the timer font, colors, etc., a new error occurs that stops me. Check boxes and dropdown menus still work. Here is the error for changing the font specifically:

"Unhandled exception occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.
"Could not load file or assembly 'CustomFontDialog, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified."

It's very similar to the original error, but unlike the original, it makes it impossible to edit the font, color, etc. Please help if possible! I'd love to change these settings.

**Comment by ImmortalMax8294** [comment]
I have the same issue

**Comment by wooferzfg** [comment]
Please make sure your virus scanner isn't removing any files. That DLL is included when you download LiveSplit.

**Comment by mistrdew** [comment]
Redownloading worked, so it's probably the virus scanner issue. Thank you!

**Comment by just-ero** [comment]
This issue appears to be resolved and can be closed.
