### ISSUE TITLE
{Feature Request} Linux Binary

### ISSUE THREAD

**Issue by gitdrug** [LiveSplit/LiveSplit#2204]
A Linux Binary would be cool but i don't know is this app uses like win32 or some other windows only API so i don't even know if you guys could port it to Linux.

**Comment by ryleu** [comment]
I'm going to try running it through WINE. We'll see how it goes. I'll try a Linux x64 build first, though .NET on Linux can be gross.

**Comment by CryZe** [comment]
The original LiveSplit will not natively support Linux. LiveSplit One however will. There's an early version here (it only shows the timer, it doesn't have any menus for configuring, instead you configure it through a config file): https://github.com/CryZe/livesplit-one-desktop
