### ISSUE TITLE
Legacy Twitch API v5 Shutdown on February 28, 2022

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#2218]
Hello,

We are reaching out as we have identified that your application(s) below have made requests to v5 API endpoints in January and may be affected by the upcoming shutdown if further action is not taken.

LiveSplit ([REDACTED])
GET /kraken, GET /kraken/search/games

On February 7, 2022, we initiated the first temporary outage in preparation for the final service shutdown on February 28, 2022. In order to not be affected by these outages or the shutdown, you will need to migrate to the latest Twitch API endpoints or remove functionality that will no longer be available. To help with the transition, we have provided a [migration guide](https://dev.twitch.tv/docs/api/migration) with endpoint and scope equivalencies.

If you have any questions regarding your migration to the latest version of the Twitch API, please feel free to chat with the community on the [TwitchDev Discord server](https://link.twitch.tv/devchat) or post on the [developer forums](https://discuss.dev.twitch.tv/).

If you develop Twitch Extensions, make sure to read [How Extensions are affected by the Legacy Twitch API v5 shutdown](https://discuss.dev.twitch.tv/t/how-extensions-are-affected-by-the-legacy-twitch-api-v5-shutdown/32708) and that your API URLs have been updated from “https://api.twitch.tv/extensions/” to “https://api.twitch.tv/helix/extensions/”.

Please refer to the [latest forum announcement](https://discuss.dev.twitch.tv/t/legacy-twitch-api-v5-i-e-kraken-shutdown-reminder-february-28-2022/36589?u=jbulava) for the phased shutdown schedule or the [Legacy Twitch API v5 shutdown announcement](https://blog.twitch.tv/en/2021/07/15/legacy-twitch-api-v5-shutdown-details-and-timeline/) for full details.

We understand this has been a big shift. The latest version of the Twitch API allows for new features and functionality to be added for third-party developers as Twitch grows and evolves. We look forward to the moments when third-party applications provide unique interactive experiences for viewers and creators, and we appreciate all your work to enhance the Twitch community.

**Comment by wooferzfg** [comment]
I [started working on this](https://github.com/LiveSplit/LiveSplit/tree/update-twitch), but I noticed that sharing to Twitch already seems to be broken if you're not logged in because the OAuth form doesn't load in our embedded web browser. I'm not sure how we can get around that.
