### ISSUE TITLE
Counter hotkeys not saving

### ISSUE THREAD

**Issue by AaronZ101** [LiveSplit/LiveSplit#2224]
A few years ago this layout worked (I've even tried making a new layout from scratch and it has the same issue). So I have two counters (one for melee kills one for shooting kills), my hotkeys are Numpad 1 and Numpad 2 for incrementing respectively, these work however I have Numpad Add to reset the counters, this will not work, I also use Numpad Add to reset livesplit timer, no sure if its conflicting, but it never used to. The weird thing is when I go to edit the Counters in layout the hotkeys are randomised after closing/reopening livesplit.

This is how I set my hotkeys (and save the layout):

![image](https://user-images.githubusercontent.com/43587018/153725451-645d1ce4-91dc-4013-83c0-e8d046cfaee6.png)

But upon closing and reopening livesplit and checking these once again, it becomes this:

![image](https://user-images.githubusercontent.com/43587018/153725486-bd4c6bbf-c344-4223-abd8-754653375701.png)

Even opening the layout in notepad to check the hotkeys there they are properly set, so livesplit is doing something wacky when opening the layout file. Like I said it used to work fine but I haven't ran this category in like 3 years so not sure when this got broken.

Layout File:
[SH1_10Star.zip](https://github.com/LiveSplit/LiveSplit/files/8054360/SH1_10Star.zip)

**Comment by wooferzfg** [comment]
In my testing, the hotkey settings do persist, but they just don't show up properly when editing the Counter component's settings again after opening the layout.

**Comment by AaronZ101** [comment]
Yeah the increment hotkey does still work but reset (Numpad Add) doesn't. Not sure if because I have Numpad Add tied to both resetting the counters and timer though. Even if I set NumPad Add and test it without closing livesplit it doesn't work at all.
