### ISSUE TITLE
my IGT isnt working

### ISSUE THREAD

**Issue by antoni54321** [LiveSplit/LiveSplit#2227]
So i want to speedrun minecraft SSG category, real time is working but igt isn't. i clicked activate next to "made by someone" and its still not working can someone please help?

**Comment by LukeSaward1** [comment]
Use the SpeedrunIGT mod, it's much better.

**Comment by just-ero** [comment]
Closing as unrelated.

Please report issues with autosplitters in their respective repositories or communities.  
The Minecraft community recommends usage of the (SpeedRunIGT mod)[https://redlime.github.io/SpeedRunIGT] today.
