### ISSUE TITLE
LiveSplit Not Showing Over Games

### ISSUE THREAD

**Issue by Makerrrr17** [LiveSplit/LiveSplit#2232]
I was using livesplit and noticed that it doesn't show over games when I am in fullscreen. I have tried EVERYTHING. The always on top option doesn't work. Does anybody have a fix to this?

**Comment by mleise** [comment]
Yes, just last week I wrote a [LiveSplit Overlay for ReShade](https://github.com/mleise/livesplit_overlay)!
All you need is a bare bones install of ReShade 5.1.x for your game.

**Comment by Makerrrr17** [comment]
Alright. Thanks a lot! :)

**Comment by just-ero** [comment]
Closing as unrelated.

No application can be displayed on top of a full screen game. This is not an issue with LiveSplit.
