### ISSUE TITLE
The timer does not start

### ISSUE THREAD

**Issue by Dinosaurleader101** [LiveSplit/LiveSplit#2233]
I am new to livesplit and could not get the timer to start so I searched all throughout youtube but could not find a fix

The problem more specifically would be when I open start the timer it acts like it has started (for example I can still split and the what not) but the timer does not go up from 0.00

**Comment by Denikkon** [comment]
I have the same issue, it acknowledges it as a run but the timer is just stuck at 0.00. It used to work yesterday, now it just refuses to start

**Comment by yeetslaps229** [comment]
I found the answer, i dont know what causes the problem but to fix it you must delete all versions of livesplit you currently have and re install it. Worked well for me

**Comment by just-ero** [comment]
Can this issue be closed due to inactivity?

I'm not really sure what would cause this. An autosplitter that sets the game time to 0.00?

Cc @wooferzfg

**Comment by wooferzfg** [comment]
It sounds like the timer component crashed or something. Not sure
