### ISSUE TITLE
cant download livesplit

### ISSUE THREAD

**Issue by wadguvsvdsRFv** [LiveSplit/LiveSplit#2234]
whenever i try download livesplit timer for speedrunning it shows a document file icon and doesnt properly download   please i want to do speedruns but this is the only timer i know

**Comment by wooferzfg** [comment]
You need to extract the files in the ZIP archive you downloaded.

**Comment by just-ero** [comment]
Can this issue be closed due to inactivity?

The problem appears to have been lack of knowledge about how to use ZIP archives.

Cc @wooferzfg
