### ISSUE TITLE
Portal 2 autosplitter not starting

### ISSUE THREAD

**Issue by Lassilos** [LiveSplit/LiveSplit#2244]

**Comment by JaioCG** [comment]
Please watch the Portal 2 Speedrun Setup Guide to get the rest of the game set up, as the autosplitter we use is handled by a community made plugin you need to install into Portal 2.

[https://www.youtube.com/watch?v=fnFenfXjrtg](https://www.youtube.com/watch?v=fnFenfXjrtg)
