### ISSUE TITLE
Cannot load splits file when using self-compiled livesplit-core.dll

### ISSUE THREAD

**Issue by haktical** [LiveSplit/LiveSplit#2249]
I am experimenting with adding a LiveSplit feature - mostly for self-use - which requires tweaks to the livesplit-core image shrinking. However, when I compile livesplit-core.dll from [LiveSplit/livesplit-core](https://github.com/LiveSplit/livesplit-core), and then build LiveSplit with this dll, I am unable to load a splits file with the error "The selected file was not recognized as a splits file."

Digging into the issue, it seems the addition of the feature to have a custom Run Layout (added in Jun/Jul 2021) requires functionality which is not available in the main livesplit-core repo. This can be seen, as an example, in LiveSplitCore.cs where "Run_layout_path" is imported from the livesplit_core DLL, however, no Run_layout_path exists in the "official" version of livesplit-core. At one point I thought I was actually getting a compilation error - something about "no entry point" for this function - however I cannot reproduce this now (maybe due to other changes I have made).

The result is that compiling LiveSplit becomes near-useless unless the included livesplit-core.dll is specifically used. Is it intended that LiveSplit cannot function properly when compiling your own livesplit-core.dll from the official repo?

**Comment by CryZe** [comment]
Yeah it's a little weird. Basically woofer accidentally released a new version of LiveSplit that included this feature without us ever merging that Pull Request. I guess I'll try to prioritize actually merging it.

**Comment by wooferzfg** [comment]
For reference, this is the commit that the LiveSplit repo used: https://github.com/LiveSplit/livesplit-core/pull/436/commits/89e51255edc1f648bf90b273ad3045de35704c98

**Comment by just-ero** [comment]
Might this be related to image types that aren't supported by LiveSplit?

Cc @CryZe

**Comment by CryZe** [comment]
Nah, this issue was basically LS accidentally diverging from lsc. This should be fixed by now.

**Comment by just-ero** [comment]
I think it would be appropriate to close this issue in that case.
