### ISSUE TITLE
Side mouse buttons do not work when setting up start-split

### ISSUE THREAD

**Issue by Yakivts** [LiveSplit/LiveSplit#2251]
Good afternoon, I found a problem, you can not assign the side buttons of the mouse, and previously you could do it. Help me solve this problem thank you!

**Comment by LimeShep** [comment]
Me too, also using older version like 1.8.15 helps but it has a new update button what i dont know how to disable WITHOUT installing new update

**Comment by BrainStone** [comment]
Having the same issue.

**Comment by william98r** [comment]
Same

**Comment by just-ero** [comment]
Closing as duplicate of #1977.
