### ISSUE TITLE
Add linux support

### ISSUE THREAD

**Issue by matej118111** [LiveSplit/LiveSplit#2252]
This is common issue with alot of software, i don't want to use wine just to run this

**Comment by CryZe** [comment]
This is a duplicate of probably many issues as this point. We are working on a Linux version.

**Comment by CryZe** [comment]
There is a Tauri version of LiveSplit One, there is a Druid version, an OBS plugin and a Dioxus version that I'm currently working on. They all work on Linux. Also you can run the original LiveSplit through Wine.
