### ISSUE TITLE
The url provided is not a valid speedrun.com Run URL.

### ISSUE THREAD

**Issue by 0ember1** [LiveSplit/LiveSplit#2253]
So I set a World Record and wanted to display my run in LiveSplit, so it'll look like "World Record is 3:13.26 by me". I got to the Edit Splits, Additional Info, Associate with Speedrun.com and paste this run link: https://www.speedrun.com/ppt_c2/run/m33q41gm. This is a valid run link submitted and verified on speedrun.com, it also displays on the LiveSplit in "World Record" graph, but LiveSplit says "The url provided is not a valid speedrun.com Run URL." I tried removing www, putting other runs, putting youtube links, doesn't work. I also tried pasting my API key in "Submit Run" form so LiveSplit maybe recognizes me, still don't work. How to fix it?
![image](https://user-images.githubusercontent.com/71174607/174331988-03dd4e90-7de9-4a7d-9e23-e97921b3f2bb.png)

**Comment by wooferzfg** [comment]
Looks like Speedrun.com changed their API so that the "Links" response header no longer includes the run.
