### ISSUE TITLE
Video doesn't play in LiveSplit

### ISSUE THREAD

**Issue by 0ember1** [LiveSplit/LiveSplit#2254]
So I've set up the basic video to see side by side where I am at my pb, and when starting a run it just shows VLC icon, even tho my default player is LightAlloy and not VLC.
![image](https://user-images.githubusercontent.com/71174607/174457795-d44e6e39-1ff8-4ae5-8a6f-c18006f1df00.png)

**Comment by LukeSaward1** [comment]
You need a specific version of VLC for that to work. It's super old. Like very, very old.

**Comment by wooferzfg** [comment]
Resolved by https://github.com/LiveSplit/LiveSplit/pull/2291 to support VLC 3.0
