### ISSUE TITLE
split atmıyot

### ISSUE THREAD

**Issue by HusoKaya33** [LiveSplit/LiveSplit#2255]
speedrun yapmak istediğim oyunun saving noktalarına geldiğimde split atmıyor

**Comment by LukeSaward1** [comment]
'Global Kısayol Tuşları' açık mı? Eğer öyleyse, doğru tuşa basıyor musunuz?

**TRANSLATION**:
Is 'Global Hotkeys' turned on? If so, are you pressing the right key?

**Comment by just-ero** [comment]
Can this issue be closed due to inactivity?

The problem appears to have been that an autosplitter was not enabled or did not work.

Cc @wooferzfg
