### ISSUE TITLE
WR Component uses incorrect timing method

### ISSUE THREAD

**Issue by wooferzfg** [LiveSplit/LiveSplit#2258]
For https://www.speedrun.com/jfo#any_-_No_Fly, it uses Game Time to compare your PB to WR despite showing a Real Time time.

**Comment by badonyt** [comment]
go to livesplit, and right click and on compare against click "Compare against Game time" or something like that

**Comment by wooferzfg** [comment]
The main problem is that we use the game's ruleset to determine the timing method here: https://github.com/LiveSplit/LiveSplit.WorldRecord/blob/d92e655814202181b0638380f0bcfba1f6d03977/UI/Components/WorldRecordComponent.cs#L139

However, in some cases, the World Record time will not have a time for the default ruleset (for example, if the subcategory is RTA only, but the game's default is RTA without loads). In that case, we need to figure out the timing method of the WR time and use that.

**Comment by just-ero** [comment]
For clarifying reasons: is it not true that only runs that have a value in the field which is the leaderboard's main timing method can even be considered for WR?

Assuming the main timing method is game time:  
A run that has a 1:00 real time and no game time should be considered slower than a run that has a 2:00 real time but a 1:30 game time.

**Comment by wooferzfg** [comment]
In my comment above, I explained the issue here - the subcategory doesn't even support game time, but game time is the default for the game because you can't have a separate timing method as the default per category.

**Comment by wooferzfg** [comment]
Duplicate of https://github.com/LiveSplit/LiveSplit/issues/2474
