### ISSUE TITLE
IGT Not Working

### ISSUE THREAD

**Issue by Javatrix** [LiveSplit/LiveSplit#2262]
My in game time is not working, it still shows 0:00 even when i pause the game or the timer. I use seperated fabric installation for speedrunning, but i changed saves folder path in settings to my fabric saves. But it still doesn't work. Help me please
![lives](https://user-images.githubusercontent.com/108270039/177751597-c6b53f0e-1c85-4d67-9a33-21dd19480792.png)
![livesss](https://user-images.githubusercontent.com/108270039/177751619-2c85414b-9d1b-4ed6-9166-415eaa54aa99.png)
!

**Comment by LukeSaward1** [comment]
Use SpeedrunIGT mod, it's much better.

**Comment by Javatrix** [comment]
Hard to tell, I have switched OSes twice since then and I just use SpeedrunIGT now.
