### ISSUE TITLE
AutoSplittingRuntimeScript not found

### ISSUE THREAD

**Issue by Notchedd** [LiveSplit/LiveSplit#2279]
I am getting an error saying:

"LiveSplit has crashed due to the following reason:
Requested value 'AutoSplittingRuntimeScript' was not found."

I don't alter LiveSplit files besides messing with my splits. I do use LiveSplit in conjuction with AutoSplit64, and play on an emulator. Not sure if any of that information helps, but thought I'd toss it in. Please let me know if anyone has a fix.

**Comment by CryZe** [comment]
Can you update your LiveSplit still? If so try that. Otherwise you may need to redownload it.

**Comment by Notchedd** [comment]
> 

I cannot access the application at all. It will not open. I can try redownloading it, but no updating as far as I can see.

**Comment by CryZe** [comment]
I reverted the changes too, so you may be able to reopen it now / soon. But I'd recommend updating / redownloading anyway.

**Comment by Notchedd** [comment]
Without redownloading, it opened up immediately after this comment.
