### ISSUE TITLE
Forced fixed width on fonts for timer

### ISSUE THREAD

**Issue by ROMaster2** [LiveSplit/LiveSplit#228]
I'm not sure if this is possible without too much rewriting but I'll make note of it.

Using certain fonts for the timer make the size of it fluctuate like crazy. Having an option for force a fixed width on them would stop that; The width would probably be based on the largest number.

Not a top priority since other fonts have fixed widths.

**Comment by CryZe** [comment]
It already does that.

**Comment by wooferzfg1** [comment]
yeah, it already uses the size of the largest digit

**Comment by ROMaster2** [comment]
Not all of them do, look at the bottom left corner of this stream http://www.twitch.tv/grandstaryoshi/popout

**Comment by ROMaster2** [comment]
Okay, then someone made the mistake of mixing up WSplit and LiveSplit.
