### ISSUE TITLE
Newest update breaks deltas for games such as Sonic 1 and 2 (IGT)

### ISSUE THREAD

**Issue by noobguy57** [LiveSplit/LiveSplit#2282]
Hello, we use autosplitters for sonic 1 and 2 since it uses IGT, however the latest LiveSplit update is causing splits that would normally be displayed as +1 or -1 to be +.99 or -.99. This never happened before and when removing decimals, this causes the time to be shown as -0 which is incorrect. It worked in previous versions of LiveSplit but now it is broken like this. For reference, these games do not use decimal points, if you cross the sign at 0:23 and 54 frames, the 54 frames do not matter and it should be stored as 0:23.00.

**Comment by DarkRTA** [comment]
The recent update increased the precision at which times are stored in the splits file, meaning they are no longer capped at 3 decimal places and instead are stored to as many decimal places LiveSplit can handle. Your auto splitter was likely relying on the old behavior which was actually incorrect in the first place.

It may be helpful to upload a splits file so we can have a better idea of what's going on, as a time of exactly 23 seconds should still be stored as 23 seconds.

**Comment by Jujstme** [comment]
Sonic 1 and 2 autosplitters, at least the versions for the genesis emulators, should work with a "dumb" logic that just increases the timer by 1 every time the game's internal timer ticks at 1 second. Milliseconds are never even taken into consideration so the update should have no effect on the autosplitter 's behaviour.
Can you please provide more details or even an example to me and @beninswe ? Either here on in the SSC discord is good to go.

**Comment by noobguy57** [comment]
Hello, I gave you a tag in CSSC and provided some screenshots. I ended up downgrading and saving over my splits, not sure if that matters or not but if it does I can upgrade tomorrow and save my splits with the weird deltas. I provided some screenshot evidence of what it looked like for me in CSSC, I can upload them to an image hosting site and paste them here if needed as well tomorrow. @Jujstme

**Comment by Jujstme** [comment]
> The recent update increased the precision at which times are stored in the splits file, meaning they are no longer capped at 3 decimal places and instead are stored to as many decimal places LiveSplit can handle. Your auto splitter was likely relying on the old behavior which was actually incorrect in the first place.

The issue apparently is not in the time, but in how Livesplit shows the deltas.
Two people reported me this issue with 2 different autosplitters.
I will try replicating this myself later today.

**Comment by CryZe** [comment]
Unfortunately while we were able to fix the internal code in LiveSplit, many auto splitters are still affected by the problem. Though this might be unrelated.

**Comment by Jujstme** [comment]
To be fair, this doesn't seem to affect the actual times reported by livesplit. Only the deltas.
So in any case it's a minor issue.

**Comment by CryZe** [comment]
![https://i.imgur.com/b4nze2X.png](https://i.imgur.com/b4nze2X.png)

I tried Manual Game Time just now and I'm not able to replicate the problem. Can you guys send me the splits file (and maybe the auto splitter?)

**Comment by wooferzfg** [comment]
@noobguy57 Could you please try this build and let me know if it fixes the issue? https://github.com/LiveSplit/LiveSplit/suites/9121483341/artifacts/423438405

**Comment by noobguy57** [comment]
Yes, I will try this and test for 15ish minutes and report back.

**Comment by wooferzfg** [comment]
https://github.com/LiveSplit/LiveSplit/pull/2283

**Comment by wooferzfg** [comment]
The fix for this was included in LiveSplit 1.8.24.
