### ISSUE TITLE
LiveSplit does not download latest UpdateManager.exe.

### ISSUE THREAD

**Issue by MidgeOnGithub** [LiveSplit/LiveSplit#2285]
LiveSplit releases include the latest `UpdateManager.dll`; when invoked, the DLL downloads `UpdateManager.exe`, which is then used to update any components/autosplitters.

The downloaded `UpdateManager.exe` does not reflect the latest version of the code. This means that the recently-released `localPath` functionality is not actually available.

I checked in both assemblies' `Updater.UpdaterInternal.PerformUpdate`.

After downloading the latest release, here is what `UpdateManager.dll` shows in dnSpy:
![image](https://user-images.githubusercontent.com/43119067/200051750-4f715a94-b257-476a-9ead-38be5429c8f4.png)

And once an update is attempted and `UpdateManager.exe` is downloaded, here is what `UpdateManager.exe` shows in dnSpy:
![image](https://user-images.githubusercontent.com/43119067/200051496-d2fa4837-9c63-4722-bae0-534a010fe9f3.png)

As we can see, `UpdateManager.exe` is a different version of the code.

**Comment by wooferzfg** [comment]
If you download LiveSplit from the GitHub releases, is the Update Manager version correct then?

**Comment by wooferzfg** [comment]
We need to update `UpdateManager.exe` on the LiveSplit site: https://github.com/LiveSplit/LiveSplit.github.io/blob/master/update/UpdateManager.exe

**Comment by MidgeOnGithub** [comment]
> We need to update `UpdateManager.exe` on the LiveSplit site: https://github.com/LiveSplit/LiveSplit.github.io/blob/master/update/UpdateManager.exe

I had a feeling it was an outdated artifact somewhere. If I understand correctly, this could be fixed silently without an explicit version release, since none of the distributed files are affected.

Any estimate on when that could be completed?
