### ISSUE TITLE
Keeps overiding edits to files

### ISSUE THREAD

**Issue by Vodkanakas** [LiveSplit/LiveSplit#2288]
Ok so I'm editing a autosplit file for SM to add some room transitions. they work as long as the name isnt the standard file name for the asl file. is there a way to stop Livesplit from redownloading the files on startup?

**Comment by wooferzfg** [comment]
LiveSplit will always redownload scripts since there is no other auto updating functionality for ASL.

To prevent updates from happening, rename the script and add the Scriptable Auto Splitter component to your layout, instead of activating the auto splitter in the Splits Editor.

**Comment by derric-young** [comment]
what is SM

**Comment by Vodkanakas** [comment]
SM=Super Metroid @derric-young 

@wooferzfg kinda late for me to respond to but thank you. have added the SAS to layout and now using that.

**Comment by just-ero** [comment]
This issue seems to be resolved and can be closed.

Cc @wooferzfg
