### ISSUE TITLE
Green border and saving issue

### ISSUE THREAD

**Issue by unispov** [LiveSplit/LiveSplit#2294]
![image](https://user-images.githubusercontent.com/119549896/204944680-1cde5d9b-56b6-4478-ba0c-2169135c23c2.png)

When I installed LiveSplit, there was a green border around the timer application. And when I try to save the file, it does, but when I view it the picture is of a piece of paper and not the normal application sign. When I do open it, there is a pop-up saying, "How do you want to open this .lsl file", and the only thing that pops up is the Microsoft store. No LiveSplit option. Just to add, Global Hotkeys also do not function with this issue.

**Comment by just-ero** [comment]
Can this issue be closed due to inactivity?

The most likely cause of this problem is that the user did not extract the files from the archive they downloaded.

Cc @wooferzfg
