### ISSUE TITLE
Comparing To Game Time does not show any Split Times

### ISSUE THREAD

**Issue by MrMagnetix** [LiveSplit/LiveSplit#2295]
As soon as I Set my Splits Time to use IGT, i can't start new Runs, all they show is Hyphens. Weirdly, they DO work properly when switching to Real Time. 
It doesn't matter in this case if I have the Splits Timing Methos set manually, or If I have them on "Use Current Comparison" and then Right Click > Compare Against > Game Time. In that case, it also only works with Real Time. (I dont use Autosplitters, but I do use Load Removers, so it's kind of annoying)
(Also attached Is an Image of how it looks with Game Time)
Any help appreciated :3

**Comment by wooferzfg** [comment]
This seems like an issue with whatever load remover you're using. It needs to initialize the game time.

**Comment by MrMagnetix** [comment]
Thanks! It was indeed an issue with the Load Remover apparently not recognizing Certain parts of the game like the Main Menu
