### ISSUE TITLE
Racetime Authentication not working

### ISSUE THREAD

**Issue by aidenrosen** [LiveSplit/LiveSplit#2296]
When trying to connect with racetime, Livesplit just brings up an infinite "Loading..." page.  When trying to reset/remove credentials from WIndows Credentials Manager, they just reset upon loading another race, instead of prompting to reauthenticate.

**Comment by just-ero** [comment]
Is this resolved on the most recent stable version of LiveSplit?

**Comment by wooferzfg** [comment]
Seems related to #2374
