### ISSUE TITLE
Unstable time saving.

### ISSUE THREAD

**Issue by petert4727** [LiveSplit/LiveSplit#2300]

**Comment by petert4727** [comment]
For some reason, the time isn't staying the same almost every time. My time for the game I'm running should be around 8:37, but now it's around 9:13 and it keeps fluctuating, and I don't know why.

**Comment by derric-young** [comment]
do you have your time comparitions set to average?

**Comment by derric-young** [comment]
becuase that is usually the case

**Comment by petert4727** [comment]
Oh you're right! Somehow it got moved to there. I don't even know how it got moved to average since I never even went in there!

**Comment by just-ero** [comment]
This seems to be resolved and can be closed.

Cc @wooferzfg
