### ISSUE TITLE
Wants Mac os version installation package

### ISSUE THREAD

**Issue by Bubble-Sword** [LiveSplit/LiveSplit#2302]
Could you provide the livesplit installation package for the MAC OS version? I can’t use a windows sys now, but I found that there is no installation package for the mac version, could you provide help about that？

**Comment by just-ero** [comment]
LiveSplit is built upon a Windows-only programming framework. It is not possible to deploy to Mac.

**Comment by rgeraldporter** [comment]
Has there been any consideration of moving from .NET Framework to the new .NET (previously known as .NET Core)? It is cross-platform compatible. I don't know much about the project to assume this would be in any way easy or doable with existing resources, but it seems like it would be _possible_.

**Comment by wooferzfg** [comment]
There's already a rewrite in progress:
- https://github.com/LiveSplit/livesplit-core
- https://github.com/LiveSplit/LiveSplitOne
- https://github.com/CryZe/livesplit-one-desktop/releases

**Comment by just-ero** [comment]
> Has there been any consideration of moving from .NET Framework to the new .NET (previously known as .NET Core)? It is cross-platform compatible. I don't know much about the project to assume this would be in any way easy or doable with existing resources, but it seems like it would be _possible_.

LiveSplit (this current version) is built with Windows Forms as the GUI framework. As the name suggests, it only works on Windows. To make LiveSplit cross-platform while staying on .NET and C#, a different GUI framework -- Xamarin (Windows, Mac, and some mobile platforms), MAUI (Windows, Mac, Android, iOS), or Avalonia (Windows, Mac, and Linux). This would essentially be a complete rewrite of LiveSplit, which, as woofer mentioned, is already in progress.

**Comment by just-ero** [comment]
Closing as unrelated.

LiveSplit is a Windows-only software.  
LiveSplit One is the cross-platform rewrite.
