### ISSUE TITLE
Loss of precision in segment times

### ISSUE THREAD

**Issue by periwinkle9** [LiveSplit/LiveSplit#2303]
I am using LiveSplit 1.8.25.
Steps to reproduce:

1. Go to Edit Splits and enter "2:14.20" as one of the segment times
2. Save, close the splits, and re-open them.
3. Observe that the segment time is now displaying "2:14.19". Saving the file now results in `00:02:14.1999990` being stored.

Actually, this seems reminiscent of #2286, except now the bug only occurs on closing and re-opening the file.

**Comment by wooferzfg** [comment]
When you enter "2:14.20" as a split time, segment time, or run offset, it gets saved in the splits file as `00:02:14.2000000`. However, when LiveSplit opens that splits file, the time gets parsed as `2:14.199990`. When you save the splits file a second time, the time gets saved as `2:14.199990`.

**Comment by CryZe** [comment]
Yeah we probably still need to update to the latest livesplit-core.
