### ISSUE TITLE
Display/expose current file name used to store splits

### ISSUE THREAD

**Issue by b-jazz** [LiveSplit/LiveSplit#2313]
I had a situation where the splits file I was running was being saved, but the file I thought it was associated with wasn't updating. If there is a way to show what the full path of the file is, I couldn't find it. It sure would be handy to show that somewhere to prevent losing precious data.

**Comment by wooferzfg** [comment]
If you click "Save As", it'll open the file dialog with the path of the splits you have open.

**Comment by wooferzfg** [comment]
I would suggest using "Save As" to save the splits again in this situation
