### ISSUE TITLE
countdown until pb

### ISSUE THREAD

**Issue by JmarbinGG** [LiveSplit/LiveSplit#2314]
hi, 

in my livesplit, it will generally count down a few second before my pb, and i was wondering if there was a way to make it always count down until my pb. if that doesn't make a lot of sense, here is an example:

pb for split 1: 13.75

currently, it starts counting down at about 10 seconds, and i would like it to count down once i start the split if you know what i mean.

feel free to ask any clarifying questions, as i'm not sure if this makes any sense.

:) 
JmarbinGG

**Comment by wooferzfg** [comment]
You can turn off "Show Best Segments" in the layout settings to get this behavior. Not planning to implement anything further than that
