### ISSUE TITLE
PB

### ISSUE THREAD

**Issue by CattyBrat** [LiveSplit/LiveSplit#2315]
I'm not sure if this is the right place but im not sure where else to put it. So, my PB. I want it to show on the right column always, and update to the new PB of that segment when time is shaved off. How? Do i have to complete the run for it to save? If so then that makes sense but i would wish it saved your best times regardless of finishing the run or not. I had a good amount of golden/yellow splits but they didnt 'save' (when you go into edit it saved but it doesn't show it where i want it to.) 
![Screenshot 2023-03-08 201541](https://user-images.githubusercontent.com/127363068/223890415-9b867200-c281-434e-9881-6402df13a150.png)

**Comment by b-jazz** [comment]
As this does not describe a bug but is a question about how to configure the display, it is not right to file a bug/issue. I'll reach out and see if I can help in another way.

**Comment by CattyBrat** [comment]
I think I found out myself how to do it but you can still try to help :3

**Comment by just-ero** [comment]
Closing as completed.

It is possible to save splits at any time, which will save the times for the completed segments.
