### ISSUE TITLE
[ERROR] Scans failed for VirtualMemoryFlag 

### ISSUE THREAD

**Issue by HugoBelin** [LiveSplit/LiveSplit#2318]
Yo i tried to speedrun elden ring but I have this error message and there is no topic that helped me to resolve the problem 
![Capture](https://user-images.githubusercontent.com/128939485/227746218-ca8da34d-294a-481f-b654-4f62df3a09e8.PNG)
I tried everything, (installing lasts version of my drivers, restarting LiveSplit, restarting Elden Ring,..... )

**Comment by CryZe** [comment]
It's best to contact the authors / the community for the auto splitter directly.

**Comment by HugoBelin** [comment]
> 

idk where, I tried so much time

**Comment by HugoBelin** [comment]
> Yo i tried to speedrun elden ring but I have this error message and there is no topic that helped me to resolve the problem ![Capture](https://user-images.githubusercontent.com/128939485/227746218-ca8da34d-294a-481f-b654-4f62df3a09e8.PNG) I tried everything, (installing lasts version of my drivers, restarting LiveSplit, restarting Elden Ring,..... )

![image](https://user-images.githubusercontent.com/128939485/227746852-56a5ce91-5a8f-4677-b4a7-1a91f9bca101.png)
I have this
