### ISSUE TITLE
Implement Twitch's IRCv3 Capabilities + Whispering

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#232]
This is super cool http://blog.twitch.tv/2015/06/whisper/

**Comment by CryZe** [comment]
Looks like they don't use the TWITCHCLIENT anymore, but instead use IRCv3 capabilities: https://github.com/justintv/Twitch-API/blob/master/chat/capabilities.md

The documentation is missing the whispers atm though.

**Comment by CryZe** [comment]
Sending a whisper:
´´´
PRIVMSG #jtv :/w username message
´´´

Receiving a whisper:
´´´
@color=#FF00FF;display-name=ROMaster2;emotes=;turbo=1;user-type=;user_type= :romaster2!romaster2@romaster2.tmi.twitch.tv WHISPER username :message
´´´

This is not available on irc.twitch.tv  (yet?)
This is only available on 199.9.253.120/80  (and maybe other random IP addresses)

**Comment by CryZe** [comment]
I'm sorry, but TWITCHCLIENT is in another castle...

Aka, our Twitch implementation is broken now. So this probably should be in 1.6

**Comment by glacials** [comment]
Whispers will not always remain IRC compatible, so keep that in mind if you build them into LiveSplit. More info: 

http://discuss.dev.twitch.tv/t/whispers-on-irc/2459
http://discuss.dev.twitch.tv/t/whispers-on-irc-2-electric-boogaloo/2477/2
http://discuss.dev.twitch.tv/t/whispers-on-irc-3-just-when-you-thought-it-was-safe-to-chat/2495/6

**Comment by wooferzfg** [comment]
I'm not sure how this would fit in with existing LiveSplit features.
