### ISSUE TITLE
specify time format for splits

### ISSUE THREAD

**Issue by Vodkanakas** [LiveSplit/LiveSplit#2324]
is there a way so the edit splits portion shows the times in HH:MM:SS.00 like 01:10:23.21 or 00:00:54.21?

**Comment by heavyutils** [comment]
Not sure about leading zeros, but you can sure change how many decimals to show in the Layout Editor. In there, double click on “Timer”.

**Comment by wooferzfg** [comment]
There's already an issue for showing more decimals in the Splits Editor: #930 

You can also already configure the layout to show more decimals, and you can export your splits to Excel if you want the raw data.
