### ISSUE TITLE
Livesplit disappearing

### ISSUE THREAD

**Issue by ScubaSteevo92** [LiveSplit/LiveSplit#2331]
I don't know why but Livesplit seems to disappear or randomly delete itself. I have never deleted it, yet three separate times, it does not exist on my laptop any more.

**Comment by just-ero** [comment]
Has this issue been resolved?

The most likely cause is an antivirus software removing LiveSplit due to its potentially malicious code. It's also possible that you did not extract LiveSplit after downloading.

Cc @wooferzfg
