### ISSUE TITLE
Show a message box when clicking on the "other" options in Edit Splits

### ISSUE THREAD

**Issue by wooferzfg** [LiveSplit/LiveSplit#2332]
Clicking on "Clear Times", "Clear History", or "Clean Sum of Best" currently doesn't show any message.

**Comment by shroomwastaken** [comment]
do you mean showing a "Times/History/Sum of Best cleared!" message box or showing a confirmation popup?

**Comment by wooferzfg** [comment]
Yes, except "Clean Sum of Best" does not clear the sum of best. If there's invalid segment history elements, it'll show a series of popup messages. But in the case that there's nothing to clean, it currently shows nothing, which is unintuitive.

**Comment by shroomwastaken** [comment]
![image](https://github.com/LiveSplit/LiveSplit/assets/59111626/d77ab997-472a-45d8-9ac2-cf9a3e1af618)
i've never used this feature before so i'm pretty confused as to how this code executes (sorry if this is really simple maybe im just stupid) where would the code go if there's nothing to clean?

**Comment by wooferzfg** [comment]
If there's nothing to clean, then the callback function is never called inside `SumOfBest.Clean`

**Comment by shroomwastaken** [comment]
ah yes, that makes sense
so ill just put a messagebox with the "nothing to clean" text at the very bottom then

**Comment by wooferzfg** [comment]
> so ill just put a messagebox with the "nothing to clean" text at the very bottom then

I think that might not work if there *is* something to clean. You might want to pass a second callback function to `SumOfBest.Clean` for the "nothing to clean" case.

**Comment by shroomwastaken** [comment]
looks like it doesnt check if something's broken before going through and trying to clean every segment

im thinking of making the CheckPrediction function return true if a segment got changed and then it will keep track of that in the Clean function, if it checked all of the segments and none have been changed it will call NothingToCleanCallback and if any one segment got changed it will do nothing

**Comment by wooferzfg** [comment]
I don't think you need to check if the segment was actually changed, just if the callback was called for at least one segment

**Comment by wooferzfg** [comment]
You could also just keep it simple and output a message like "cleaning is done" at the end, and skip all this complicated logic

**Comment by shroomwastaken** [comment]
yea thats true, idk why i was making it this complicated lol
