### ISSUE TITLE
LiveSplit not loading the correct game from a split file

### ISSUE THREAD

**Issue by DeathHound6** [LiveSplit/LiveSplit#2342]
Upon loading a split file, the correct details (additional info and category) are not loaded correctly, with the only resolution being to manually insert the same game name already present in the input field.
Resaving the splits after the fix, exiting and reloading also does not fix this.

A demonstration is shown below.
https://cdn.discordapp.com/attachments/574291072692256771/1129821346990399538/2023-07-15_18-05-22.mp4

It is worth noting that the only game that this happens with for me is `Alice in Wonderland` (alice2010 on SRC). My best guess as to why this happens is due to a game who's name is `Alice in Wonderland (DS)` (begins with the bugged game's name).
LiveSplit may instead be loading the information from the DS game instead of the Wii/PC one, which is what it should be loading.

Although it is not completely unusable, it is very frustrating to have to manually fix this every time, for category and WR information to be correct and shown every time I go to run this game.

My LiveSplit version is the current latest, 1.8.26, and I always run the app as Admin should that make any difference.

**Comment by CryZe** [comment]
I think I know exactly what's happening here: The game name on speedrun.com seems to end in a space, and LiveSplit, with the way XML works, strips all surrounding whitespace.

**Comment by DeathHound6** [comment]
Ah yep. That's exactly it. Adding the space to the end of the name when opening the splits does fix it

This sounds like something you wouldn't be able to fix in LiveSplit though, since it's an XML thing, right?
The only thing that can really be done is asking a super mod to remove the space from the name?

**Comment by CryZe** [comment]
I'd say that we probably do want to fix this in LiveSplit somehow, since it's definitely a bug. However the space should almost definitely not be part of the game name anyway, so asking a mod to fix this at least fixes the problem for you.

**Comment by DeathHound6** [comment]
Yea that makes sense
Main issue though, is that I requested to become a mod this week since the super mod isn't responding to messages at the moment
Suppose all I can do is message and wait

Thanks for looking into this though

**Comment by wooferzfg** [comment]
This should have been fixed in https://github.com/LiveSplit/LiveSplit/pull/2387
