### ISSUE TITLE
Split time distributions analysis

### ISSUE THREAD

**Issue by Sheypex** [LiveSplit/LiveSplit#2345]
Hi,

Couldn't find this as an existing feature anywhere while searching for it, so I'm leaving this idea here for consideration by people who are more knowledgeable than me about the development of this tool.

TLDR: Use saved logs of times recorded for a split to fit approximate probability distributions that describe the likelihoods of achieving certain times. 

Usage/Utility: Use these distributions to eg. estimate the likelihood of actually performing a run that reaches the 'Sum of Best Segments', to estimate the 'significance' of a new PB split time, to estimate a best guess for the number of run attempts that are expected to include a run that reaches some target overall time or better, etc.

I feel that attaining even basic approximations for time distributions opens up a lot of room for creative inference. 

Gotchas: I'm uncertain if logs of times per split exist or if only the best time per split is saved. This doesn't appear like a big hurdle though if not the case. More practically, the change in a runners performance over time is probably a bigger problem since it's difficult to approximate distributions with relatively low sample rate and perhaps changing underlying true distributions.

Best regards and have a nice day :D

**Comment by Eein** [comment]
Just noting there is a Best Possible Time component that already does this during the run to make an estimation based on your current run vs current splits. This sounds like it fits your use case. 

Theres also a generate goal comparison that gives some probably split times to aim for based on performance.

**Comment by TheTaraStark** [comment]
This would be a neat idea built-in, but probably not a priority at the moment. Until then, there are some existing analysis tools that could work similarly for your purposes, such as [TheRun.gg](https://TheRun.gg). Specifically, I’m thinking of Splits Stats > Reached # in this instance. [Here’s an example!](https://therun.gg/nukiedog/The%20Legend%20of%20Zelda%3A%20Majora's%20Mask/100%25)

**Comment by wooferzfg** [comment]
Not planning to implement this. You can already use sites like therun.gg, splits.io, or export your splits to Excel.
