### ISSUE TITLE
Slow and hangs in Splits Editor

### ISSUE THREAD

**Issue by heavyutils** [LiveSplit/LiveSplit#2348]
Title says it all. Very likely to be because of the huge load of games. A workaround could be to only cook the list of games when the user clicks the drop-down. If that’s not possible, then when the user clicks the game list.

**Comment by alystair** [comment]
I've experienced the same issue

**Comment by wooferzfg** [comment]
The performance of the Splits Editor should be a bit better now with some of the recent changes (such as https://github.com/LiveSplit/LiveSplit/commit/820899de2b30e27aeb66b1cae68044e610f0821f)
