### ISSUE TITLE
Livesplit won't show up when im playing minecraft

### ISSUE THREAD

**Issue by ItsAlex111** [LiveSplit/LiveSplit#2351]
I tab out to Minecraft: Bedrock Edition and Livesplit doesn't show up. I already have "Always on top" enabled but it doesn't work.

**Comment by heavyutils** [comment]
Use windowed full screen rather than traditional fullscreen. It’s long ago I played Minecraft, but some games have a Windowed Fullscreen mode, use it if it has.

**Comment by LukeSaward1** [comment]
> Use windowed full screen rather than traditional fullscreen. It’s long ago I played Minecraft, but some games have a Windowed Fullscreen mode, use it if it has.

There is no borderless windowed last time I checked.
[This](https://github.com/Mr-Technician/BorderlessMinecraft) should be good at achieving it

**Comment by just-ero** [comment]
Can this be closed due to inactivity?

The issue appears to be that no application is able to be displayed on top of a full screen game. This is not an issue on LiveSplit's side.

Cc @wooferzfg
