### ISSUE TITLE
Soul Splitter 1.4.3 Missing Boss for auto split: Deathbird (Capital Outskirts)

### ISSUE THREAD

**Issue by justiziabelle** [LiveSplit/LiveSplit#2358]
Hi,
in the list of Bosses the Deathbird in Capital Outskirts (Altus Plateau) is missing, instead there is a Death Rite Bird listed (3 times), anyways there's no split after killing the Deathbird.

But also there is a "Monstrous Dog" listed for Caelid when there is no Monstrous Dog Boss anywhere in the game. Don't know what that's about and also also the Bell-Bearing Hunter in Capital Outskirts isn't listed, although there is a split when it is killed.

That said, when adding all the listed Bosses for automatic Splitting, the Deathbird in capital outskirts is the only one where it doesn't do a split.

**Comment by LukeSaward1** [comment]
Take this up with the developers of SourceSplit. This is not LiveSplit's issue.

**Comment by CryZe** [comment]
Yeah, auto splitter specific issues are handled by the developers of the auto splitters.
