### ISSUE TITLE
Cannot assign side mouse buttons to settings hotkeys

### ISSUE THREAD

**Issue by StickCannon** [LiveSplit/LiveSplit#2363]
Yeah no hotkey is being overwritten when trying to use side mouse buttons for Start,Reset, ect..

**Comment by wooferzfg** [comment]
Do you have "Allow Gamepads as Hotkeys" enabled in the settings?

**Comment by StickCannon** [comment]
> Do you have "Allow Gamepads as Hotkeys" enabled in the settings?

This works thanks! though the 2 other buttons on the right side of my mouse don't assign this might be a problem with my mouse

**Comment by wcaroman** [comment]
Edit settings.cfg and use next keys for normal buttons: LButton, RButton, MButton, XButton1, XButton2
And probably wheel buttons also work: WheelDown, WheelUp, WheelLeft, WheelRight
