### ISSUE TITLE
Video Plugin not working with VLC 3.0.X and ActiveX plugin installed

### ISSUE THREAD

**Issue by SukeSJ** [LiveSplit/LiveSplit#2364]
Currently have tried VLC 2.2.1. VLC 3.0.0 and VLC 3.0.18 and i get this error (VLC Media Player 3.0.x (64-bit) along with the ActiveX plugin need to be installed for the Video Component to work.)
![2023-09-23 20_19_56](https://github.com/LiveSplit/LiveSplit/assets/67334059/0538c68b-7109-427c-8273-b537e6f40f7a)

**Comment by wooferzfg** [comment]
You've tried VLC 3.0.18 and making sure that the ActiveX plugin is included in the installation?

**Comment by SukeSJ** [comment]
Yup. This is how it looks when i install it

![2023-10-01 19_54_00](https://github.com/LiveSplit/LiveSplit/assets/67334059/2f1bd1e0-b535-40fd-ae10-c6f4b1dbdcb3)

**Comment by wooferzfg** [comment]
And you downloaded the 64 bit version? https://get.videolan.org/vlc/3.0.18/win64/vlc-3.0.18-win64.exe
