### ISSUE TITLE
exe file missing

### ISSUE THREAD

**Issue by Altois0** [LiveSplit/LiveSplit#2370]
i looked everywhere, there is no livesplit exe file.  What did i do wrong

**Comment by wooferzfg** [comment]
Did you extract the ZIP file you downloaded from livesplit.org/downloads? Also, make sure you don't have a virus scanner affecting LiveSplit.

**Comment by just-ero** [comment]
Can this be closed due to inactivity?

The issue is possibly caused due to an antivirus program removing potentially malicious software. Make sure to allow LiveSplit to exist on your drive.

Cc @wooferzfg
