### ISSUE TITLE
Skipping splits doesn't really work

### ISSUE THREAD

**Issue by cwainczak** [LiveSplit/LiveSplit#2372]
Suppose this scenario:
- Split 1 | 2:00
- Split 2 | SKIPPED
- Split 3 | Time it took from Split 1 to Split 3

Generally, the segment of a split is the time it takes to get from that split from the previous split. However, in this case, Split 3's segment time is the time it took to get from Split 1 to Split 2 **and** from Split 2 to Split 3.

This makes splitting difficult for games with inconsistent routes; if you go out of order for your run, your split times are out of sync. If we decide to skip Split 2 because it is more applicable to go to Split 3 first (but then have to go do Split 2 after; suppose it is a mission or something), we now put an incorrect segment time down for Split 3 (as Split 3 should be the time it takes to get from Split 2 to Split 3). This makes the feature of "Best Segments" completely obselete in a non-linear speedrun.

I would love if we can get a fix for this; it can be some specific type of skip, where the segment time for Split 3 becomes counted the moment Split 2 is skipped. So, if we need to skip Split 2, we can decide when to start counting time by skipping whenever is applicable, instead of always having to aggregate the bonus time.

**Comment by Jujstme** [comment]
The kind of behavior you're asking for is just unsupported in Livesplit

**Comment by cwainczak** [comment]
> The kind of behavior you're asking for is just unsupported in Livesplit. I don't think non-linear routes are part of its design.

I see. This makes me wish there was another program like LiveSplit that did account for non-linear speedruns. I understand that most speedruns are linear, but the ones that aren't are unfortunately left in the dark with this kind of issue.

**Comment by cwainczak** [comment]
> > This makes the feature of "Best Segments" completely obselete in a non-linear speedrun.
> 
> When you skip Split 2, LiveSplit tracks the time from Split 1 to Split 3 and uses that to calculate the Sum of Best Segments, even though the "Best Segment Time" in the Splits Editor might show a faster time. Note: the "Simple Sum of Best" setting disables the use of the segment history for the Sum of Best Segments.

This makes things a bit better, but still doesn't exactly solve the issue. If I did the Split 1 mission, then the Split 3 mission (and skipped Split 2), and then did the Split 2 mission, this is a somewhat okay solution. However, if I choose to never do the Split 2 mission because it would more effective to skip it, this method unfortunately becomes obselete.

I guess it's just not possible with LiveSplit, but would be a great addition if non-linear speedruns were accounted for.

**Comment by wooferzfg** [comment]
This requires something like #178
