### ISSUE TITLE
cant extract

### ISSUE THREAD

**Issue by XpNvH** [LiveSplit/LiveSplit#2373]
when i try to extract it from the website download (im using 7zip) it says cannot open file as archive 
wont work ive tried it like a million times

**Comment by wooferzfg** [comment]
It's a standard ZIP file. Maybe it's an issue with your virus scanner, or with your 7Zip installation.

**Comment by XpNvH** [comment]
it was just firefox being stupid. i figured it out. thanks for replying so fast though
