### ISSUE TITLE
AutoSplit not working

### ISSUE THREAD

**Issue by NIGHTpro8** [LiveSplit/LiveSplit#2382]
Hi. I was trying to speedrun GTA5 Trevor%, but when I launched a new game, the AutoSplit wasn't working. I am playing on version 1.27, and the AutoSplit turned on. It used to work before, but it just stopped working, without me doing anything. Any ideas on how to fix?

**Comment by wooferzfg** [comment]
I'd suggest reaching out to the developer of the autosplitter

**Comment by just-ero** [comment]
This is not an issue that can be fixed here. An issue on the repository of the autosplitter is more appropriate: https://github.com/hoXyy/GTAV-AutoSplitter.
