### ISSUE TITLE
How to delete invalid best segments?

### ISSUE THREAD

**Issue by alystair** [LiveSplit/LiveSplit#2386]
I've had many situations where I accidentally 'completed' segments in absurely short time - ruining my PB listings. Wondering where I go to delete these safely? Eg. segments that should take 40+ seconds plus are marked as 2 seconds etc.

**Comment by wooferzfg** [comment]
In the Splits Editor, you can select the best segment time and then press your delete key.

**Comment by alystair** [comment]
Thanks, didn't realize it could be reverted to previous successful runs.
