### ISSUE TITLE
Livesplit won't properly update to 1.8.27

### ISSUE THREAD

**Issue by RicardoAndresV** [LiveSplit/LiveSplit#2388]
Every time I attempt to update to 1.8.27, I click Yes, Livesplit appears to update, then the popup appears again asking me to update to 1.8.27. 

![Screenshot 2024-01-08 185123](https://github.com/LiveSplit/LiveSplit/assets/91508240/886c7f3b-dd23-46ef-b6ab-cebfb2bd3bbb)

I attempted to manually install 1.8.27 by deleting my old Livesplit install, downloading the new one, then dragging it into its place, yet it still occurs.

**Comment by wooferzfg** [comment]
That's because you're using a custom Subsplits component that's tied to the auto updater XML for the regular Subsplits component even though it has a custom component DLL.

**Comment by RicardoAndresV** [comment]
Ah ok, thank you!

**Comment by fmichea** [comment]
@wooferzfg The URL has been fixed in the relevant component and I made an announcement where it makes sense, thanks for the advice, you can close this issue.
