### ISSUE TITLE
Maybe try to patch the Game and Category of Speedrun.com Runs

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#239]
When downloading a run from speedrun.com, the actual Game and Category is known. Since it's a huge advantage to have them properly filled out, it might be a good idea to patch the game and category names of the downloaded run in order to make sure they are correct.

**Comment by wooferzfg1** [comment]
A weird case for this would be: http://www.speedrun.com/run/65670

**Comment by CryZe** [comment]
Well, in that case we should maybe cut of the additional splits too, but idk.

**Comment by CryZe** [comment]
Not questionable anymore. We definitely want to patch the metadata and therefore the game name and category name too (otherwise the metadata is useless).
