### ISSUE TITLE
[Bug] LiveSplit crash when a video component is in the layout

### ISSUE THREAD

**Issue by Yanis42** [LiveSplit/LiveSplit#2391]
## Setup
- OS: Windows 11 (22H2, build ``22621.3007``)
- VLC Version: 3.0.20 64-bits
- LiveSplit files located on my desktop (on a SSD, if that matters)

## Computer Specs
- CPU: AMD Ryzen 7 5700g
- GPU: Nvidia GTX 1050Ti
- Motherboard: MSI B350 Tomahawk
- RAM: 2*16GB DDR4 3200MHz
- 1TB SSD (nvme, hosts the OS)

## Steps to reproduce
- Open LiveSplit (1.8.26 or 1.8.27 or auto-build from commit d29c0f4c925f3b4ce4e8656a9af14ec47007765b)
- Load the default layout
- Edit it and add the video component
- The video component is added to the layout, but the crash happens right after

---
I have no idea how to debug this without installing Visual Studio (and I want to avoid doing that), maybe it's something AMD-related? I don't remember having such issues with my previous CPU which was an Intel.

I tried to disable SRL and Racetime just in case (I read that it could cause a crash in another issue) but same thing, note that I tried that months ago and it kinda worked, I was having crash issues but not like this one, not sure what's the issue here, probably something Windows changed? also I tried some compatibility things just in case but still crashing

At this point I'm not sure it's a me-issue as other people have been complaining about crashes too but if it's just my setup that cause such issues then it's fine I guess 🤷 

---
<details>

(it's white because of the "X is not responding" thing from Windows)
<img src="https://github.com/LiveSplit/LiveSplit/assets/35189056/9193aea5-6471-4982-abf4-d865140625f2"/>
</details>

**Comment by wooferzfg** [comment]
Did you install the ActiveX Component for VLC?

**Comment by Yanis42** [comment]
ActiveX should be installed yeah

I found an old discord message of me saying it's because I had the most up-to-date version, I installed 3.0.0 and it worked, though I didn't try again yet, but I confident it would work but then I'll run into the issues I had in the past, which were random crashes, random timer freeze, things like that

**Comment by DoctorBlue** [comment]
Chiming in here to say "me too." Updated to latest LiveSplit this morning (same versions: `1.8.26` and `1.8.27`), any splits with the Video component in it now instantly crash it.

Event Viewer in Windows (I'm on Win10 pro x64) only has a generic "program hangs" message:

```
The program LiveSplit.exe version 1.0.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 3320
 Start Time: 01da6ca4a2546daf
 Termination Time: 5
 Application Path: C:\Path\To\LiveSplit.exe
 Report Id: 2a71dadc-acff-438b-8359-8562f84d2934
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Cross-thread
```

![image](https://github.com/LiveSplit/LiveSplit/assets/47405668/a5540867-06dd-417b-979b-5a7b9c31507e)

Can reproduce by starting a new instance of LiveSplit with no splits or layout files open. Adding the Video component instantly crashes things. VLC version is `3.0.20 Vetinari`, and this works prior to the latest update.

![image](https://github.com/LiveSplit/LiveSplit/assets/47405668/3a2767f9-7beb-4b80-827a-f9503e85aa0d)

**Comment by DoctorBlue** [comment]
Found out there's a lot more in the event viewer as a matter of fact. I have 1000s of these messages (100s being thrown per second. I'm guessing this `Update()` method in LiveSplit is called every frame or something):

```
Object reference not set to an instance of an object.

   at LiveSplit.Video.VideoComponent.<Update>b__52_0()
   at LiveSplit.Video.VideoComponent.Update(IInvalidator invalidator, LiveSplitState state, Single width, Single height, LayoutMode mode)
   at LiveSplit.UI.Components.ComponentRenderer.InvalidateVerticalComponent(Int32 index, LiveSplitState state, IInvalidator invalidator, Single width, Single height, Single scaleFactor)
   at LiveSplit.UI.Components.ComponentRenderer.Update(IInvalidator invalidator, LiveSplitState state, Single width, Single height, LayoutMode mode)
   at LiveSplit.View.TimerForm.<TimerElapsed>b__185_1()
```

**Comment by wooferzfg** [comment]
3.0.18 works for me, but the latest (3.0.20) doesn't work.

**Comment by wooferzfg** [comment]
I removed the change to the volume. I think we originally had it because the muting wasn't working properly, but when I'm trying it now, there's no issues with muting.
