### ISSUE TITLE
Submit Run prevents submitting runs "for more than the currently authenticated user" even for runs which may be single-player

### ISSUE THREAD

**Issue by ambersz** [LiveSplit/LiveSplit#2397]
https://github.com/LiveSplit/LiveSplit/blob/ce1fe0466444b721e0cd80f3261f7bcb106cbb27/LiveSplit/LiveSplit.Core/Web/Share/SpeedrunCom.cs#L168-L172

The player count on the category [may be "up-to"](https://github.com/speedruncomorg/api/blob/57138cae156591c53823c43622ab9434bb5d4279/version1/categories.md?plain=1#L51-L52) which includes the possibility that it is a single-player run

I'm not sure what the purpose of the safety check is, so don't know if it's better to err on the permissive side, allowing runs which _may_ be single-player to go through, or warn/block submissions which _may_ involve multiple players

**Comment by wooferzfg** [comment]
We actually do support the distinction: https://github.com/LiveSplit/SpeedrunComSharp/blob/master/SpeedrunComSharp/Categories/Players.cs#L15
