### ISSUE TITLE
Categorize the Recently Used List into Games and Categories

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#240]
By Categorizing the Recently Used List we can have a lot more games there, it's a lot cleaner and you can easily find your splits.

**Comment by wooferzfg1** [comment]
we should keep the file name also though because people will have multiple splits per category sometimes

**Comment by CryZe** [comment]
I think it should adjust to the Use Case:
 * If you have a low amount of splits, it shouldn't categorize at all
 * If you run only a single game, only show the categories and skip the games completely

**Comment by CryZe** [comment]
@wooferzfg1 Can you verify if this works well for you or if you can find any bugs?

**Comment by wooferzfg1** [comment]
Everything seems to work, but I think keeping the order as most recent might be better than using alphabetical order. Also backwards compatibility for 1.5 settings where games & categories are populated should be added before this is merged I think.
