### ISSUE TITLE
Split dosen't save

### ISSUE THREAD

**Issue by ghost** [LiveSplit/LiveSplit#2402]
When i try to press 1
![image](https://github.com/LiveSplit/LiveSplit/assets/161221789/4ea1a4e5-ef6d-429b-b563-892476aad947)
The split dosen't save the timer.
https://youtu.be/88Xu-QSG8xM

**Comment by Refragg** [comment]
Hello, it looks like you're probably using the wrong timing method.
Try this: Right click on LiveSplit > Compare Against > Real time.
Make sure that in your layout, the splits also use real time and not game time.
