### ISSUE TITLE
Add a Pre-Commit Hook for the Tests

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#242]
git apparently has so called "pre-commit hooks" which are basically scripts that can be run while committing. If the script fails, the commit is automatically stopped too. So the script determines when you can commit and when you can't. If we added a script with the Unit Tests to the Pre-Commit Hook, you wouldn't be able to commit when your code is faulty, which would be pretty cool.

**Comment by wooferzfg1** [comment]
Would there be a way to override it? Not being able to commit with errors would mean not being able to do WIPs or asking for help with an error.

**Comment by CryZe** [comment]
Yeah you can commit with --no-verify
