### ISSUE TITLE
Force Capitalization of Username in the WR Component as a Setting

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#244]
PowderedMilk wants this: http://www.twitter.com/PowderedMilk_/status/610954756887023616

**Comment by wooferzfg1** [comment]
I'm not sure about this feature. It looks better on some names (the ones that are meant capitalized but the users for some reason decided not to) and looks worse on those that are meant to be lowercase (like my username).

**Comment by wooferzfg** [comment]
Not planning to implement this. Users can control the desired capitalization of their username on speedrun.com.
