### ISSUE TITLE
Prevent user from accidentally overwriting a splits file with a layout file

### ISSUE THREAD

**Issue by flemgus** [LiveSplit/LiveSplit#2454]
every single time i save a livesplit thing it always tells me that when i load it up, this is the most recent version and i re-installed it and tried re making it 3 times
![image_2024-04-17_205316929](https://github.com/LiveSplit/LiveSplit/assets/167311381/cf0abc9f-9c55-4dbb-9b13-ed8073b5afb5)

**Comment by CryZe** [comment]
Please attach the splits file as well, so we can look into it.

**Comment by TheTaraStark** [comment]
I've also had this issue since switching from LSO to LS, I think it's something to do with the image files used for icons because clearing the icons and uploading different images fixed the issue for me. Sadly, git won't let me attach an .lss file but I'll try to get something in the Discord

**Comment by CryZe** [comment]
So we just fixed the bug @TheTaraStark encountered, but I'm not convinced that this fixes the original bug. So I'd still like a splits file for that.

**Comment by just-ero** [comment]
We should expand #2371 to include all image formats that LiveSplit One supports.

**Comment by flemgus** [comment]
> Please attach the splits file as well, so we can look into it.

yes but it said that github doesn't support that file type, is there any other way i can send it?

**Comment by flemgus** [comment]
> Please attach the splits file as well, so we can look into it.

[Subnautica - Any% - Copy.zip](https://github.com/LiveSplit/LiveSplit/files/15022117/Subnautica.-.Any.-.Copy.zip)
 here's a compressed version

**Comment by CryZe** [comment]
That's a layout file. It seems like you accidentally overwrote your splits with the layout.

**Comment by CryZe** [comment]
@wooferzfg Maybe we should error out in case the file extension is mixed up like that before overwriting any files.

**Comment by flemgus** [comment]
> That's a layout file. It seems like you accidentally overwrote your splits with the layout.

ah yes how do i fix that or do it the proper way again?

**Comment by flemgus** [comment]
> @wooferzfg Maybe we should error out in case the file extension is mixed up like that before overwriting any files.

yes oaky i re did them and it worked thank you idk what went wrong beofre but it's fixed now
