### ISSUE TITLE
ScriptableAutoSplit: vars problem

### ISSUE THREAD

**Issue by LightningLoops** [LiveSplit/LiveSplit#2465]
"'System.Dynamic.ExpandoObject' does not contain a definition for " error appears in Event Viewer when trying to use the vars object. Code that follows the vars line is skipped.

Weird thing is, it was working the day before, now it doesn't. Timer now doesn't reset, nor splits. Just starts.

**Comment by just-ero** [comment]
Closing as stale.

There is no clear cause for the issue.
