### ISSUE TITLE
WorldRecord component: Filter by timing method (RTA/IGT/LRT)

### ISSUE THREAD

**Issue by Avasam** [LiveSplit/LiveSplit#2474]
Currently the shown WR uses the primary timing method if I'm not mistaken. I have two use-cases to use a timing method (RTA/IGT/LRT) other than the primary one:

1. When the timer has no load remover / can't be aware of IGT. This is especially for console runs where the loads are consistent enough to get an idea of how close someone is to the record. But still using IGT or loads are removed after the fact for leaderboards.
2. When the timer *does* support load removal / IGT inspection. But the leaderboard uses uses RTA as a primary timing method. This could be for legacy reasons, or because only certain categories/subcategories use LRT/IGT.

The "Pitfall: The Lost Expedition" community is currently in the second case since PC version is a subcategory. But may eventually become the first case if console switches to LRT by default.

**Comment by wooferzfg** [comment]
The timing method used is always the game's default timing method, and it's always compared to the equivalent timing method in LiveSplit https://github.com/LiveSplit/LiveSplit.WorldRecord/blob/1f1349a967e4471251450fcc0f4492667ff2073d/src/LiveSplit.WorldRecord/UI/Components/WorldRecordComponent.cs#L139

**Comment by wooferzfg** [comment]
> When the timer has no load remover / can't be aware of IGT. This is especially for console runs where the loads are consistent enough to get an idea of how close someone is to the record. But still using IGT or loads are removed after the fact for leaderboards.

If IGT is the default on the leaderboard, then LiveSplit will show the IGT record. The problematic case is specifically the second one, where console and PC runs are on the same leaderboard, but a particular leaderboard can only have 1 default timing method.
