### ISSUE TITLE
Add setting to block autosplitters from creating popups

### ISSUE THREAD

**Issue by rythin-sr** [LiveSplit/LiveSplit#2480]
The "please switch to game time" popups are extremely overdone, annoying and sometimes borderline malicious when they refuse to go away until you click yes.

**Comment by wooferzfg** [comment]
I don't think there's a good way to do this with how autosplitters are currently implemented (where autosplitters basically have full access). It works better with the auto splitting runtime, where autosplitters are sandboxed.

For now, it might be best to reach out to autosplitter devs individually and ask them to remove the message boxes. If you the behavior is malicious for a particular autosplitter, you can open a PR to remove that autosplitter from the autosplitters XML.
