### ISSUE TITLE
a couple things not working with livesplit

### ISSUE THREAD

**Issue by ScottWWFC** [LiveSplit/LiveSplit#2491]
When i try and run my livesplit from my desktop it doesnt load but it does when i load it through files also i cant change the background colour for my timer i have all the right files downloaded but i cant seem to find a solution

**Comment by wooferzfg** [comment]
Try these steps:
1. redownload LiveSplit
2. Extract the ZIP contents to a folder
3. Open LiveSplit.exe in the folder
4. Say "Yes" to the Admin prompt, so that it registers the file associations

**Comment by ScottWWFC** [comment]
there is no admin prompt

**Comment by wooferzfg** [comment]
Try running LiveSplit as administrator

**Comment by ScottWWFC** [comment]
i can change the colour for the title but not for the back ground the box is white if that  makes sense

**Comment by wooferzfg** [comment]
Can you post a screenshot?

**Comment by ScottWWFC** [comment]
![Screenshot 2024-05-04 194217](https://github.com/LiveSplit/LiveSplit/assets/168774505/81411def-8a8b-44a2-a3a4-b9a74890e3d3)
![Screenshot 2024-05-04 194204](https://github.com/LiveSplit/LiveSplit/assets/168774505/5bcf75aa-7e7a-4751-9965-62fc1c80e27e)

**Comment by wooferzfg** [comment]
When changing the background color in the Layout tab, you'll need to increase the alpha value. I'm pretty sure it defaults to 0 (fully transparent).

**Comment by ScottWWFC** [comment]
where would that be located?

**Comment by wooferzfg** [comment]
Click on the gray box, then there's a vertical bar in the color picker that controls the alpha.

**Comment by ScottWWFC** [comment]
OMG im so dumb thanks for the help
