### ISSUE TITLE
Mon temps par split ne s'affiche pas 

### ISSUE THREAD

**Issue by Pouletox** [LiveSplit/LiveSplit#2500]
Bonjour quand je split en speedrun mon temps ne s'affiche pas par split pouvez-vous m'aider svp 

Cordialement bonne journée

**Comment by just-ero** [comment]
Please use English in this repository.

Make sure your splits component or LiveDplit as a whole are set to compare to Real Time.

**Comment by Pouletox** [comment]
Hello when I split in speedrun my time is not displayed by split can you help me please

Kind regards, have a nice day

**Comment by just-ero** [comment]
I have already suggested a fix.

**Comment by Pouletox** [comment]
ok thx can you say me where is it pls ?

**Comment by Pouletox** [comment]
![image](https://github.com/LiveSplit/LiveSplit/assets/170230163/cb4da566-e57e-4cad-b225-c85a472d8318)

Its normal ?

**Comment by just-ero** [comment]
Right click LiveSplit, compare against, real time.

**Comment by Pouletox** [comment]
![image](https://github.com/LiveSplit/LiveSplit/assets/170230163/96611a5e-f790-410e-b02e-81b9ea38d0d2)

![image](https://github.com/LiveSplit/LiveSplit/assets/170230163/40e7018f-9e10-460f-8991-b289cd5f9794)

**Comment by Pouletox** [comment]
its good sorry
