### ISSUE TITLE
Livesplit is not responding after changing resolution

### ISSUE THREAD

**Issue by Pkow1999** [LiveSplit/LiveSplit#2502]
After changing resolution or changing refresh rate livesplit is not responding.

Here are some Event Viewer logs:
![obraz](https://github.com/LiveSplit/LiveSplit/assets/72875240/44f19efa-ba9b-467f-b78a-22a02ec30b0a)
![obraz](https://github.com/LiveSplit/LiveSplit/assets/72875240/9f3352aa-4b69-4385-8c20-515aee70a852)
![obraz](https://github.com/LiveSplit/LiveSplit/assets/72875240/c8da92f1-4c09-442e-9a79-f1574add2233)

**Comment by wooferzfg** [comment]
Are you using the latest version of LiveSplit?

Also, based on the first error, it could be an issue with the autosplitter you're using.

**Comment by Pkow1999** [comment]
Yeah my bad, apparently the latest update fixed it or smth for now, which is fantastic because this thing was buggering me for several updates. 
Sorry for opening this issue, that was a little bit rash decision.
