### ISSUE TITLE
Timer/Splits Not Showing Up On Top Of The Game

### ISSUE THREAD

**Issue by hypnOX22** [LiveSplit/LiveSplit#2510]
Ok so, I'm trying to speedrun Hello Neighbor (Beta 3) And whenever I open the game, the timer won't show up. If I click on the livesplit on my taskbar, it just minimizes the game and only shows the timer. Also, I have the layout settings on "Always on top" Please help

**Comment by wooferzfg** [comment]
LiveSplit currently doesn't support appearing on top of full screen games
