### ISSUE TITLE
Typing livesplit into windows explorer opens http://livesplit, but this does not happen with any other input.

### ISSUE THREAD

**Issue by viasux** [LiveSplit/LiveSplit#2511]
Totally possible this phenomenon is caused by something other than this applicaiton, but it's just.. weird lol. Why it do that..
https://github.com/LiveSplit/LiveSplit/assets/47131867/1c011957-eee3-41a8-a9ec-5900a01c73ed

**Comment by just-ero** [comment]
For me, a browser window opens for anything that I type into the Windows explorer.

**Comment by wooferzfg** [comment]
This isn't re

**Comment by viasux** [comment]
> For me, a browser window opens for anything that I type into the Windows explorer.

weird, it only happens when I type livesplit on mine, as demonstrated in the video.
