### ISSUE TITLE
Compilation in Linux

### ISSUE THREAD

**Issue by jljlspeedrunning** [LiveSplit/LiveSplit#2517]
I have .NET 8.0 SDK and runtime installed on Arch Linux. .NET Framework 4.6 was deprecated. How do i compile LiveSplit for Linux?

**Comment by wooferzfg** [comment]
.NET Framework 4.6 is required, but in general LiveSplit only officially supports Windows

**Comment by apple1417** [comment]
Though note you can generally run it under proton perfectly fine. You need to run it under the same prefix as the game to get autosplitters to work. What I've always done (though there's probably an easier way) is:
1. Temporarily set the game's launch options to `PROTON_DUMP_DEBUG_COMMANDS=1 %command%`.
2. Launch the game. This dumps some scripts into `/tmp/proton_$USER/` with the exact proton config. Remove the launch option after.
3. Copy `/tmp/proton_$USER/run` somewhere else, edit it and replace `DEF_CMD` to point at LiveSplit.exe
4. Run the script.
