### ISSUE TITLE
Sub Category not Showing when changing title of the game

### ISSUE THREAD

**Issue by AleyzRo** [LiveSplit/LiveSplit#2529]
it just says: "World Record: 0:00.00 by me"

**Comment by wooferzfg** [comment]
Can you be more specific? Some concrete steps to demonstrate the issue or a video wouls be helpful

**Comment by AleyzRo** [comment]
https://youtu.be/5PJa3vW-GcI

**Comment by just-ero** [comment]
Click Additional Info.

**Comment by wooferzfg** [comment]
The reason it says "World Record is 00:00 by me" is because your only split has a time of 0 - that means your PB time is 0, which is faster than any WR will ever be

**Comment by AleyzRo** [comment]
ohhh
