### ISSUE TITLE
Wont Update Splits

### ISSUE THREAD

**Issue by Qyndryx** [LiveSplit/LiveSplit#254]
When I finish a run and the popup saying "Do you want to update your splits" come ups.  I click Yes and then it reverts to my old times.  If you don't understand, if my original time for a split was say 2:00 and I lost 2 seconds it would be 1:58 if I clicked yes on the update popup it would stay the same at 2:00 instead of 1:58.  What is wrong, why is this happening?  It is really starting to irritate me, I have to write down all of my times then update them manually.

**Comment by wooferzfg1** [comment]
Was your new final split faster than the final split you had before? It'll only update the splits if you PB. Otherwise, it'll just update your best segments.

**Comment by Qyndryx** [comment]
Yes they were faster

**Comment by wooferzfg1** [comment]
can you send your splits? (upload to mediafire or something)

**Comment by Qyndryx** [comment]
OK, if I can

**Comment by Qyndryx** [comment]
http://www.mediafire.com/view/477a1kk3hgm32kp/Portal_Glitchless_LiveSplit_Layout.lsl

**Comment by wooferzfg1** [comment]
Isn't that your layout file rather than your splits file?

**Comment by Qyndryx** [comment]
sorry wrong file

**Comment by Qyndryx** [comment]
https://www.mediafire.com/?1c1daqf6fssud5e

**Comment by wooferzfg1** [comment]
Could you do a test run of some kind where it's supposed to update the splits but doesn't, save the spilts, and then send those? I'm trying to figure out what it's doing for you.

**Comment by CryZe** [comment]
Are you sure you are comparing against Personal Best and not something else?

**Comment by Qyndryx** [comment]
It is saving best segments.  Is it supposed to do that?  It seems to work fine there, best segments is pretty much the same as PB?

**Comment by Qyndryx** [comment]
I had 2:15 then saved 2 seconds then it updated t 2:13 on best segments

**Comment by wooferzfg1** [comment]
Yes, but it'll only updated Personal Best if you complete a run and your final split is faster than before. Does it not do that for you?

**Comment by Qyndryx** [comment]
No it doesn't do that, so should install/reinstall ?
