### ISSUE TITLE
New Timing Method(s): Full RTA & Paused Time

### ISSUE THREAD

**Issue by Pixiuchu** [LiveSplit/LiveSplit#2544]
One or two new timing methods:
When you pause LiveSplit, this timer method would continue, and can not be stopped. It is essentially the full RTA from start to finish. This would be great for runs that want to pause the run for any reason, but also track the actual RTA time. The second new timing method is essentially just the total paused duration.

Currently to achieve either of the timing methods I use a second LiveSplit instance to show the true time or to show for long I have paused (the latter which is useful for games that have specific pausing rules). It's inconvenient and can (and absolutely has) mess up the timers if not set up in a very specific way.

They probably need better names.

**Comment by wooferzfg** [comment]
We already store the total duration of all pauses [in the state](https://github.com/LiveSplit/LiveSplit/blob/master/src/LiveSplit.Core/Model/LiveSplitState.cs#L134) and in the splits file, which components could access

**Comment by Pixiuchu** [comment]
I guess an alternative is to add support for the unpaused timer in the Timer / Detailed Timer default components (maybe as a checkbox "Time Pauses", by default unticked) so that people don't have to add 3rd party components or go through the .lss files in a text editor (which is what I currently do). I don't find any component that adds such a timer either.
