### ISSUE TITLE
"Start WS Server" option is not present despite documentation saying it is

### ISSUE THREAD

**Issue by Jzwhale** [LiveSplit/LiveSplit#2550]
The LiveSplit Server documentation states that possible connections include a WebSocket server that can be found/started under the Control menu, but the only server option listed there is the "Start TCP Server" option. I tried the WS connection while the TCP server was running just in case they were somehow being run at the same time (docs say they can't but figured I'd try anyway) and it didn't yield any results. I feel like this is pretty important given a lot of contexts (such as browser clients) don't always support TCP sockets. Am I missing something or is the option just not there?

**Comment by wooferzfg** [comment]
Are you using the dev build? It's currently only available there

**Comment by Jzwhale** [comment]
You replied just as I spotted the commit that added it, haha. I'll download the dev client, thank you!
