### ISSUE TITLE
Build  instructions seem to be lacking?

### ISSUE THREAD

**Issue by lietu** [LiveSplit/LiveSplit#270]
I was thinking of trying to add a feature to LiveSplit, but the build instructions on [https://github.com/LiveSplit/LiveSplit/blob/master/README.md](https://github.com/LiveSplit/LiveSplit/blob/master/README.md) seem to be lacking a bit.

Firstly I bumped into some kind of `AxAXVLC could not be found` -errors. I tried a wild guess, that in addition to Xsplit it required VLC, and more specifically it's ActiveX component. I seem to have been correct as those errors sent away.

However, now I'm looking at a different set of errors:
![image](https://cloud.githubusercontent.com/assets/1296558/8449708/8b344e8c-1fdc-11e5-8e62-0286a9624216.png)

Could it be that the project depends on a specific version of VLC, or that I need something else?

Trying to build a debug version on Windows 10 / Visual Studio 2013 Community Edition.

**Comment by wooferzfg1** [comment]
Did you add the ActiveX component as a reference (Add Reference -> COM -> ActiveX Component) in LiveSplit? I think I had the same errors when it wasn't referenced.

**Comment by lietu** [comment]
No, I had not tried anything like that. I went to `Project -> Add Reference ... -> COM` and checked `VideoLAN VLC ActiveX Plugin`. Tried build again, nothing changed.

**Comment by CryZe** [comment]
Well, no idea what's causing this specifically, but you probably don't need the Video component anyway for whatever you wanna do, so I guess you could just remove the Video component from the solution.

**Comment by lietu** [comment]
Yup, removed Media -> LiveSplit.Video, seems to compile fine now .. thanks! Would probably be nice to figure out what is still required though.

**Comment by wooferzfg1** [comment]
XSplit is no longer required to compile LiveSplit but VLC is, so I guess the ReadMe should be updated.

**Comment by wooferzfg1** [comment]
Also, I got the Video Component to compile by referencing AxVLC.dll and Interop.AxVLC.dll (you can get these from the Components folder of a downloaded LiveSplit build)

**Comment by CryZe** [comment]
I'll close this, since @lietu got his to build and since the VLC files are included now.
