### ISSUE TITLE
Not all previous attempt splits being read?

### ISSUE THREAD

**Issue by ROMaster2** [LiveSplit/LiveSplit#276]
https://www.dropbox.com/s/2zpak2haxxqeqzj/Majora%27s%20Mask%20Any%25.lss?dl=0

For whatever reason both 'Average' and 'Balanced PB' aren't recognizing the couple of previous attempts past NWBN, even though they seem just fine. I tried removing Time id 0 but that didn't change anything. The file has not been tampered with.

**Comment by ROMaster2** [comment]
The solution may cause an issue. What if the segment after the null one is the combination of two segments, as a result of skipping?

**Comment by wooferzfg1** [comment]
Skipping is different (the Segment History element is still there, but the time is null). The only way to have a segment after the null one be a combination of two segments is to modify the XML manually.
