### ISSUE TITLE
Multiple bugs with split colors in the development build

### ISSUE THREAD

**Issue by reijerzzz** [LiveSplit/LiveSplit#300]
I did a speedrun today and found several bugs. I'll add links to the twitch vod so you can see for yourself.

-[Bug 1](http://www.twitch.tv/raynius_/b/677563045?t=24m03s): I was able to save 2.43 seconds and saved 2.57, but it didn't show up as a gold split. (It did show up as gold on the graph.

The same happened [here](http://www.twitch.tv/raynius_/b/677563045?t=11m47s)

-[Bug 2](http://www.twitch.tv/raynius_/b/677567834?t=45s): The split was gold, but after I finished the next split, it lost its rainbow effect and became light red.

-[Bug 3](http://www.twitch.tv/raynius_/b/677567834?t=25m22s): The split was dark red, but after I finished the next split, it became light red.

*****

For this run, I used two different instances of LiveSplit. The one on the top right has a subsplits component always showing subsplits. It has rainbow splits enabled.

I used the autosplitter of Portal 2 and was comparing against Game Time.

I hope this bug report is useful even though I'm not sure how to reproduce any of these bugs.

**Comment by wooferzfg1** [comment]
Fixed here: https://github.com/LiveSplit/LiveSplit.Subsplits/commit/084e4f88ade834161947c4eb5f7de52ee7362d48
