### ISSUE TITLE
[Bug?] Missed splits stat appears to be incorrect

### ISSUE THREAD

**Issue by jhobz** [LiveSplit/LiveSplit#320]
See https://splits.io/5af/stats and compare to https://splits.io/5af. Stats page claims 4 splits were missed but only 2 were. Could it be doubling due to segment length? Or perhaps could there be two splits that were undone and re-split over the course of the run?

**Comment by wooferzfg1** [comment]
This isn't really the place for this issue (since it's splits.io related rather than LiveSplit related). You should report it here instead: https://github.com/glacials/splits-io/issues

**Comment by jhobz** [comment]
yeah sorry I had both tabs open and placed it in the wrong one
