### ISSUE TITLE
Null-Bytes when saving splits, layouts and settings

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#324]
This apparently is a problem in the dev build and could be caused by the changes made in #269

**Comment by reijerzzz** [comment]
Is there a way you can fix your splits after this happens?

**Comment by CryZe** [comment]
It's not that much of a bug. It just increases the file size and splits i/o has issues with it. It'll fix itself after you save with a dev build / normal build that doesn't have this issue anymore.

**Comment by reijerzzz** [comment]
Oh, sorry. I thought this was about the tweet I sent you a minute before you opened this issue.
