### ISSUE TITLE
Resetting very slow

### ISSUE THREAD

**Issue by drtchops** [LiveSplit/LiveSplit#325]
When split history builds up, resetting starts to be slow (can take over a second). When an autosplitter resets and starts splits on the same frame or very close together, this causes the start to be delayed until the reset has finished.

Example: Skyrim resets and starts on the same frame. Me and gr3yscale's starts are delayed almost a second when using auto reset. We can move the reset back but only by about a second, which would just delay the problem.

**Comment by fatalis** [comment]
used profiler and found the problematic lines:

https://github.com/LiveSplit/LiveSplit/blob/8ad2ed46f65e8b6f82b17ad73b7ad010c56700b8/LiveSplit/LiveSplit.Core/Model/Comparisons/AverageSegmentsComparisonGenerator.cs#L48

https://github.com/LiveSplit/LiveSplit/blob/8ad2ed46f65e8b6f82b17ad73b7ad010c56700b8/LiveSplit/LiveSplit.Core/Model/IRun.cs#L144

**Comment by wooferzfg1** [comment]
Can someone upload splits that take forever to load and link them here? Would be useful for testing.

**Comment by fatalis** [comment]
https://www.dropbox.com/s/j0xhw3j0rx1wfq4/skyrim_any.lss?dl=0
