### ISSUE TITLE
Showing Real Time World Record of Game Time game is flawed

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#374]
It currently shows the Real Time of the Game Time World Record, which might be pretty slow, so it might assume your local time is actually World Record instead, which it probably isn't.

**Comment by wooferzfg1** [comment]
It should probably show the Real Time World Record all the time, but I'm not sure.

**Comment by wooferzfg1** [comment]
Another option would be to only use the category's default timing method (rather than the current timing method in LiveSplit) when comparing the WR on Speedrun.com to the local PB time.

**Comment by CryZe** [comment]
Yeah, I think that's the best solution. No one cares about the Real Time of the WR of a Game Time timed game anyway.
