### ISSUE TITLE
Automatically choose Timing Method upon opening Splits

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#378]
By implementing a "Default Timing Method" to compare against, the user wouldn't need to manually switch between the Timing Methods for the individual games.

**Comment by wooferzfg1** [comment]
I'm not sure if this is a good idea unless we can figure out a way for the user to easily know what the current timing method is.

**Comment by CryZe** [comment]
This could also be just a setting: Automatically choose Timing Method upon opening Splits

I think this is not confusing as people need to know the Default Timing Method of the game anyway.

On that note: We should probably show the Timing Method in the Rules if it's not Real Time (distinguish between Game Time and Real Time without Loads)

**Comment by wooferzfg1** [comment]
We should also probably store the last used timing method in the Settings for each set of splits.

**Comment by wooferzfg1** [comment]
I guess we could solve this with whatever we do for #384
