### ISSUE TITLE
Portal 2 autosplitter not working in livesplit 1.6

### ISSUE THREAD

**Issue by reijerzzz** [LiveSplit/LiveSplit#394]
Basically what the title says, It works perfectly in 1.5, but it doesn't in the development build. I tried disabling and enabling and I tried to make new splits but it didn't help.

The timer doesn't start automatically, and if I start it manually the game time stays at 0.

**Comment by fatalis** [comment]
yep, will be fixed when 1.6 is released

**Comment by reijerzzz** [comment]
Is there a way around it for now, or do I have to wait for 1.6 before doing runs again?

**Comment by CryZe** [comment]
@fatalis Is this the Namespace issue or something else? O.o

**Comment by fatalis** [comment]
@reijerzzz just use 1.5
@CryZe 64 bit issue since livesplit reads modules other than mainmodule

**Comment by CryZe** [comment]
Oh, nvm. I read this as his Auto Splitter not working, not yours xD

**Comment by reijerzzz** [comment]
I can't use 1.5 because I used my splits in the 1.6 version and it can't open my splits.

**Comment by CryZe** [comment]
You can open them in this special build which saves them as 1.5 again: http://puu.sh/jMYcX.zip

**Comment by reijerzzz** [comment]
Thanks!
