### ISSUE TITLE
ComponentFactories should reload when a new DLL autosplitter is downloaded

### ISSUE THREAD

**Issue by fatalis** [LiveSplit/LiveSplit#404]
If a dll autosplitter has a seperate UI component (see Halo) that's downloaded with it, you have to restart in order for it to show up in the layout editor.

**Comment by wooferzfg1** [comment]
Maybe just reload only the new .dll file(s) rather than all the factories?

**Comment by CryZe** [comment]
404 Component Not Found ![Keepo](http://a.deviantart.net/avatars/k/e/keepoplz.png?2)

**Comment by wooferzfg1** [comment]
^
