### ISSUE TITLE
CPU Usage increasing over time

### ISSUE THREAD

**Issue by FlorentUguet** [LiveSplit/LiveSplit#409]
Don't know if it has already been reported or not, but Livesplit's CPU usage increases over time, even when the software is not being used.

You can see, for example at the end of that video https://www.youtube.com/watch?v=2ujWVU6j_gc that the timer has a lot of freezes due tu its CPU usage.

I run Windows 8.1 on a i5 4460 and a GTX970.

**Comment by CryZe** [comment]
Is that the OBS plugin?

**Comment by FlorentUguet** [comment]
No, it's the main Livesplit program

**Comment by CryZe** [comment]
Can you test the Dev Build and see if it's still happening there?

**Comment by FlorentUguet** [comment]
Okay, I tell you as soon as I can

**Comment by wooferzfg1** [comment]
You actually made sure in Task Manager that it's LiveSplit that is increasing in CPU usage, right (and not some other program like OBS)?

**Comment by FlorentUguet** [comment]
Yes, I made sure it was LiveSplit
After 15-20 minutes of using it, it would grow to 15% of my CPU, and start freezing, it'd stay at 15% even when idle.

The Dev build is fine, it is at 0% CPU when it's idle, and doesn't get over 3-5% when in use. So the Dev Build is fine, thank you !

**Comment by wooferzfg1** [comment]
Alright, that's very weird but I'm glad it works. Let us know if it happens again in the future.
