### ISSUE TITLE
Add 00:00:00 as a Timer Format

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#425]
https://twitter.com/Cereth_/status/641991771157889024

**Comment by wooferzfg1** [comment]
what about 00:00:00.00?

**Comment by CryZe** [comment]
if we don't have that, then yeah, that tol

**Comment by wooferzfg1** [comment]
I'll probably do 2 combo boxes next to each other (one for the number of leading zeroes and the other for the accuracy)

**Comment by CryZe** [comment]
Sounds like a good idea
