### ISSUE TITLE
Request for a "Start at..." feature

### ISSUE THREAD

**Issue by Zamiell** [LiveSplit/LiveSplit#426]
In WSplit, you can right click the timer and select "Start at...". A window pops up that allows you to select a start offset.

LiveSplit has a similar feature: the "Start Timer at..." section in the "Edit Splits" window. However, this functions a bit differently.

Let's examine the use case of a speedrun tournament that is rebroadcasting a screen capture of several different racers along with a screen capture of a local LiveSplit for viewer reference. (Such tournaments happen on many channels, such as the bostv channel regularly viewed by 2K+ people.) In such a scenario, it is hard for the broadcaster to start his LiveSplit start in conjunction with the actual racers, so it is best to wait for it to start and then use a "Start at..." feature to sync with the racers. However, after 15 minutes or so, the race is over, and it is time to re-sync the timer again. Or, alternatively, maybe the rebroadcast shifts to a different race (similar to what Cosmo did in his famous 74-person OoT puzzle race), and the timer needs to be updated once again.

What would the keystrokes be for such an action in LiveSplit?

1. Alt-tab to LiveSplit
2. Press the menu key
3. Press e
4. Press enter
5. Use the mouse to manually highlight all of the text in the "Start Timer at" box. <--- terrible
6. Type in the new time
7. Press enter.
8. Press the start timer hotkey

Contrast this to the sequence of actions necessary in WSplit:

1. Alt-tab to Wsplit
2. Press the menu key
3. Press e
4. Press enter
5. Type in the new time
6. Press enter.

WSplit is significantly better in 3 ways:

* WSplit doesn't involve any use of the mouse.
* WSplit automatically starts the timer once the initial time has been entered. In this context, it is completely logical to do so, since we run the risk of immediately get out of sync again if the timer is not started.
* WSplit knows this is an action that will only occur once. Subsequently, upon a timer reset, it will correctly set it to 0 instead of back to the initial set at time.

With these things in mind, my proposition for LiveSplit is as follows:

* Implement the "Start at" feature similar to the way WSplit does it - from the main right-click menu. Selecting the option will open a sub-window with the cursor ready to type in numbers.
* This is the most intuitive spot to put it and users looking for this functionality will completely miss it in the "Edit Splits" section, since **starting at a particular time has nothing to do with setting up splits**.
* This feature should co-exist with the "Start Timer at" feature in the "Edit Splits" section, since that is meant to be used for repeated trials, while the "Start at..." feature is meant to be used once.
* Ultimately, this sub-window/feature should be accessible from a global hotkey. This would greatly improve upon both the 8 steps in LiveSplit and the 6 steps in WSplit.

I'm imagine the programming work for this tiny feature would be trivial, so please consider this request. ;)

**Comment by wooferzfg1** [comment]
Just change "Start Timer At..." in Edit Splits? How is that different from what WSplit has?

**Comment by Zamiell** [comment]
I've rewritten the original post to be much more verbose. Thanks for your time.

**Comment by wooferzfg1** [comment]
I understand your point, but we don't want to have the same feature twice just to save a few clicks. It just ends up bloating the program.

**Comment by Zamiell** [comment]
It's not the same feature twice; I've clearly established that it functions differently in 3 separate ways.

**Comment by wooferzfg1** [comment]
It functions slightly differently but it's essentially the same feature, and all it does is it saves 2 steps.
