### ISSUE TITLE
Component Containers

### ISSUE THREAD

**Issue by puri-puri** [LiveSplit/LiveSplit#427]
I'd like to reduce the amount of space that my LiveSplit layouts take up, while also having access to all the info that it can provide. My request is for component containers that can cycle through components based off a timer, like a slideshow.

Container 1: Current Run [15s per element]
---Last Segment
---Possible Time Save
Container 2: Run Stats [30s per element]
---Sum of Best
---WR
---Current Pace

**Comment by wooferzfg1** [comment]
I think @CryZe had this idea before. We'll definitely have this.

**Comment by CryZe** [comment]
There already is an issue for it though: https://github.com/LiveSplit/LiveSplit/issues/305
