### ISSUE TITLE
Unable to use 32 bit libraries with LiveSplit 1.6

### ISSUE THREAD

**Issue by AdamPrimer** [LiveSplit/LiveSplit#439]
I am looking for advice from others that might know more about this than I do.

I am the author of the Escape Goat 2 autosplitter which took me quite a long time to create due to it being in C# with very volatile memory. I was unable to find any way to hook the game via static pointers or via scanning memory for function signatures (as I was able to do in another autosplitter I created, Ori and the Blind Forest).

My eventual solution was to use a library called Microsoft.Diagnostic.Runtime. This library is essentially a very nice wrapper for the CLR which will bind to the memory of a given process (in this case the 32bit Escape Goat 2 binary) and essentially allows you to traverse the heap to find memory values.

The issue is, this library requires the monitoring executable, and the target executable to be running the same architecture. I am not entirely sure why this requirement is essential, but the library is quite large and I will admit knowing only a small amount of its internals which I learned while trying to build the autosplitter.

With LiveSplit being 64bit now, this library refuses to hook the 32bit process essentially leaving the autosplitter as a paperweight. 

I spent a very long time trying to get this autosplitter to work and to find a method that would work, so I am currently at a loss as to how to approach trying to fix this issue. I am hoping the more experienced members here may be aware of another autosplitter using this library or similar, and provide some guidance as I am currently out of ideas.

Any input would be appreciated.

PS: I know this technically isn't a "bug" but a compatibility issue, I didn't know where else to put this.

https://github.com/AdamPrimer/LiveSplit.EscapeGoat2
https://github.com/Microsoft/clrmd

**Comment by AdamPrimer** [comment]
Since posting this I came up with the idea of launching the autosplitter as a seperate executable running as a 32 bit process, and then communicating back to a LiveSplit component via stdin and stdout.

I have pushed a version of the autosplitter making use of this, but it now requires downloading an extra executable alongside the dll. This is obviously unideal, but it seems to work for now.

I will leave this issue open in case there is some nice solution I'm not thinking of, but feel free to close this if you think my workaround is the best that can be done.

https://github.com/AdamPrimer/LiveSplit.EscapeGoat2

**Comment by fatalis** [comment]
The reason is stated [here](https://github.com/Microsoft/clrmd/blob/master/Documentation/GettingStarted.md#what-do-i-need-to-debug-a-crash-dump-with-clrmd). It doesn't look like it's possible to work around it. Your IPC solution is probably the best bet right now. Alternatively you can force either the game (if it doesn't load any native x86 DLLs) or LiveSplit to run in a different architecture by patching the flags in the .NET directory of the PE, but that's an even uglier solution.

Since a lot of games are now being made in .NET, it's probably a good idea for the next version of LiveSplit to distribute as both x86 and x64.
