### ISSUE TITLE
Just watch this picture I dont know what's the problem

### ISSUE THREAD

**Issue by Aethology** [LiveSplit/LiveSplit#440]
Just watch this picture I dont know what's the problem with my livesplit 1.6. I downloaded this right from forum, it was like this at the beginning. Then I re-installed it, still the same. I guess this is not a ''bug'' but I dont know what to do, it splits the PB time too when I split. Any helps?

Picture: http://puu.sh/kr6Ux/887f63764b.png

**Comment by CryZe** [comment]
I'm not seeing any problems in the picture. Can you explain it in a more detailed way?

**Comment by Aethology** [comment]
Well basicly I wanna make the splits look like this: http://puu.sh/kr92x/8eb04facb0.png , the thing is that when I split, it should basicly show the - / + time, and PB time next to it, but it splits both times. When I asked about this, nobody really didn't know what to do lol. So I decided to write it down here.

**Comment by reijerzzz** [comment]
I think what he's saying is that he would like to show the time he split in his pb instead of the time he split in the current run.

So he wants the hero's sword split time to say 10:54 instead of 10:50 in the second screenshot he posted.

**Comment by Aethology** [comment]
Quite right, but like in hero's sword i want my PB time shown at right, and SPLIT time at left. Just like in second picture. This is how my livesplit looks when I dont split anything:  http://puu.sh/kr9FJ/3a57bc7c90.png . Bomb (1) -1:49 1:50 . Thats how I want it to look! Not like:
 Bomb (1) -1:49 0:01

**Comment by reijerzzz** [comment]
I'm sorry, but there's no setting to change this.

**Comment by wooferzfg** [comment]
I also think it would be very confusing if it was allowed as a setting because there's no way to differentiate between the past run times and current run times.

**Comment by Aethology** [comment]
Well what the heck should I do?

**Comment by wooferzfg** [comment]
Just have it show the split times instead of the PB times?

**Comment by wooferzfg** [comment]
The image on the LiveSplit site shows Split Times for splits before the current split and PB Times for splits after.
