### ISSUE TITLE
SpeedRunsLive - .done issue

### ISSUE THREAD

**Issue by Harest** [LiveSplit/LiveSplit#447]
Hi,  

We did a "test" tournament yesterday for a french event and we did many SRL races. Two on DuckTales and two on Super Monkey Ball in a row. And for the finale DuckTales / SMBall and Spelunky.  

I don't remember exactly when but i think right after the 2 DuckTales races, the .done wasn't automatic. In any case, if that could help, i've 6 named splits for DuckTales, "no split" (by default you've one with empty name) for SMBall (where if i'm remember correctly the issue started and i had to .done manually in the irc window opened by LiveSplit), and 10 splits for Spelunky (shortcuts + olmec).  

If you need any additional information, feel free to ask. Apparently there's no log, but maybe i'm wrong and this could help you find the issue. Right now if i remembered correctly and the issue started with SMBall, maybe it's related to the fact there's just the timer and no named split, i don't know. If needed, i could have the certitude by checking the VOD.

_I'm using LiveSplit v1.6.2._

**Comment by wooferzfg** [comment]
Was the timer start still automatic?

**Comment by Harest** [comment]
Yep, no problem with the timer, it started properly.

**Comment by wooferzfg** [comment]
Hmm, this is weird. I can't really see what the problem could be aside from LiveSplit thinking that the race has ended already or something...

**Comment by Harest** [comment]
I know many participants got the same issue, i could ask them if they remember when it started, if it was for the 4th race too or not.

**Comment by wooferzfg** [comment]
Not planning to work further on the SRL integration.
