### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Inferno989** [LiveSplit/LiveSplit#448]
I'm just going to be blunt and say I'm horrible with technology, that said, I need help with downloading the actual live split. When I try to compile LiveSplit with visual studio this error pops up.

"Migration Report LiveSplit.Tests\LiveSplit.Tests.csproj: The application which this project type is based on was not found."

If anyone could give me a solution to this I'd appreciate it.

**Comment by wooferzfg** [comment]
Are you using VS 2015?

**Comment by CryZe** [comment]
Just unload / exclude that project. It think you might need a bought version of Visual Studio for Unit Testing.
