### ISSUE TITLE
LiveSplit malware issue

### ISSUE THREAD

**Issue by Skeletonkillman4** [LiveSplit/LiveSplit#449]
I went to download LiveSplit from the website, but when I do, every time I try to open it, I get a message telling me it has Trojan malware.

**Comment by fatalis** [comment]
False positive.

**Comment by Skeletonkillman4** [comment]
?

**Comment by wooferzfg** [comment]
Just disable your virus scanner temporarily or something? It's obviously not malware.

**Comment by Skeletonkillman4** [comment]
Will do.
