### ISSUE TITLE
[Feature Request] Note windows with segment triggers

### ISSUE THREAD

**Issue by jhobz** [LiveSplit/LiveSplit#458]
It would be nice to be able to integrate route notes into LiveSplit instead of having to use a Pastebin or Google Doc that you need to manually scroll (and can easily lose your place in). Basically you'd write a file (preferably with Markdown support) with a line to declare a segment and end that declaration and then whenever that segment starts, a window pops open (akin to the SRL window) that displays your info. Notes would ideally be saved independently of splits files (like layouts), but would have a spot in the splits file to tie a notes file to a set of splits (so you wouldn't have to manually set the notes file every time you change a game or category). My rough idea of what a splits file would look like:

```xml
<game>Game</game>
<category>Category</category>
<author>Me</author>
<segment title="MyfirstSegment">
# MyFirstSegment
I would include some notes here with **Markdown** support:
* Equip this thing
* And this other thing
* Oh and don't forget that thing obviously
</segment>
<segment title="MySecondSegment">
You get the idea
</segment>
```

You would not need notes for every segment and segments should probably be nestable for subsplits (in case you have multiple subsplits with the same name like "-Checkpoint" or something).

**Comment by jhobz** [comment]
I'd love to help implement this, but I have no idea where to start since I'm not very familiar with the LiveSplit architecture. Would this be more suited as a plugin, or a regular component?

**Comment by jhobz** [comment]
Also, the ability to choose between a local or remote file (maybe with some built-in integration with speedrun.com?) would be useful.

**Comment by jhobz** [comment]
Just realized this is heavily related to #261. The two could probably be merged.

**Comment by wooferzfg** [comment]
Closing this because this issue is very similar to the Route Component one.
