### ISSUE TITLE
Deleting best time fills all previous attempts with bad times?

### ISSUE THREAD

**Issue by ROMaster2** [LiveSplit/LiveSplit#464]
https://splits.io/d5i - GrandStarYoshi's Super Mario Sunshine split file

A few days ago he deleted the time in his best split for Bowser. For whatever reason this resulted in all of his RealTime previous attempts for Bowser to be wiped and replaced with 01:08:20. Something also happened to the first segment's history but I don't know what he did during that time.

He can be contacted at http://www.twitch.tv/grandstaryoshi or https://twitter.com/GrandStarYoshi

**Comment by wooferzfg** [comment]
i'm 90% sure that he typed it wrong as 1:08:20 and then retyped it as 1:08.20 when trying to change his best segment time

**Comment by ROMaster2** [comment]
We'll have to wait until he's on to check that.

**Comment by ROMaster2** [comment]
https://twitter.com/GrandStarYoshi/status/673921747075207170 -- Looks like he did just that.

Maybe have something to prevent absurdly large times from being entered? I don't think this is the first time I've encountered this problem. I think zfg had this problem before.

**Comment by wooferzfg** [comment]
Hard to say what "absurdly large" would be..

**Comment by ROMaster2** [comment]
Maybe if it's larger than the average split it'll pop-up a warning?
