### ISSUE TITLE
Only part of a ReadProcessMemory or WriteProcessMemory request was completed

### ISSUE THREAD

**Issue by tduva** [LiveSplit/LiveSplit#482]
I got this error with an ASL autosplitter. First I got the error, then it told me `level` isn't defined (which is a state variable). After that `level` was defined, but stuff I define in init wasn't available, so I assume the init-method didn't run because of the error.

I'm not quite sure what this error means and whether it can be fixed, or if there should be a workaround in the ASL script to still run init despite an initial error (it only seems to happen directly after connecting to the game).

I got this error while running the regular downloaded version of LiveSplit with a ASL script in the Layout (DebugView): [error1.txt](https://github.com/LiveSplit/LiveSplit/files/103863/error1.txt)

It also occured when running in Debug mode out of Visual Studio, not sure if it's the same error/cause but it at least seems similiar: [error2.txt](https://github.com/LiveSplit/LiveSplit/files/103862/error2.txt)

**Comment by fatalis** [comment]
Yeah, it's a known issue with ModulesWow64Safe, but IIRC it's harmless and shouldn't affect the script. It can occur when closing the game as well. The bug should be fixed if possible though, especially if it causes the issue you're saying. I looked at the code briefly and it doesn't seem like that can happen though.

**Comment by tduva** [comment]
It doesn't seem like what can happen? If the error occurs when updating the memory values after attaching the game and before init runs, won't it just skip init and go right to the other methods? Or does that error not stop execution? Either way, a method I attached to `vars` in init wasn't available after that error, so I assume init didn't run.

When I cause an error in init itself (e.g. accessing a non-existant dictionary key), then it doesn't execute the code after that. Not sure if that kind of error would be different in regards to stopping executing compared to the other error not coming from within the ASL script.

Funnily enough, when I just tested the on-purpose error in init again, the memory reading error occured again when I started the game. So I had the script loaded and running, I started the game, the memory reading error occured and I got no debug output from init or after init in TryConnect. Modifying/saving the ASL script again it ran normally. Modifiying/saving the ASL script to include the on-purpose error in init again the on-purpose error occured as expected and didn't execute the parts in TryConnect() after init.

I included the debug output from Visual Studio and commented it a bit: [error3.txt](https://github.com/LiveSplit/LiveSplit/files/103978/error3.txt)

**Comment by fatalis** [comment]
You're right. [this line](https://github.com/LiveSplit/LiveSplit.ScriptableAutoSplit/blob/92e4f3c14f25c93bfd26f7af8469be70bf529a83/ASL/ASLScript.cs#L78) should be after line 85.

**Comment by tduva** [comment]
But `Game` needs to be set when init is run, because it is referred to in init. There would have to be another variable that checks if init has been run successfully, because there is no point in running the rest of the script if init didn't even run properly. Maybe put init separately and run it until it run successfully. Not sure if trying to connect to the game again everytime that error occurs would be better or worse.
