### ISSUE TITLE
Can't save more than 1 lsl / lss file

### ISSUE THREAD

**Issue by kazoks** [LiveSplit/LiveSplit#492]
Hallo!

I like to speed run games, but right now i can't because, if i try to make new lsl / lss file it will open already saved one and if i want to clear everything it will clear everything in already saved one as well, so i can have only 1 active lsl / lss file at the moment, and if i wanna create new one, I need to delete previous, please help!

Thanks!

**Comment by wooferzfg** [comment]
what does "Save as..." do for you?

**Comment by kazoks** [comment]
Save as just save both of my lsl / lss files and after that i can make as many new files as i want but all will be the same as 1st one.

**Comment by wooferzfg** [comment]
so what happens if you open a split file, modify it, do Save As and save it as something else, and then open the original split file? are the new modifications still there?

**Comment by kazoks** [comment]
It worked, kinda.
I made new split and layout file with game #1 and then with game #2 
I opened #1 split file and then #1 layout file everything was good.
Then i opened #2 split file and it showed me #1 layouts, so i close it and opened #2 layout file and again #2 split file and and now everything was good with game #2 files too.
Then i opened #1 split file again, and now it showed #2 layouts so i closed it and opened #1 layout files and then again #1 split file and now everything was ok. and so on and on.....
I hope you get it, mindfuck. x/

**Comment by wooferzfg** [comment]
The thing is that split and layout files are completely separate. So changing the split file won't change the layout.

**Comment by kazoks** [comment]
I see.
But when i speed run which file I need to use split or layout or it doesnt matter?

**Comment by wooferzfg** [comment]
The split file stores times and information about the game, category, etc. The layout file just controls the appearance of LiveSplit. Most people just use one layout file and multiple split files (one for each category that they run).

**Comment by kazoks** [comment]
Oky, thanks a lot, thats all i wanned to know. :)

**Comment by wooferzfg** [comment]
no problem
