### ISSUE TITLE
Livesplit not even running

### ISSUE THREAD

**Issue by rendable** [LiveSplit/LiveSplit#501]
I have windows 10 on my computer and whenever I click the .exe it does not open up. I've tried running as administrator as well. I've read the FAQ and have watched the video. In the video tooshi opened the program with no problem. It just does not want to open. Sorry that this is a very basic explanation, but I'm not sure what else to type.

**Comment by wooferzfg** [comment]
you unzipped it right? lol

**Comment by rendable** [comment]
Lol yes, but when I unzip it, there are like, dozens of files and I'm not
sure which one to try, and the ones that I have tried aren't opening. I'll
retry downloading it from the site once again

**Comment by rendable** [comment]
[image: Inline image 2]I've tried opening both .exe files that I have
circled and nothing happens. I've moved the first .exe on to my desktop to
open it, and it has the live split logo so I'm sure it's the right one. But
it still doesn't run

**Comment by fatalis** [comment]
do you have avast antivirus?

**Comment by rendable** [comment]
I didn't even know that was a program until just now lol. So that would be
a no.

**Comment by rendable** [comment]
[image: Inline image 1]I got this when I tried to troubleshoot it. Not sure
why it would be incompatible though.

**Comment by Edacaf** [comment]
Do you have an Xbox One controller plugged into your PC? If so disconnect it and try opening again.
