### ISSUE TITLE
LiveSplit fails to open

### ISSUE THREAD

**Issue by Edacaf** [LiveSplit/LiveSplit#509]
When I try to open Livesplit it doesn't open.

It does appear in Task Manager and I have ended the task and also tried ending the process tree and then reopening.

I have deleted it and redownloaded/extracted but it still is not opening.

I have seen some suggestions that it could be my antivirus, but I have allowed it and it is still not opening.

**Comment by fatalis** [comment]
Does 1.6.8 work for you? https://github.com/LiveSplit/LiveSplit/releases/download/1.6.8/LiveSplit_1.6.8.zip

**Comment by Edacaf** [comment]
Unfortunately no. I forgot to say I tried that and 1.5 even but both have the same results.

**Comment by fatalis** [comment]
Has it ever worked for you?

**Comment by Edacaf** [comment]
Yes.

It's been maybe a week or two since I've opened it but I have used it before.

**Comment by fatalis** [comment]
Try deleting `settings.cfg` with LiveSplit closed. If that doesn't work, I don't know.

**Comment by Edacaf** [comment]
I just redownloaded it, extracted, and when trying to open Livesplit I allow permissions.

Looking at that folder I don't even see the `settings.cfg` file.

**Comment by Edacaf** [comment]
It's just located in the Livesplit_1.6.9 folder right?

**Comment by Edacaf** [comment]
I tried deleting the `LiveSplit.AutoSplitters` since that was added since I last used it but I still get the same results. Also when I tried to open Livesplit, `LiveSplit.AutoSplitters` reappears on the file list.

**Comment by wooferzfg** [comment]
can you check your Event Viewer for LiveSplit errors?

**Comment by Edacaf** [comment]
Okay I believe I have it up.

**Comment by Edacaf** [comment]
Do you want me to paste the description?

**Comment by Edacaf** [comment]
"Could not find file 'C:\Users\NAME\Downloads\LiveSplit_1.6.9\settings.cfg'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)"

So it says I don't have the `settings.cfg` file that Fatalis mentioned.

Woofer if you download LiveSplit right now do you see `settings.cfg` in the folder?

**Comment by wooferzfg** [comment]
Well if the settings.cfg file isn't there (which it isn't when you first download), it should just use the default settings. Are there any other errors?

**Comment by Edacaf** [comment]
Sorry for the delayed response, I am hopeful that this can help. I asked a friend to download LiveSplit and he was able to open it just fine, so it's definitely on my end. I tried opening it from a new profile on the computer and from a clean boot with no luck. I even had him send me his already opened copy and the settings file but that didn't work either. 

I may end up having to use WSplit if I can't figure it out, which isn't the end of the world but I do really love LiveSplit and the work you guys have done is appreciated. :-)

`Log Name:      Application
Source:        LiveSplit
Date:          3/5/2016 5:36:07 PM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-AG7H2JI
Description:
Could not find a part of the path 'C:\Users\NAME\Downloads\LiveSplit\Components'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
   at LiveSplit.UI.Components.ComponentManager.LoadAllFactories()
   at LiveSplit.UI.Components.ComponentManager.LoadLayoutComponent(String path, LiveSplitState state)
   at LiveSplit.UI.LayoutFactories.TimerOnlyLayoutFactory.Create(LiveSplitState state)
   at LiveSplit.View.TimerForm.Init(String splitsPath, String layoutPath)
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="LiveSplit" />
    <EventID Qualifiers="0">0</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-03-05T22:36:07.359549400Z" />
    <EventRecordID>1083</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-AG7H2JI</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Could not find a part of the path 'C:\Users\NAME\Downloads\LiveSplit\Components'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
   at LiveSplit.UI.Components.ComponentManager.LoadAllFactories()
   at LiveSplit.UI.Components.ComponentManager.LoadLayoutComponent(String path, LiveSplitState state)
   at LiveSplit.UI.LayoutFactories.TimerOnlyLayoutFactory.Create(LiveSplitState state)
   at LiveSplit.View.TimerForm.Init(String splitsPath, String layoutPath)</Data>
  </EventData>
</Event>`

**Comment by wooferzfg** [comment]
why does it say the path is Users/NAME?

**Comment by Edacaf** [comment]
I took my name out, kind of dumb on my part

**Comment by Edacaf** [comment]
So maybe to be clear or correct myself, it seems that when I first try to start the application LiveSplit appears in my Background Processes, but the problem is it doesn't "go all the way through" to the Apps section of Task Manager. 

Not sure if that helps or not, it does seem to be a problem on my end not LiveSplits but I do appreciate any advice you might be able to give.

**Comment by wooferzfg** [comment]
I have no idea what would cause it to not find the paths of these files, idk, sorry

**Comment by Edacaf** [comment]
No problem, appreciate your time today. I'll still check it out every now and again and see if something clicks to make it work.

**Comment by fatalis** [comment]
Does the `Components` folder exist?

**Comment by adrianzech** [comment]
Same Issue here:

> Protokollname: Application
> Quelle:        LiveSplit
> Datum:         06.03.2016 12:32:15
> Ereignis-ID:   0
> Aufgabenkategorie:Keine
> Ebene:         Fehler
> Schlüsselwörter:Klassisch
> Benutzer:      Nicht zutreffend
> Computer:      Windows
> Beschreibung:
> Das Handle ist ungültig
> 
>    bei LiveSplit.ComponentUtil.ExtensionMethods.ModulesWow64Safe(Process p)
>    bei LiveSplit.ComponentUtil.DeepPointer.DerefOffsets(Process process, IntPtr& ptr)
>    bei LiveSplit.ComponentUtil.DeepPointer.Deref[T](Process process, T& value)
>    bei LiveSplit.ASL.ASLState.GetValue(Process p, String type, DeepPointer pointer)
>    bei LiveSplit.ASL.ASLState.RefreshValues(Process p)
>    bei LiveSplit.ASL.ASLScript.DoUpdate(LiveSplitState state)
>    bei LiveSplit.UI.Components.ASLComponent.UpdateScript()
> Ereignis-XML:
> <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
>   <System>
>     <Provider Name="LiveSplit" />
>     <EventID Qualifiers="0">0</EventID>
>     <Level>2</Level>
>     <Task>0</Task>
>     <Keywords>0x80000000000000</Keywords>
>     <TimeCreated SystemTime="2016-03-06T11:32:15.179451500Z" />
>     <EventRecordID>2968</EventRecordID>
>     <Channel>Application</Channel>
>     <Computer>Windows</Computer>
>     <Security />
>   </System>
>   <EventData>
>     <Data>Das Handle ist ungültig
> 
>    bei LiveSplit.ComponentUtil.ExtensionMethods.ModulesWow64Safe(Process p)
>    bei LiveSplit.ComponentUtil.DeepPointer.DerefOffsets(Process process, IntPtr&amp; ptr)
>    bei LiveSplit.ComponentUtil.DeepPointer.Deref[T](Process process, T&amp; value)
>    bei LiveSplit.ASL.ASLState.GetValue(Process p, String type, DeepPointer pointer)
>    bei LiveSplit.ASL.ASLState.RefreshValues(Process p)
>    bei LiveSplit.ASL.ASLScript.DoUpdate(LiveSplitState state)
>    bei LiveSplit.UI.Components.ASLComponent.UpdateScript()</Data>
>   </EventData>
> </Event>

and

> Protokollname: Application
> Quelle:        LiveSplit
> Datum:         06.03.2016 12:32:15
> Ereignis-ID:   0
> Aufgabenkategorie:Keine
> Ebene:         Fehler
> Schlüsselwörter:Klassisch
> Benutzer:      Nicht zutreffend
> Computer:      Windows
> Beschreibung:
> Das Handle ist ungültig
> 
>    bei LiveSplit.ComponentUtil.ExtensionMethods.ModulesWow64Safe(Process p)
>    bei CompiledScript.Execute(LiveSplitState timer, Object old, Object current, Object vars, Process game, Object settings)
>    bei System.Dynamic.UpdateDelegates.UpdateAndExecute7[T0,T1,T2,T3,T4,T5,T6,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
>    bei LiveSplit.ASL.ASLMethod.Call(LiveSplitState timer, ExpandoObject vars, String& version, Double& refreshRate, Object settings, ExpandoObject old, ExpandoObject current, Process game)
>    bei LiveSplit.ASL.ASLScript.RunMethod(ASLMethod method, LiveSplitState state, String& version)
>    bei LiveSplit.ASL.ASLScript.DoUpdate(LiveSplitState state)
>    bei LiveSplit.UI.Components.ASLComponent.UpdateScript()
> Ereignis-XML:
> <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
>   <System>
>     <Provider Name="LiveSplit" />
>     <EventID Qualifiers="0">0</EventID>
>     <Level>2</Level>
>     <Task>0</Task>
>     <Keywords>0x80000000000000</Keywords>
>     <TimeCreated SystemTime="2016-03-06T11:32:15.193977200Z" />
>     <EventRecordID>2969</EventRecordID>
>     <Channel>Application</Channel>
>     <Computer>Windows</Computer>
>     <Security />
>   </System>
>   <EventData>
>     <Data>Das Handle ist ungültig
> 
>    bei LiveSplit.ComponentUtil.ExtensionMethods.ModulesWow64Safe(Process p)
>    bei CompiledScript.Execute(LiveSplitState timer, Object old, Object current, Object vars, Process game, Object settings)
>    bei System.Dynamic.UpdateDelegates.UpdateAndExecute7[T0,T1,T2,T3,T4,T5,T6,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
>    bei LiveSplit.ASL.ASLMethod.Call(LiveSplitState timer, ExpandoObject vars, String&amp; version, Double&amp; refreshRate, Object settings, ExpandoObject old, ExpandoObject current, Process game)
>    bei LiveSplit.ASL.ASLScript.RunMethod(ASLMethod method, LiveSplitState state, String&amp; version)
>    bei LiveSplit.ASL.ASLScript.DoUpdate(LiveSplitState state)
>    bei LiveSplit.UI.Components.ASLComponent.UpdateScript()</Data>
>   </EventData>
> </Event>

Tried version 1.6.8 and 1.6.9

**Comment by adrianzech** [comment]
It seems my Xbox One Controller is causing this issue.
If i unplug it it works fine.

**Comment by Edacaf** [comment]
WOW that was my problem too!

Thanks so much Adrian!!

**Comment by wooferzfg** [comment]
3 different people with 3 different sets of errors, all caused by Xbox controllers? weird lol

**Comment by dos350** [comment]
had this exact same problem just now on latest stable and dev version as of this date,,,

win 10,. program wouldnt open ,, never had used it b4,,, tried admin etc,, finally see this, unplug controller and it come straight up,,, please fix!

**Comment by tommy606** [comment]
my safeguarded (means no virus until i type in the pin) computer's livesplit **barely** works on my computer if i refuse to type in the pin which i actually dont know anymore and please dont send a windows help request because it is a good reason but if i told you i would get kicked off of github because no minors are allowed on github

**Comment by will0009961** [comment]
go to event viewer -> windows logs -> applications (click on it), if live split is your last application opened, you can click on the newest log and see what it says.
