### ISSUE TITLE
LiveSplit not showing up in OBS

### ISSUE THREAD

**Issue by snakemaster777** [LiveSplit/LiveSplit#518]
Hey so this problem randomly started happening a few days ago. I can see LiveSplit when I open it up, but the window capture on OBS is blacked out. It was working fine before and I didn't change anything. I've tried running as an admin, deleting and remaking the window capture, and several other things and the window is still blacked out in OBS. Is this a LiveSplit bug?

**Comment by wooferzfg** [comment]
if OBS Studio doesn't work, the only thing I can think of would be an issue with Aero being on/off
