### ISSUE TITLE
I can't open my splits!

### ISSUE THREAD

**Issue by kazoks** [LiveSplit/LiveSplit#521]
Hallo!

I reinstalled window and downloaded LiveSplit, and now i cant open my old splits.
They appears as unknown application. Please help! :)

Thanks!

**Comment by wooferzfg** [comment]
what happens if you open LiveSplit, do Open Splits -> From File, and select your splits?

**Comment by kazoks** [comment]
I dont understand now. Yesterday I reinstalled LiveSplit and i was able to open only my layout file but i still couldnt open my split files.
And today everything is ok and im able to open splits too.
Ok, thanks anyways, hehe. ;) :D
