### ISSUE TITLE
Associate with Speedrun.com, hm?

### ISSUE THREAD

**Issue by Glaived** [LiveSplit/LiveSplit#525]
![capture](https://cloud.githubusercontent.com/assets/1835170/14063748/46186662-f3df-11e5-9310-6c570eb3e72d.PNG)

sorry to ask here, but what is this option? What to put in the box? :c

**Comment by wooferzfg** [comment]
The URL of your speedrun.com run, for example: http://www.speedrun.com/run/9mex1x8z

**Comment by philipbower122** [comment]
doesnt work?

**Comment by NoTeefy** [comment]
> 
> 
> doesnt work?

Could you be more specific what functionality you're talking about? That button helps generating splits.io files for your submitted run. Works as intended for me...
