### ISSUE TITLE
Splits don't start

### ISSUE THREAD

**Issue by Giga4945** [LiveSplit/LiveSplit#530]
I have set everything up, ran as admin, tried numerous hotkeys, but my splits will not start. They will sometimes randomly for seemingly no reason start and split 5 times. In which case me reset hotkey works fine, otherwise I just cannot start any split.

While focused on the window. while not, when global hotkeys are on and off, it just doesn't seem to work for whatever reason.

**Comment by wooferzfg** [comment]
Weird... can you send me your event logs? http://pastebin.com/M3n52ABV

**Comment by Giga4945** [comment]
https://db.tt/wOZthyMb

These are all the errors between now and when I was trying to get livesplit to work. I tried installing the OBS plugin also to see if that would fix anything, but my OBS just crashed instead.

**Comment by Giga4945** [comment]
I re-downloaded the program for a second time, and now the splits actually work. I can't tell you why, but the error from before was still there, and it also didn't work on my first try of re-downloading. Really am unsure as to what caused the issue, however I can now use the program.
