### ISSUE TITLE
Start / Split hotkey not working (all others do)

### ISSUE THREAD

**Issue by jwwisgerhof** [LiveSplit/LiveSplit#539]
Hi,

Trying to use this software, but cannot get the Start / Split hotkey to work. All other hotkeys work as expected. I can manually start the split (right click -> control -> start) but not use the hotkey. The same goes for split - works via the right click menu but not the hot key.

**Useful info**
1. Tried changing the hotkey (none worked)
2. Tried turning global on / off 
3. Tried using the hotkey with the LiveSplit window focused (and without)
4. All other hotkeys work, even if changed to the "Start / Split" default (num1)
5. Windows 10 64bit. LiveSplit 1.6.9 (also tried dev build, same issue)
6. Running as admin changed nothing

**Comment by jozefspisiak** [comment]
I have similar problem, I can start with hotkey but never split (it is the same hotkey) or reset. I have no clue what could be the problem and why it allows me only to start it. Did you have any progress in solving yours?

**Comment by jozefspisiak** [comment]
Update, on reddit someone suggested to try to map the start split to xbox controller and it works! Hope this helps someone.
