### ISSUE TITLE
How to scroll splits?

### ISSUE THREAD

**Issue by ghost** [LiveSplit/LiveSplit#548]
Topic, how do I scroll up and down?

**Comment by wooferzfg** [comment]
Using the mouse wheel while LiveSplit is selected should work.

**Comment by skallandt** [comment]
I am having this issue as well, and simply using the mouse wheel (or laptop touchpad movement) while LiveSplit is selected doesn't work. I have LiveSplit 1.6.9. Is there a setting that needs to be activated that I can check?

**Comment by wooferzfg** [comment]
No, but it might only work with a regular mouse.

**Comment by skallandt** [comment]
My actual mouse does not work either (and it does scroll web pages normally). 

I tried to uncheck "always on top" so I could know that I'm selecting LiveSplit, and this does not work either....

**Comment by seanlaguna** [comment]
Also having this issue. LiveSplit will not scroll.

**Comment by wooferzfg** [comment]
This should be resolved in LiveSplit 1.8.
