### ISSUE TITLE
ASL: Separate event triggering from event handling

### ISSUE THREAD

**Issue by faultyserver** [LiveSplit/LiveSplit#552]
In the current state of ASL, we have actions that describe event _triggering_, but not actions that describe event _handling_. This means that, for instance, people often use the `reset{}` action block to determine when to trigger a reset, and use the `update{}` block to perform actions that need to happen when a reset event occurs, such as zeroing timers, clearing lists, etc.

This clutters the `update{}` bock and requires a conditional block that looks similar to

``` C#
if (timer.CurrentPhase == TimerPhase.NotRunning && vars.prevPhase == TimerPhase.Running) {
  // ... do reset stuff
}
```

I would like to see new actions (blocks?, maybe a different, more semantic name) such as `onSplit{}` and `onReset{}` to separate this event handling from the event triggering.

Here's a full sample that keeps track of which split the player is on and splits based on that information:

``` C#
state("event_hooks_sample") {
  int state : ...;
}

init {
  // The possible values of `state`
  vars.level_end_state  = 0x000100;
  vars.main_menu_state  = 0x000001;
  vars.cutscene_state   = 0x010000;

  // The list of all splits in this category.
  vars.splits = new List<string>{
    "First Level",
    "Second Level",
    "Last Level"
  };

  // The list of splits that have been done in the current run.
  vars.current_splits = new List<String>();

  // The name of the next split that will occur.
  vars.next_split = vars.splits[0];
}

split {
  bool reached_end_of_level = current.state == vars.level_end_state &&
                              old.state     != vars.level_end_state;
  bool entered_cutscene     = current.state == vars.cutscene_state &&
                              old.state     != vars.cutscene_state;
  bool on_last_level        = vars.next_split == "Last Level";

  // Split if the player has reached the end of a level. If the player has
  // finished the last level, split when they enter the cutscene.
  return reached_end_of_level || (on_last_level && entered_cutsecene);
}

reset {
  // Reset if the player is on the main menu.
  return
    current.state == vars.main_menu_state &&
    old.state != vars.main_menu_state;
}

onSplit {
  // After a split has occurred, add the old next split to the list of
  // passed splits and determine the new next split.
  vars.current_splits.Add(vars.next_split);
  vars.next_split = vars.splits[vars.current_splits.Count - 1];
}

onReset {
  // If the splits get reset, clear the current split list and reset
  // next_split to the first split.
  vars.current_splits.Clear();
  vars.next_split = vars.splits[0];
}
```

Notice that the script does not even contain an `update{}` block. This means there are no conditionals to worry about, and the logic is syntactically separated into meaningful locations rather than bundled into one big block.

Addtionally, the logic in `split{}` is _only_ the logic that determines if a split should occur, and does not contain any logic about what should happen after a split occurs.

Ideally, this could also be expanded into `beforeSplit{}` and `afterSplit{}` blocks to provide a full set of hooks.

**Comment by Anty-Lemon** [comment]
It would be nice to have them implemented into ASL, but for now LiveSplitState's events can be used

```
timer.OnReset += (object sender, TimerPhase e) => {
  // ... do reset stuff
}
```

**Comment by faultyserver** [comment]
I had no idea those events were exposed like that already. I'll definitely be using those until it becomes part of the syntax. Thanks!

**Comment by faultyserver** [comment]
It would also be nice if we could get an `onSettingsUpdated{}` block, so that scripts can react to changes in `settings`, rather than just using them passively.

An example just came up where the user could select which splits will be made automatically, and the current implementation of that would require something like `if next split should be 'c' but !settings['c']: next split should be d` for any splits that are optional. With an `onSettingsUpdated{}` block, though, this could be simplified to a single line determining the full list of splits to be made. Some psuedocode:

```C#
init {
  splits = ['a', 'b', 'c'];
  // Default to including 'a', 'b', and 'c'. Probably not the right syntax
  settings.add('a', true);
  settings.add('b', true);
  settings.add('c', true);
}

onSettingsUpdated {
  splits_for_run = splits.FindAll(split => settings[split] == true);
  ... // logic for actually starting the splits (return true and such)
}

split {
  if(splits_for_run.Contains(current_split)) {
    // perform split logic
  }
}

onSplit {
  current_split = <next split in splits_for_run>;
}
```

**Comment by just-ero** [comment]
The issue is resolved. `onStart`, `onSplit`, and `onReset` have been added.
