### ISSUE TITLE
[Question] Doom + auto-split not works?

### ISSUE THREAD

**Issue by CHEF-KOCH** [LiveSplit/LiveSplit#568]
Hey, thanks for the wonderful tool!

I have a question or issue with Doom 2016 (PC - Steam). Somehow I not get it working, livesplit not doing anything and the configuration is a bit confusing. 

Why there exist settings twice and which one do I need? I tried both together and only one of them but livesplit won't start?! Do I need to press something?!
![dwdwt](https://cloud.githubusercontent.com/assets/727123/16884850/ede504c0-4acb-11e6-932d-42d08809c49f.png)
 

I used this script (.asl) from [here](https://raw.githubusercontent.com/TheFuncannon/Autosplitter.Doom/master/Doom.asl). 

What do I not see here?

**Comment by wooferzfg** [comment]
You should be able to just set your game to Doom and activate the Auto Splitter. I don't think you need to have Scriptable Auto Splitter in your layout.

**Comment by CHEF-KOCH** [comment]
Okay, let me try. :+1:

**Comment by CHEF-KOCH** [comment]
Close, if anyone is interested [here](https://gist.github.com/CHEF-KOCH/f9df0a3f2457a641d7c6db0965d21b2e) is the working one which currently works with the v1 (remove the patch files in Doom).
