### ISSUE TITLE
Autosplitter not working anymore

### ISSUE THREAD

**Issue by Rawrnekton** [LiveSplit/LiveSplit#570]
Someone hit Darkid with a slice of lemon wrapped round a large gold brick (please dont do that).
He updated (16 hours ago) the asl for The Talos Principle but that doesnt work.

here is the last usable one:

https://gist.github.com/jbzdarkid/611993edbfc9a774e95234166be52f2a/f5ab48c84626e43a2bfeb174a289baf2e5f34b79

**OLD:**
Hello,

Problem: [Picture](http://i.imgur.com/OCQFISr.png)
Game; The Talos Principle, Autosplitter by Darkid

The Options dont show up anymore and any utilty of the autosplitter script is gone, livesplit still works fine.

It worked until yesterday, but today after i booted it seems broken, file still gets downloaded automatically from this [url](https://gist.githubusercontent.com/jbzdarkid/611993edbfc9a774e95234166be52f2a/raw). Content of the file looks fine (seemingly no syntax errors, i have merely spend 20 minutes on the how to write a autosplitter site, so there is a good chance my judgement is wrong).

* Do i need any dependencies i might removed? (Is anything not c#?)
* Its running on win10
* I redownloaded LiveSplit 1.6.9
* I recreated new splits
* the only other autosplitter tested "Alien: Isolation", works fine--

**Comment by CHEF-KOCH** [comment]
How you got it working again?

**Comment by Rawrnekton** [comment]
the version 20 of the file was syntactically broken (he missed an equal sign), but he fixed it about 15 hours ago


just go to your components folder inside livesplit and delete the old one (should be called just "raw"), then activate the autosplitter again and it downloads a working version


sidenote: as i edited into the post, i manually downloaded version 19 and used that until i noticed what was broken



-----Ursprüngliche Mitteilung----- 
Von: CHEF-KOCH <notifications@github.com>
An: LiveSplit/LiveSplit <LiveSplit@noreply.github.com>
Cc: Rawrnekton <jonathangerdes1@aol.de>; State change <state_change@noreply.github.com>
Verschickt: Mi, 20 Jul 2016 2:54 pm
Betreff: Re: [LiveSplit/LiveSplit] Autosplitter not working anymore (#570)



How you got it working again?
