### ISSUE TITLE
Option to change LiveSplit's refresh rate

### ISSUE THREAD

**Issue by ROMaster2** [LiveSplit/LiveSplit#578]
The current setting of 40Hz makes things sort of odd for streams that display 1/100 seconds. If a run is manually retimed, it has a bit of drift when compared against the recording. An option to change the refresh rate would be helpful for competitive runs or just making sure the timing is right on something. I suggest having a hard limit of 300Hz (similar to various games).

CPU usage shouldn't be a problem for most people, and if it is, they can leave it at the default value. A tooltip could appear when hovering over the input box warning against setting it too high.

**Comment by ROMaster2** [comment]
Added with #1195

**Comment by Avasam** [comment]
As a note. #2095 re-implements #1195  (just kept up to date with recent `master`, it's basically ROMaster2 's code with one small tweak). I also offer a build https://github.com/Avasam/LiveSplit/releases
