### ISSUE TITLE
Split Time into "Paused Time" when you pause

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#594]
When you pause, you should have some way of accessing the actual Real Time again.

Noticed this in Linkxie's stream where she was thinking a lot about whether she should be pausing the timer or keep it running.

**Comment by fatalis** [comment]
test

**Comment by ROMaster2** [comment]
Maybe record checkpoints marking when the timer is paused/unpaused. The runner can re-add the times at the end if necessary.

**Comment by wooferzfg** [comment]
https://github.com/LiveSplit/LiveSplit/issues/736
