### ISSUE TITLE
LiveSplit not recognizing .lsl and .lss

### ISSUE THREAD

**Issue by GameguySD** [LiveSplit/LiveSplit#604]
Hey! 

Been using Livesplit for a good while now, and decided to categorize my split/layout files a little better to make setting up livesplit easier for runs. I moved all my splits and layouts into respective game-specific folders I made within the Livesplit program folder. However, selecting them through the Livesplit.exe right-click menu no longer works. Some splits show as doubles in the dropdown menu and have submenus when moused over to show the same splits twice(at least one of these is fake). However, I can manually click some sets of splits and some layouts in the folders I put them in (which is the only way for many splits to work now). 

Is there a way I can fix this to make the dropdown menu functional again?

Thank you.
-GG

**Comment by wooferzfg** [comment]
under Open Splits, there's an option to change which splits appear in the dropdown.
