### ISSUE TITLE
Second 'Best Segment' splits for theoretical best time/time savable

### ISSUE THREAD

**Issue by ROMaster2** [LiveSplit/LiveSplit#615]
Your personal best segments is useful for knowing how well you've on a particular segment. Another comparison with the TAS time/#1 IL record/how much you know you can save can give a more optimistic view when a runner is so far behind not even matching their best segments can save the run.

It could put both gold/rainbow split to use for beating your best vs beating an IL record. With Speedrun.com integration, it could even fill itself out for some games.

**Comment by abney317** [comment]
2nd this idea. Currently live split doesn't allow you to do "Possible Time Save" against anything other than your best segments. Usually that's fine and people compare PB vs best segments to see the possible time save. But I'd like to be able to set a Possible Time Save component up for PB vs IL WRs (or any other custom comparison)

**Comment by pojebunny** [comment]
I don't know if I understand correctly, but you can add "comparisons" to your splits by importing splits (that you can ofcourse obtain on splits.io).

Then in Layout -> Splits module settings, you can add 2nd column with that comparison, so you can see PB and WR at the same time :P

**Comment by wooferzfg** [comment]
This is best handled with a custom comparison.
