### ISSUE TITLE
Global hotkeys with Xbox One controller

### ISSUE THREAD

**Issue by TheGerboise** [LiveSplit/LiveSplit#631]
Hello,

Hotkeys do not work with my Xbox One controller only when the focus is not on the LiveSplit window (i.e. when they should be global...).
Global hotkeys are activated, I tried 3 other different controllers, including an XBox 360 controller, it all works fine with them, works fine with hotkeys bound to keyboard or mouse wheel, tried to run as admin...

Don't know what else to try... Thanks for your help !

**Comment by wooferzfg** [comment]
https://github.com/LiveSplit/LiveSplit/issues/517
