### ISSUE TITLE
Can't save settings

### ISSUE THREAD

**Issue by CyndaKill-SH** [LiveSplit/LiveSplit#632]
Hello,
My computer died last week, I just bought a new one. I downloaded LiveSplit 1.6.9, did some Pokémon Blue NSC runs, and when I closed LiveSplit, this window popped up :
![settigs couldn t be saved](https://cloud.githubusercontent.com/assets/11931729/19693650/9e13671e-9adc-11e6-8e02-5c4f202b0f96.jpg)

I did some testing, and it happens literally everytime. When I don't do anything else than just open and close, when I load a layout, or splits, or both, when I save changes or not (I still can do it, no problem on this side), when I change the hotkeys... And it even happens with the 1.6.5 version that worked perfectly on my old computer.
I don't mind changing my hotkeys and loading my splits and layout everytime I launch LiveSplit, but it would obviously be better if I didn't have to... So if someone knows if I did something wrong, or if it's a known problem, please let me know ^^

Thanks for your help !

**Comment by d4rkd0s** [comment]
I am having the same issue... It's annoying as heck having to re-setup all my hotkeys each time I I start LiveSplit.

I am a developer myself and I will assist in troubleshooting and fixing this issue as much as I can. People just let me know.

**Comment by d4rkd0s** [comment]
@CyndaKill-SH I was able to fix the issue by running the program as "Administrator"... I think its a permissions issue on writing to the settings file area.

**Comment by d4rkd0s** [comment]
You can follow this to always run as admin.
https://technet.microsoft.com/en-us/library/ff431742.aspx
