### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ekaj113** [LiveSplit/LiveSplit#636]
First off, I want to say that I don't know if this is a fault with my computer or the software.
Second off, I am running this on Linux with wine.

The error says "LiveSplit has crashed due to the following reason: An exception was thrown by the initializer for LiveSplit.Web.Share.SpeedrunCom"

Hope I can help or at least can get my version working

**Comment by Tdrayne** [comment]
I'm having the same issue

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
I am also using linux and having a similar issue
ERROR:

"LiveSplit has crashed due to the following reason:

Success"

Afterwards nothing happenes and the application does not load...
