### ISSUE TITLE
Pressing the final split key twice auto resets

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#638]
sva just accidently pressed the final split key twice and it reset the timer. While the PB is still saved, he couldn't talk about his PB or create a proper screenshot for Twitter. So maybe this should be an option?

**Comment by wooferzfg** [comment]
It's not really a bug since it's intended and based off of WSplit behavior, but yeah, there should maybe be a way to turn it off.

**Comment by hallcristobal** [comment]
Why should this be an option? To me it would make sense that the split button wouldn't reset the splits, only the reset button would.

**Comment by CryZe** [comment]
Yeah, we should just change the behavior so that it only does this in timer only mode. I see no advantage of having this in a normal speedrun.

**Comment by wooferzfg** [comment]
https://github.com/LiveSplit/LiveSplit/pull/672
