### ISSUE TITLE
Add multiple columns to Subsplits

### ISSUE THREAD

**Issue by wooferzfg** [LiveSplit/LiveSplit#64]
The labels component should still go above the rest. There should be a way to specify the comparison and timing method for the section header (since the header doesn't use the columns).

**Comment by pojebunny** [comment]
I'll just comment on that as it looks like an easy feature to add :3

**Comment by wooferzfg** [comment]
https://github.com/LiveSplit/LiveSplit.Subsplits/commit/09e8b545bb4129761a6d4d3d9f96ecb8640d8856
