### ISSUE TITLE
ASL does not seem to function through Wine.

### ISSUE THREAD

**Issue by prohunterdogkeeper** [LiveSplit/LiveSplit#654]
I'm not sure if you're actually interested in supporting your software on linux through Wine, just close the issue if it's a won't fix. I also noticed that the ASL component is in a separate github repo, should I post this issue over there since that's where the problem is?
Running in 1.6.9, but the issues persist when using 1.6.
Two issues: (Probably unrelated? Should I make a different issue for each?)
1. When downloading an ASL file through the settings of a split file, the download fails ("Error downloading file" is the only message reported), it then tries to load a file from a location that doesn't exist. (In this case it tried to read from "E:\\Stream\\LiveSplit_1.5.5\\Components", I have not loaded a drive E into the prefix.) I haven't read through the relevant code here, but I assume it fails because it tries to download to a location that doesn't exist?
2. Livesplit throws an exception when trying to load in any ASL script manually through the layout->Scriptable Auto Splitter menu. 
It throws the exception upon initiation of the Methods class, (LiveSplit.ASL.ASLScript.Methods) and since the only code being run in the initialization of that class that really can fail to execute is LiveSplit.ASL.ASLMethod.ASLMethod() it seems that that's where the failure is.
I'd try running ASLMethod("") outside of the constructor just to get the full exception, but then I realized that I have no idea about how much work it is to set up a build environment through an emulation layer. I might try this at some point if nobody answers.
The exact error Wine gives me is
> err:eventlog:ReportEventW L"The type initializer for 'Methods' threw an exception.\n\n   at LiveSplit.ASL.ASLScript.Methods..ctor()\r\n   at LiveSplit.ASL.ASLParser.Parse(String code)\r\n   at LiveSplit.UI.Components.ASLComponent.LoadScript()\r\n   at LiveSplit.UI.Components.ASLComponent.UpdateScript()"

It seems that since the second error prevents LiveSplit from being able to even read the ASL file, it means that even if the first problem is solved, it still wouldn't be able to read the ASL file, so the second error is the actual problem.
Don't hestitate if you need any more info, or want me to try something or run some new binaries.

**Comment by fatalis** [comment]
Wine issue, won't fix.
