### ISSUE TITLE
Programme disappeared

### ISSUE THREAD

**Issue by TheodoreYuen** [LiveSplit/LiveSplit#699]
I am using a macbook pro with OSX El Capitan, I download the whole folder and the livesplit is not in it, what can I do?

**Comment by hallcristobal** [comment]
It sounds to me like whatever browser your using is blocking the exe. possibly flagging it as a potential risk. Check your firewall settings and content settings in your browser.

**Comment by just-ero** [comment]
Closing as unrelated.

LiveSplit is a Windows-only software.  
LiveSplit One is the cross-platform rewrite.
