### ISSUE TITLE
Linux port

### ISSUE THREAD

**Issue by jonlaokan** [LiveSplit/LiveSplit#715]
Is a Linux port still on the table or should we continue to use it via wine for now?
Thanks!

**Comment by CryZe** [comment]
We are actively working on a cross-platform port of LiveSplit. It's similar to OBS Studio and Minecraft Pocket Edition in that it's a complete rewrite, so getting to feature parity with normal LiveSplit will take a while. However other than layout editing, everything else already behaves just like the original LiveSplit.

**Comment by AnthonyD973** [comment]
Any news on this yet?

**Comment by hallcristobal** [comment]
@AnthonyD973 please follow LiveSplit/LiveSplitOne for future cross platform updates.

**Comment by hallcristobal** [comment]
You can find future the cross platform build that CryZe was referencing is in the LiveSplit organization as LiveSplitOne. Take a chance to look at that. :)

**Comment by BuyMyMojo** [comment]
any update on linux support?
