### ISSUE TITLE
Can't Save Splits

### ISSUE THREAD

**Issue by Bibzuda** [LiveSplit/LiveSplit#726]
Whenever I try to save my splits I get a popup that says splits could not be saved! I've tried changing the name of the file, the file path, restarting the program, my PC, anything I could think of and still get same error. It still creates a file with the name I choose at the spot, but when I try to open it it says it was not recognized as a splits file even though it is .LSS

**Comment by Bibzuda** [comment]
Was an issue with one of my components which worked when disabled.

**Comment by raymer37** [comment]
What component was it?
