### ISSUE TITLE
LiveSplit displaying the wrong times

### ISSUE THREAD

**Issue by chemicalcat59** [LiveSplit/LiveSplit#729]
I am starting to speedrun an online flash game called Cat Ninja, and my current time is 9:24, but when I open my timer to do another run, it is displaying wrong times for every split, as well as a final time of just over 11 minutes. When I go to edit my splits, however, it shows my original time of 9:24 with correct splits. Does anyone know how to fix this?

**Comment by chemicalcat59** [comment]
Edit: I just did another run (9:44), and my timer showed 10:35 for the final time after completing the run. 

EDIT: While writing this, my timer switched to the correct time (9:24), and is currently changing every time I look at it (between random times like 8:23, 9:24, 10:27), etc.

**Comment by JermJermJerm** [comment]
Are you switching comparisons (Best Segments / PB / Average Segments / etc.) unknowingly?
I think left and right arrows change comparisons by default
