### ISSUE TITLE
The selected file was not recognized as a layout file

### ISSUE THREAD

**Issue by GalladeGalaxy** [LiveSplit/LiveSplit#733]
Hey! I've made a layout for LiveSplit that I was very proud of, but today when I tried to open it, it just said "The selected file was not recognized as a layout file. (The root element is missing.)" Is there anything I can do? I excactly don't want to have to remake my layout.

**Comment by Hyphen-ated** [comment]
why don't you post the file in question

**Comment by DylanMurphey** [comment]
I think this issue can be closed without any offense taken unless @GalladeGalaxy still has the layout file in question.

**Comment by wooferzfg** [comment]
The layout file was likely accidentally replaced by some other file, or didn't save properly
