### ISSUE TITLE
LiveSplit says VLC and ActiveX aren't installed, but they are

### ISSUE THREAD

**Issue by MikeGamePro** [LiveSplit/LiveSplit#752]
Every time I try to add a video into my layout, I get the error message, "Video Component Could Not Be Loaded - VLC Media Player 2.2.1 (64-bit) along with ActiveX Plugin need to be installed for the Video Component to work."
I have the newest version of VLC (2.2.4) installed with ActiveX, yet I still get this error message.
I have re-installed VLC three times.

**Comment by fatalis** [comment]
try 2.2.1

**Comment by MikeGamePro** [comment]
Downgrading to 2.2.1 didn't work

**Comment by wooferzfg** [comment]
you need specifically the 64 bit version of 2.2.1 because 32 bit won't work

**Comment by MikeGamePro** [comment]
Thank you! I guess I never noticed the VLC website set the default version as 32 bit. This worked :)
