### ISSUE TITLE
LiveSplit UI behaviour is inconsistent from time to time

### ISSUE THREAD

**Issue by RickardNi** [LiveSplit/LiveSplit#765]
Not sure if this is a known bug or not, haven't found anything about it.

Starting LiveSplit after using different splits sometimes causes the application to start in a mode where all UI text are scaled up, or much bigger. Exiting the application and restarting it sometimes resets it to proper behaviour.

I created a video to demonstrate the behaviour:
[https://www.youtube.com/watch?v=87sGGHcwOA8](https://www.youtube.com/watch?v=87sGGHcwOA8)

This forces me to use a new folder and LiveSplit application for each game/split I want to use, which is quite annoying.

**Comment by wooferzfg** [comment]
This has been a known issue for a while, but I haven't been able to figure out a good fix for it. Could you send me your splits and layout so I can see if I can reproduce it again?

**Comment by just-ero** [comment]
Does this issue persist in the most recent stable version of LiveSplit?

**Comment by wooferzfg** [comment]
This was likely fixed in https://github.com/LiveSplit/LiveSplit/commit/4c9c725898b46d79669156ea7ac7ca019de66101
