### ISSUE TITLE
1.7.1 breaks my fonts (text outlines)

### ISSUE THREAD

**Issue by Ammako** [LiveSplit/LiveSplit#780]
Hey, I downloaded LiveSplit a week or two ago, I've set up my splits and layout using fonts I like and I was satisfied with it.

Then a few days later, I got the notification that a new update was available (1.7.1), so I did the update, but after the update, my fonts are very blurry and just don't look as good. I believe this is caused by the new Text Outlines option.

Could we get the option to disable text outlines entirely? That feels like it might be the simplest solution to keeping the fonts looking like they used to.
For now I've re-downloaded 1.7.0 and ignore the update notification every time, but I'd like to be able to just update to take advantage of new features I might like + bugfixes :p 

[Image to show what I'm talking about](http://i.imgur.com/si1V89a.png)

**Comment by wooferzfg** [comment]
Try downloading the Dev Build and see if it works for you.

**Comment by Ammako** [comment]
It does fix my issue, thank you!
Although, it seems that text outline doesn't work at all for Times and Splits/Title now, for people who may actually want to have text outlines on everything. Tried with other fonts in case it was just this one font, but the text outlines only applies to the Timer now.

**Comment by wooferzfg** [comment]
There's no way to do Text Outlines without Anti-Aliasing (as far as I know).

**Comment by wooferzfg** [comment]
So you'd need to turn on Anti-Aliasing for the Text Outlines to show up on all text.

**Comment by Ammako** [comment]
Yeah, that makes sense! I guess the problem was with anti-aliasing which was somehow always on, and not with the text outline feature in itself.
Is there any hint anywhere in the program that tells you anti-aliasing must be enabled for text outlines that I may have missed? If not, might be worth adding something so that people don't start reporting that the outlines aren't working ;p
