### ISSUE TITLE
LiveSplit wont open my PB Split now

### ISSUE THREAD

**Issue by CarNage64** [LiveSplit/LiveSplit#789]
most of my other split files work jsut fine but when i try and open my PB file which i was using jus
[Split.zip](https://github.com/LiveSplit/LiveSplit/files/1067034/Split.zip)

t fine yesterday it says it isnt recognized as a splits file

**Comment by wooferzfg** [comment]
some of your splits file got corrupted. mid recovered most of your splits https://cdn.discordapp.com/attachments/266217745446600704/323703693067419658/CarNage_Salvaged.zip

**Comment by CarNage64** [comment]
thanks :D
