### ISSUE TITLE
Program eventual crash if update notification is canceled

### ISSUE THREAD

**Issue by Neerrm** [LiveSplit/LiveSplit#798]
When notified that there is an update available and the user chooses to cancel and not update, LiveSplit will eventually lock up after a period of time. Experiencing this on Windows 10. There doesn't seem to be any consistent amount of time before the crash occurs, but it does happen consistently.

**Comment by wooferzfg** [comment]
could you send me event logs from when it locked up? https://pastebin.com/M3n52ABV

**Comment by wooferzfg** [comment]
This is likely resolved now that the update prompt is invoked.
