### ISSUE TITLE
Livesplit crashing on "edit splits"

### ISSUE THREAD

**Issue by jjplaysgames** [LiveSplit/LiveSplit#799]
When i have to change the format of my splits, or add new ones, I click on edit splits, and my livesplit crashes completely! this is really annoying because sometimes I forget to save my splits, and then I click edit splits, and I lose everything! I wish there was some way to fix this

**Comment by wooferzfg** [comment]
Does it give an error message when it crashes?

**Comment by jjplaysgames** [comment]
it just says, "livesplit is not responding"

**Comment by wooferzfg** [comment]
can you send event logs? https://pastebin.com/M3n52ABV

**Comment by CryZe** [comment]
Or rather, possibly some splits and a way to replicate this. I think that
may be better.

2017-06-21 22:50 GMT+02:00 Sergey Papushin <notifications@github.com>:
