### ISSUE TITLE
Global Hotkeys not working when XSplit is in focus (Windows 10 only)

### ISSUE THREAD

**Issue by CaracarnVi** [LiveSplit/LiveSplit#815]
Global Hotkeys in Livesplit are not working if XSplit is in focus. Only in Windows 10, it never did this in Windows 7. I have the "deactivate for other programs checked." Even when global hotkeys are disabled in XSplit, the hotkeys in LiveSplit still will not work. Not sure if this is something that can be fixed in LiveSplit or not, but I am curious to see if this has been a problem for anyone else.

Edit: This now also happened when Task Manager was focused... I will keep updating this whenever I find another program that hijacks LiveSplit's hotkeys.

**Comment by aggixx** [comment]
Shot in the dark here, but programs sometimes have trouble with hotkeys if you are focused on a program that was run as admin (which I assume XSplit is) when the program doing the monitoring was not. Try running LiveSplit as admin as well, that will fix it if that is really what the problem is.

**Comment by AshMarks** [comment]
tested @aggixx 's workaround with task manager and it worked for me.

**Comment by CaracarnVi** [comment]
running LiveSplit as admin seems to have fixed the issue. Thank you!
