### ISSUE TITLE
Start/Pause shortcuts

### ISSUE THREAD

**Issue by TheMiziko** [LiveSplit/LiveSplit#826]
Hey guys ! Is there any way to make keybinding for start/pause button ? For now, it either resets the timer, or makes a split and resets again, and there's no way for me to make it work.

**Comment by wooferzfg** [comment]
Go to Settings -> Hotkeys and set two different buttons for Start / Split and for Pause. Make sure that these buttons are different than what you set for any other hotkey.

**Comment by crabman1234** [comment]
when im in the game i cant quickly start it
