### ISSUE TITLE
LiveSplit using the incorrect Font for the 'minus' symbol

### ISSUE THREAD

**Issue by EvilAsh25** [LiveSplit/LiveSplit#835]
Image of the problem: [Imgur Image](http://i.imgur.com/o91PNbv.jpg )

LiveSplit 1.6.9 is running on the left and 1.7.0 (same with later versions) on the right.  This seems to have broken on the change between these two versions.  I use my own custom font, you can download it here: [Chrono Cross Font](https://goo.gl/EechG9). 

This only happens in the split number text where it shows time Deltas, and also includes the Previous Segment component.  If I use the 'minus' in a split name it shows up correctly.

**Comment by CryZe** [comment]
It's because your font doesn't properly handle the Unicode Minus. You are using the ASCII Hyphen-Dash (because that's what is on the keyboard).

**Comment by EvilAsh25** [comment]
Cool thanks.  Now I know where to look to try to fix this.
