### ISSUE TITLE
Livesplit Transparency And Click Prevention

### ISSUE THREAD

**Issue by ChronoKong** [LiveSplit/LiveSplit#840]
So I would like to know if you can make it so livesplit is transparent for the runner in game ik how to make it transparent for my recordings/streams but how do I make it transparent in game for me, also how do I make it so when im in game i dont click on the timer if its in the top right
EX: If im in a run and aim in top right (where my livesplit timer is) and click to shoot it pauses the game and I have to tab back in and unpause the game again.

**Comment by wooferzfg** [comment]
https://github.com/LiveSplit/LiveSplit/pull/882

**Comment by Brambor** [comment]
> #882

Doesn't address the transparency.
