### ISSUE TITLE
"Script to Run" Column in Splits Editor?

### ISSUE THREAD

**Issue by Ecksters** [LiveSplit/LiveSplit#845]
So I'm talking with some people and we're looking at a way of essentially making API calls every time a runner splits, and have the API call be specific to the split in question.

Now, with the current limitations of Components, it seems like the easiest way to add this would be to submit a pull request for this repository and simply add a new column linking to a "Script to Execute" on each split, either linking to a file script, or perhaps running some sort of scripting options internally (most likely the former.) 

Before we put in all that effort though, we'd like to know if this is a feature that actually _could_ be easily implemented with a Component, and if not, if such a feature would be considered useful enough for the Pull Request to be accepted.

**Comment by Ecksters** [comment]
As a use-case example, this could be used to send a command to a bot with each split, and the bot can link to videos/pages explaining the current split and glitches used in it.

**Comment by hallcristobal** [comment]
This could be easily implemented as it's own component, actually. A component can see the whole state of LiveSplit, including the current split, splitting events, and all splits that are in the current run. I don't feel like this could benefit from being a pull request for the master repo.

**Comment by Ecksters** [comment]
Can a component add a column to the Splits Editor, and keep a unique value for each split?

**Comment by hallcristobal** [comment]
It cannot add a column directly to the Split Editor, however you can get the same effect from a table in the component's own settings page. As for saving a unique value you can save and load to and from files at will as a component so that shouldn't be an issue.

**Comment by Ecksters** [comment]
Awesome, sounds good then, we'll look into it as a Component.

**Comment by Ecksters** [comment]
Just a quick final question, are you aware of any currently existing Components that have per-split settings that we can use as a reference?

**Comment by wooferzfg** [comment]
https://www.nightgamedev.com/sgl but idk if there is source code

**Comment by Ecksters** [comment]
https://github.com/iNightfaller/SpeedGuidesLive

Awesome, thanks @wooferzfg
