### ISSUE TITLE
LiveSplit disappearing mid game

### ISSUE THREAD

**Issue by BaldrOfTheNorse** [LiveSplit/LiveSplit#848]
https://www.youtube.com/watch?v=C2yGcq5yvyE&feature=youtu.be

Here is a video of what I am talking about. At the end it disappears. Any idea why?

**Comment by wooferzfg** [comment]
What OS are you on?

**Comment by BaldrOfTheNorse** [comment]
Windows 7

**Comment by wooferzfg** [comment]
Turn Aero mode on if you don't have it on

**Comment by BaldrOfTheNorse** [comment]
I just turned it back on and it still disappears.

**Comment by BaldrOfTheNorse** [comment]
If the timer is running, that doesn't disappear. The title still does, however.
