### ISSUE TITLE
Shantae: Half-Genie Hero creates Errors

### ISSUE THREAD

**Issue by totenphal** [LiveSplit/LiveSplit#863]
Moderater of the Shantae: HGH Leaderboard here. 
After the restructuring of the Leaderboard which was necessary, the splits don't load and or can't get saved anymore.
The moment you open the Info-Tab you get Error-Messages. 
Several different persons already have this issue and it makes it hard to keep track of our splits.

Help would be appreciated.

**Comment by wooferzfg** [comment]
Could you send your splits file?

**Comment by totenphal** [comment]
Include empty and ones with some times.

[Shantae HGH Splits.zip](https://github.com/LiveSplit/LiveSplit/files/1268906/Shantae.HGH.Splits.zip)

**Comment by wooferzfg** [comment]
so the issue is that the Risky-Mode variable has no values. i'll fix the crash, but a temporary solution for you guys would be to either remove that variable or to give it a value of some sort.
