### ISSUE TITLE
Copy-pasting splits doesn't properly account for skipped splits

### ISSUE THREAD

**Issue by jhobz** [LiveSplit/LiveSplit#867]
If you copy a series of splits from the Splits Editor that includes one or more blank splits and paste them into another set of splits, the blank splits will not copy things over properly.

**Comment by wooferzfg** [comment]
Could you explain how to reproduce this issue? I'm having trouble figuring out what issue you're referring to.

**Comment by jhobz** [comment]
1. Open instance of livesplit with splits file "A" that has one or more blank split times, _but not all_ (as in, not a new splits file).
2. Open second instance of livesplit with splits file "B" that has one or more blank split times.
3. Select split times of entire column in splits file "B" and copy to clipboard.
4. Paste in splits file "A," starting at the top.

Observe that split times are condensed, ignoring the spots in splits file "B" that had skipped splits (IOW, not skipping a split in "A" when pasted).

Hopefully that should work.
