### ISSUE TITLE
possibly wrong condition in getter

### ISSUE THREAD

**Issue by drmalc** [LiveSplit/LiveSplit#87]
Reference:
https://github.com/LiveSplit/LiveSplit/blob/master/LiveSplit/LiveSplit.Core/Model/LiveSplitState.cs#L86

Seems like the condition for the "CurrentSplit " getter should be:
(CurrentSplitIndex < 0 || CurrentSplitIndex >= Run.Count)

**Comment by CryZe** [comment]
You are right. Quite weird that we never saw that O.o
