### ISSUE TITLE
LiveSplit crashing when selecting game.

### ISSUE THREAD

**Issue by FredBloggs2169** [LiveSplit/LiveSplit#872]
When I try to select a game, LiveSplit decides to crash on me after each letter. When I do get the game I want, it says there is no autosplitter for it, but it works for my friends. I've tried different versions but can't get it to work. The game i'm playing is Left4Dead2.

**Comment by wooferzfg** [comment]
Is there any message when it crashes?

**Comment by just-ero** [comment]
Closing due inactivity.

There is no clear cause for the issue. The user did not provide sufficient information to work on the issue.
