### ISSUE TITLE
splits section shrinking when increasing times font or icon size.

### ISSUE THREAD

**Issue by allibear17** [LiveSplit/LiveSplit#890]
Whenever I increase the icon size, or the font size for times the entire splits sections shrinks.  Even when I have the splits height at max, it will shrink anytime I make these changes.  This is with no text for the split names.  If I add the texts back in, it won't shrink until the icon pushes the text into the times.

Something similar happens when I change text/time fonts.  Whether I type in a size or not.

I'm trying to make icons and times a bit large since I have poor vision, while keeping the horizontal size down to a minimum so I can keep splits, chat and my emu all on screen.

If there are any files that'll help, I'll gladly upload them.  In general it'd be nice to have support for larger sizing for fonts and sections,.

**Comment by wooferzfg** [comment]
Are you using the newest stable version of LiveSplit (1.7.4)? Also, could you upload a video of this behavior?

**Comment by allibear17** [comment]
I am using 1.7.4 and here's a link.  The mouse cursor isn't captured correctly, but I think you can still see what I am clicking clearly enough.  Also, if it matters I have a custom dpi set in windows to 130% (which might be whats affecting the mouse capture).  I am using windows 7 64 bit.  

Video:
https://youtu.be/8WEYlFZkpDU

Split/Layout File
https://drive.google.com/open?id=0BwbBHCdnLfcqd3ZuRGIyT0FicGc

**Comment by wooferzfg** [comment]
The reason this is happening is because the overall width of LiveSplit is less than the minimum width that the Splits component requires. I'd recommend removing one of the columns in the Splits component settings and changing the other column to show a Delta or Split Time. That way, it'll be a lot less wide.

**Comment by allibear17** [comment]
Thank you!
