### ISSUE TITLE
Autosplitter doesn't work on any game

### ISSUE THREAD

**Issue by Beruno** [LiveSplit/LiveSplit#913]
Hello everyone, i've tried several times to use autosplitter on games such as "A hat in Time" and "The binding of isaac" but i just can't get it to work, Live split doesn't start the timer automatically nor does it make the splits. I've tried including the splitting scripts manually but it still doesn't work. Any ideas on how to fix this? Thanks in advance. 
![image](https://user-images.githubusercontent.com/33266637/32247179-68146796-be79-11e7-8b0d-59a9aae2314f.png)

**Comment by wooferzfg** [comment]
Try running both the game and LiveSplit as Admin.

**Comment by Beruno** [comment]
Tried it just now and still doesn't work :/

**Comment by CryZe** [comment]
Can you check if LiveSplit's exe file is called LiveSplit32.exe?

**Comment by Beruno** [comment]
The file i have is named "LiveSplit.exe". Could it be a different version?

**Comment by just-ero** [comment]
Closing as stale.

There is no clear cause for the issue. The autosplitters have had changes since the time of the issue.
