### ISSUE TITLE
OBS Window Capture Black Space

### ISSUE THREAD

**Issue by cooopercrisp** [LiveSplit/LiveSplit#944]
I've been having this problem since getting a new laptop with Windows 10 where, when capturing the LiveSplit windows in OBS, there is extra black space to the right and down from the window capture. For a 400x120 LiveSplit layout, OBS is interpreting this as 500x150, which is 1.25x greater than the expected ratio on both sides. ![figure 1](https://user-images.githubusercontent.com/21260285/33658916-677bbe3a-da4c-11e7-80a6-3d818452351d.png) I also tested a 600x720 layout, and the resulting aspect ratio in OBS was 750x960, which is again 1.25x the expected amount on both sides. ![figure 2](https://user-images.githubusercontent.com/21260285/33658917-678e8222-da4c-11e7-9f89-4968a63c1efa.png)

I am wondering if this is an issue with OBS, with Windows 10, with my laptop, or with LiveSplit. My OBS version is 20.1.3 64-bit, but the 32-bit version had the same issues as well. My Windows 10 version is 10.0.16299. My LiveSplit version is 1.7.4.

**Comment by Darien117** [comment]
I'm having literally the exact same issue, trying to use LiveSplits with OBS and it's like OBS is picking up extra black space to the right and below my splits.I'm not sure what the issue is, or how to fix it.

**Comment by cooopercrisp** [comment]
This morning, I discovered that when I hooked my laptop to a desktop monitor and have the LiveSplit window on the monitor, the aspect ratio issue goes away. The source of the problem is therefore with my laptop’s display and not with LiveSplit.
