### ISSUE TITLE
Not working unles in first plane

### ISSUE THREAD

**Issue by LoboVS** [LiveSplit/LiveSplit#954]
I want to make a run of Overwatch the practice range, however, Livesplit will not show up and if I have anything else in first plane that isn't livesplit, it will just ignore my commands.
For instance, I've set "g" as the start/split button, but if I'm playing the game, livesplit will simply be on the background not working, or even showing up on my screen

**Comment by hallcristobal** [comment]
First go through and make sure that:
A) Global hotkeys are enabled and working (try with some other program)
B) Make sure whatever your hotkeys are are not bound in game anywhere

Also try running OW in windowed or borderless-windowed as well.

**Comment by just-ero** [comment]
Closing as unrelated.

No application can be displayed on top of a full screen game. This is not an issue with LiveSplit.
