### ISSUE TITLE
[UBUNTU 16.04] Trying to make it work with Wine

### ISSUE THREAD

**Issue by Hankyu0** [LiveSplit/LiveSplit#957]
Hi I'm a noob on linux and I've been trying to make LiveSplit work, so i installed Wine (idk what version it is) and tried to launch LiveSplit through terminal with "wine LiveSplit.exe", but everytime and with every Livesplit version I've tried it gives me this error message :

livesplit has crashed due to the following reason : an exception was thrown by the type initialyzer for livesplit.web.share.speedruncom

I've tried to look it up online for a fix but nothing, please help

![capture du 2017-12-23 23-39-12](https://user-images.githubusercontent.com/34800862/34323099-838e75ee-e83a-11e7-89ae-98b3c1bb2420.png)

**Comment by wooferzfg** [comment]
consider following the development of LSO, a LiveSplit rewrite that works on all platforms: https://github.com/CryZe/LiveSplitOne

**Comment by Hankyu0** [comment]
Thanks for the answer! :)
