### ISSUE TITLE
LiveSplit isn't able to save Settings and/or Splits

### ISSUE THREAD

**Issue by mayuso** [LiveSplit/LiveSplit#958]
I've just tried LiveSplit on Windows 10 and I can use the timer and layout editor just fine, but then closing the software it always says "Settings could not be saved!" and "Splits could not be saved!".

I've tried with 1.7.4 and DevBuild and both have the same issue (I've also tried running as admin, as another issue answer suggested, but didn't work).

I'm starting to think it has something to do with this:

https://github.com/Disassembler0/Win10-Initial-Setup-Script/blob/master/Win10.ps1

I run that script as soon as I reinstalled W10 last week, is it possible that that script disabled some feature(s) that LiveSplit needs? Because I don't know what else can it be, apart from that this is a clean W10 install.

**Comment by mayuso** [comment]
I can now confirm the problem comes from that Script, not sure what function(s) cause the problem, I just rolled back everything and LiveSplit works perfectly again.

**Comment by hallcristobal** [comment]
I’m curious, did you run that script with default options, or did you change anything?

**Comment by mayuso** [comment]
Default options. I then run the exact script again but with opposite options (The ones in comments next to the equivalent option) and LiveSplit worked again.

I assume it's one or (at worst) a few options in that script that mess up something with LiveSplit, but I don't know which option(s) yet.

**Comment by Nathan-360** [comment]
Why I can't keep the livesplit layouts

**Comment by Nathan-360** [comment]
Why I can't keep the livesplit layouts
