### ISSUE TITLE
When Trying To Download I Only Get The Files for LiveSplit, Not The Actual "App"

### ISSUE THREAD

**Issue by Andreasbl00** [LiveSplit/LiveSplit#959]
The title basically explains it. When I try to download LiveSplit I only get the files of LiveSplit, but I can`t find the "app" anywhere. What do I do?

**Comment by wooferzfg** [comment]
The executable file is LiveSplit.exe. It only works on Windows.

**Comment by Andreasbl00** [comment]
@wooferzfg I have Windows, and when I try to download it I download files, it`s called "LiveSplit_1.7.3.zip

**Comment by wooferzfg** [comment]
You need to extract the files from the ZIP archive.

**Comment by Andreasbl00** [comment]
@wooferzfg  It worked :)
