### ISSUE TITLE
Missing game "Killer Instinct" (2013) in splits editor

### ISSUE THREAD

**Issue by Mhmmm** [LiveSplit/LiveSplit#980]
when editing splits, I can't select this game, probably because it has the same title as the first game in the series.

I'm talking about this one:
https://en.wikipedia.org/wiki/Killer_Instinct_(2013_video_game)
https://www.speedrun.com/ki3

And selecting "Killer Instinct" in splits editor is this https://www.speedrun.com/ki1

Sorry if this shouldn't be posted here, I wasn't sure where to report that.

**Comment by wooferzfg** [comment]
This issue doesn't seem to be happening anymore
