### ISSUE TITLE
Use livesplit-core for saving the splits

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplit#991]
While not initially planned, this seems to be the way to go for actually fixing our broken split files problem. livesplit-core isn't quite there yet, as no one had the use case of fully modifying Run objects through the C API yet, but that is going to be necessary in the C API eventually anyway, and this also nicely fixes our bug (hopefully at least). Layout files however possibly still have the bug (maybe some custom rust code for saving those?).

**Comment by wooferzfg** [comment]
This will be covered by https://github.com/LiveSplit/LiveSplit/issues/1754
