### ISSUE TITLE
Global Hot Keys and footpedal

### ISSUE THREAD

**Issue by Popplars** [LiveSplit/LiveSplit#994]
Whenever global hot keys are on and my foot pedal for splitting is plugged, the key assigned "1" on the number row above the keyboard will start the splits, it would be nice if this didn't happen so i wouldn't split when trying to type something into chat that contains the number one.

Global hotkeys must be on for my foot pedal to work as well, the number pad functions 100% correctly though.

This is a specific interaction with the foot pedal i have found.

**Comment by Xylol** [comment]
So your foot pedal is sending a "1" and I suppose you cannot change it?
What is the output of this page: https://keycode.info/ when you hit your pedal?
What other buttons presses is your foot pedal sending?
What happens when you turn the global hotkeys off and focus your split window?

**Comment by just-ero** [comment]
Closing as invalid.

LiveSplit cannot impact what key the pedal sends.
